---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: watchdog-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    url: AgB0Hw4uGi1GJJX3AjlvpUxIVtZsutdf0tcNIvWjjBBT7kFa9uBvYvy22LV0GmW2mfFnJQ09NEz4aog4FsKDoAplgomjmO4UtROxqe8nA5IqEgJfd6oW0njsTHO+yHQ0qrPx0Wn07cMyokc35XbcggfDDgFRTm5jjV0jZG+/qS8h1ZjeqcFTaipfdMrnvWBYgZcsR8Mlt7Tn4Apjlr2vTSiX21mGzdkJ8RpotUFXNu8YmHnxKUxbeKxVl0Ne9ARxRtxg2/sX/lcZb6/m3I8DPp9HPCV3pZBKgD3cAUf3xPi0Wt7/CaUGqe7AODCFEMPp5BBs5T+jL/UyMOiSdGaiPqMOEjxKxBupv7sQ0aoiJlVxh5LP3RYzBjk6JbXR/dyjA7Y5C/9pXLZ7XAlrqMHATBzbjj9w0evMpoDHrx4i4xcfJ1ub2ZSyAvdvFevpyZHmsx40nL9twiOcXg/+M/m3vO7zNGAt+P50nwLAsbMK7VyVwSwfRkmlSyWzbNCXgxRDvKr2chgKQ/3OZzU4OkyZUIrazQ6gevbgvOh1pSWFnK5QBJqHGGqAj4XOzzcl4DGtTHWcjlc8c3Y6PhPYXKx7H4FU3GHidwzL+0VVizQB8/Lhdrx62lvVvbHB6yYbZTndp1QlVUSh9KsRpdv4Vh/JzpwDU//Bp+yyU2WuxjLwxiZmgw5BAfyxsKsQOq6OD5/jVfQVCH4uTaDuyKDg2VnVH3qHRkcQ6+s/jAcOSWNd1UadKLBzfdvKB8z6oRpQEC9MJL27g8mY6P3vRP9XR4eEAGPYDXX0YlLO9YJrkLNiNiE=
  template:
    metadata:
      creationTimestamp: null
      name: watchdog-webhook-url
      namespace: monitoring
