---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: watchdog-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    url: AgAKSvVgQr+OCExDuYNnls8EHetjkuKfvlm/IauCNmiJpQaETv+7zGpBRsQLqaALFk8eWdnCYZnE7A4RFs16eA/svKWbfgPZjEi3/6B2/fl0+xVEt1bCLv5Dr4cdsDUDJ4h62L3CGNtnc2RI3QwL0YwpKUsR7yGQciLlLLL2HEqOxDBzx5+y8Xf/GER/48bjjhIvQVQ6S0dDJU+q5Gy5ayYJLBbziWTvnDjVlvC79voKjpnEFX5M+5umogkzU9POMs7DepSnbWcqJkC33aLSsCqf7h+8F7+K7EJcYW7sSEw2ltOzBGWqjoQLQunIiitQyYkJPro+GFUclhJV/w+QggbkHmLmgkZYIM7UqWjvWmpCCIamSGs0zYvIwZBCp8bNVO89oRa+zDvVC7oI4WDSUHBQw9Oi1xuSNWNxnS9yubC2Q0thlVQxtuaakRPO2E4Dea11hTp9DlDxi14b85dDfw9/EU9fK6G/dA3D9CoGMfPnj7kvoqYzs0r+YkqC40Z23f1pNs1AoxaPANdzEk0CrJfIkyvKe8GgVHObo6oHyEMtksoovdt+ZTcqIyRO41qVQqoBsyH5pERso/8orgnCMooBrob6cFUQ/ECks2etCoOVn4d88ZenWSjdasmyqVjNHcrM2H8j7fg6oX6DwWBaG0wWVO+egpKU3XODEeURchF1Zm/UDfTzkryGw05SYlHc6ON4t9NMMgDj2DSE7abND6ASc988eElMs1LAUdxQl5h77jnvM/NOCurk/wFC13wRa/CPStkfY/sOGQ==
  template:
    metadata:
      creationTimestamp: null
      name: watchdog-webhook-url
      namespace: monitoring
