---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: watchdog-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    url: AgAnHZaiR6bX1ZnQV9SFHt13diZdL+gr/I57M5vNjaJz/ETqAGKF4mE0KjwfOokq0d4N3wTOzzRNDFRDYDeAagrPofDRojRX2wKSZvC4GhklW0jlnNnplVJmcGoyHBh2IIjG2sNSYG3RgqR2GH3Gsq9ql9o7Jd8c8/0PghsbKPg4BzmXmm8udhuEANvDzwn5qmbWoeq7zfFeYVYzuj6ieBGAt/qi/R5f7uESPXIoqAVaE5XSXu423a3WHZMBvJlUCxn5v28BOX8svc5dNxpp+eu7GKWwvOqchbLnUPDb+4gwGm5mrXiBBW69406upENmEqk/xpWpvadexUPa3BLAifzJqBSmAQjqnEQxs5Dm9auIe5SD4GVqSjnNsy+B1gw/KydN5uirdSlK2BZT9JrSPhU5DF64RY45RbsOr/V00J/69XxvC9AMnRmoGr14mkCs+GFC3aMGnejHnXHb2gntpftNoYpgrhj6wJRMftpgsaPySshcja4/MvXNp0PClUTOmvH99kw3NpBXTHJusntALvU9YB4g2PsJAt8KQyNrfVAq8jGte+sqTYBUB8x79oDt/LP0GuRk/rpvMyzirkVN56JrfNzVE8EKBYQnuPIQeyU2mOZse1rU/cUA6FxfDZFtXtbtmqy9Rs1IfwM3dNeUEftS+yF1F8DxH77z9Hd+O9fO5SGoK/IW2HxXiI8HmqkxkVesMYnClIRC34/gu1B71KZxo1rYwBrc8ZNv49wmQrJ9CwR9OzvW6ofh+kLDszSIFP/ZP1jLdiUtmkcsCXg7DzQ=
  template:
    metadata:
      creationTimestamp: null
      name: watchdog-webhook-url
      namespace: monitoring
