---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redpanda-basic-auth
  namespace: drova
spec:
  encryptedData:
    .htpasswd: AgCwO2vESpxyXv3RqptT3RVQzdMnvjFd55lmY28fKlEKo7YU/2z1jlM7PmRJ8aHOmEaHLrx2pGfk9C+cKSDUoPXFzeHnmogFYlMIBUAZnrojOOymb9m7YH6eVf8Sg5p+7dxTHqNr5aO/cA5xsuNJrafKQFm/eQur/jvffKEhi9ZCS79gybcRhvqevsqFMxqIwPYrM4dQMgLyrtNXJWm0lm7NRQv+qlqSDVdP/RmEBM8C5y+J20sLYvEZzTEcJtZGk4gJ73ZGYbkEwr7wwi5zFmVX+gqfjRCJxRQYy0z4ftfXL8r1ilB/F1vuZOBnSXprZ3yF8zpr74GPvNAB5XzXNj9xkMQkEuraiERtpu40fr+1oYq1nuYQGjAqwBdKeR51Ur+fC1El/AVMbE3nBhZSsw9iiQEGVmkS19l+VyGkSrbaO9Gc2lUTIJr1p9wytR99JHEdZIRUy3ApCWpdouFJIN0y2toujJ9JQsQOHfic5Eg0lkIppmMEAeEd0o72lDuSpDvr+fEjY0XdFsVWTuD+9QiKnxH+y72HBAx5svoHtv/WQlPYihKUfpGS5eG4PC6QblTUtoZ0VJqUuLHlpBbJtNj9ODwhrfBKXrrtOCHgdBJA4RTvu7XIdf/cHJFAGEDvU7Lhc6pkY8jllwRzVtGqfRJYFiLn/2tKxfRhhQsPrBMHKMxHDgnJZgyGN0ElEaznT8RzQpW4gz/WyAQH00h7aHlbHOpdausOUGKxK2fkitv7Yg5U63Bg51DcDN8=
  template:
    metadata:
      name: redpanda-basic-auth
      namespace: drova
