---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redpanda-basic-auth
  namespace: drova
spec:
  encryptedData:
    .htpasswd: AgAjA6kG6Na6fvmLkt6zn6HPKojuthpCIfqusByIPqFMlJ2RKcHJ0A5bVI2i7bTk46jRW7FZUSZOB3XMvdzhDAQpfA4rBqRRlD1IaePDWNgk/T3Ak5SRQAl3npVsXMPwIqRZZx+8NZQl8chWJwlRaVeQZMOWEZ1G5X6NomSMlionuOl854VY6KAB1MdmKKK9QoR0ui9TlVIRUy7QCB1CR7cCv/5H0ocVEyoY0Lr7IUac5WWRsVPt9OFEzRD00mnGpqz8+nz27GGR0vlpWerNRYflyrM4KM/f2V73SzJnIe9HEHtGFnqfdJ6s2MDOzW9hJnWBSFUncd2rLvM3Ly8CrGp07Tt7PTcdKVoBEr6Fc/sRh4DZylXWZ9XspfIL9dbBBfmpTTcjqKbQGBtJhM8qGL65/Njrq296t6vODm1MJQtemLio8pHp4pW7ug9YAIYp6A9GyM6iNzHLMNRH0Z4vAqwZjEpVtqgDmaI9ic6JWejQQqvkheqwOV8JKzYV1wAS0Uw4lsSgskZcmZDAMtnM9/V0ua1bMeVM/kxnRD0vTr5uYwSOhASkLRC48cR79Mp4jAjkSFNydwaAeBtDX0hp8Ri9wY3LpDtua0fZDJkXM9NPh3UgbRBosmxG2YHNkCET72NyN/G28wU4FoOLcpCPYxPzXp3Q7+2sYqxLbb3a8dSKvu7HC+3tpjk982bPMQ5H+bvDx3b7wMf03qmHjfgYSWjRVrX3bUIdOy7qsP7TEofTOxVu4jRdj5e830I=
  template:
    metadata:
      name: redpanda-basic-auth
      namespace: drova
