---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-oidc-credentials
  namespace: netbird
spec:
  encryptedData:
    AUTH_CLIENT_ID: AgAwtvhAF7KZV5l1gdY7PXEbyJrKGtGVboAYZddXBMflBxYHGdjI/Fttno6WXbvVS5ruGzwZnJishwUmHD94Y/H0qIOW8lg75R1U2NKWg4JYyE3ZBKo4BJm0/RXPKzxYtZkv3fPiNtQceh2xogTIVPvzOwhPNaKn7bdtm9A4P8d1XsoLZ9yB2oHEAw9Kb5ilAAkeWZVZDVcxNC9et9pEQA8fXEqGrdIr/xkFcya4RgKo6ezANi4lWqSTnDZJ0Yu/tjcJTbPqsbkcNmr+5F0CDOnbLlJMG5b70Dh85j88j6oXYVreMcF4MBX6FZVFvXCyV77Bui0Eo0GoyybbefrJei1FUAcPAQGjxHNsXfLeytYz+pOHahVyUZyXlerD5h1PJa8DCbfIa7gNRMhvztLt0JKdgW6nizAv3BhPEZLdK41wxe9H+cYFQsOJJhGMbtF7nOP8vTg52APWLHUK+QAHz/5G5yL7EEfVbJuook6i/jyQUlJqn3kgUYSlDm7nWAH50raj9GcBANdzhF7qG5R7tljHGSXXytDapnkbyTNasHYIHMvsuh76nJcgGIsv0oTBFeh+9McQX0GS9yWSzTM8vA1/VHMbaO94XcMM2YQbJ3+v16YSOvNhNV7BovP3P2nl0KEo01VKn/K8hc0/4YhvkH0Ed2TLJ7uleZqvJNE9YmtwqUb7gpD9rvbQ8GPYjB9S4r+NgjMfgC6f
    AUTH_CLIENT_SECRET: AgB8/sns4f0bYyyzd6vvQVS20IFDFTPhx0lXAj/2hcxu+YCHrSceeECKraGhoDVSryMlEBodvH4cqRjqmyBkysXV5zesiu50RphtHCt3O66pd9RgDGNLzVZaOFYEuGpihLtRHBHUdSV7ExTwHqUG0K+q+6sNCREZFWQrrqF4D4WGLxIG7cqKqgDjjX2WjvhFizOuqpPy6AiYP0h7gq9fooMCdVH1UbAZepYUt87uZ/pW2JlrtiE5U3aZkR3fTR+3Ghpy0GQmu4yjyhnaivXDgc/ttu1WCm7ZBBFPTeXhBU2/dWdYT8YhOMqigldPcKW5aWn10oORaY5OGZRnml4lG7aSZY82QogTSNXsmtHYIgQ/Ul68Ax2X3g4+d9Ovm/mITYyWJtJ+2d06geqrL4N52qQT36mTjuT0cn5WbORk1paAob6OGKG8KRawEkcI5rk1t8O+ZoVNE1SS16w/rxXAntR54Em89OsCeEjTmVZtLgoLsyTMe3Hb6kA89NTuGYzR/XQ+zEnsbbr858sXJuFQ8UYFG1oMi4rC5DNEUZuQp0Xi7wJMifTYmmf5Uk6m/ITvAApsh4RHu1nXOlLhDuSRxqPhRMvWdtCbZBeG3H0woH0WwZAnIBVBA6oTFjWaKEa0DvndJ28Rw9scfgCLU25xrUe1G7HWvWJGR9Mtz1LDUFFGLKMgAe+wwY9odf1Els/QYom26PUNQD5H7EqcsTW1k+MNgmI6Qy1O2wtYnMGfpAI7dw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-oidc-credentials
      namespace: netbird
