---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: management
  namespace: netbird
spec:
  encryptedData:
    datastoreEncryptionKey: AgBpWbEIk9MNK8sgn/Yj5ocrV0Jtw1y/HleRb2BUpLqe7CuqyuL+fcbUSpQ7QzWkU1iUgMnKcN+7avUP6+8Rr1rfzhRZSWVvk0cKqoJjax3TmBGTSqY5E+ZdxYlw2QpKLtckkYaq5WJmh70rY6wtYkQwaaKtUOTLmiYO4+m7HBVECQcgZSVEjAEZN3q75RtDP1TfJYH49scXHX91nJfSCJgQGgyuKX+mR3De4iTKBSACyOjv9/X42yLh9TNjqvyDwOMEhQvNL45SSGiB8FwbUQQffCZF0UpMKQxsdJoxfn2cE1mFyxukBxtRZvJ2GKk8AjhQDDsCxVINToprsy19qjhAg/EwpBwr9D+6j1Ui5OA4cOnYOIHKshGAFPcFEUuKmYBPaIROCjD5SNcdrh7kUGegmgBTTHUqQ/QrYCIMjKTZWMgXe4DXLGVp7m70J1rwwUR0a0PPJMy0dsr2RuRqhXGLnKNRHyRJPcP7tRro74WI39Dm/46mtOzo22jU8y/sZCuZHWLmfSUq/OkK21qFrtqJeF2kL7CBvD5PnjHjXG9tf3SK+SQf5VjsdTlT923i9tfmDWfCmVRAAUc0P8N8Yn+t1A0sJUGQ233cuojI2tINEFWJu7OMKee4MUNiwfMzv/3ROCgvz4O5hYzacS9OguTQohx7c1QaJaY6qtv49GouNnny0V0Qhhi3IVUGH1hzlz2aslUjFHYCUqMCvxbBUH15b+/XQ615bQQKAhX+voFMzbzEjQS115tC500Flw==
  template:
    metadata:
      creationTimestamp: null
      name: management
      namespace: netbird
