apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: relay-secret
  namespace: netbird
spec:
  encryptedData:
    NB_AUTH_SECRET: PLACEHOLDER_SEAL_WITH_KUBESEAL
  template:
    metadata:
      name: relay-secret
      namespace: netbird
