apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-oms
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.domain: data
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: platform
  source:
    repoURL: https://github.com/Tim275/talos-homelab
    targetRevision: HEAD
    path: kubernetes/platform/mongodb/mongodb-oms
  destination:
    server: https://kubernetes.default.svc
    namespace: oms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
