apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-gateway-external-config
  namespace: gateway
data:
  redis.conf: |
    maxmemory 64mb
    maxmemory-policy allkeys-lru
    appendonly no
    save ""
