---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: drova-rate-limit
  namespace: drova
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: drova-app
  rateLimit:
    type: Local
    local:
      rules:
        - limit:
            requests: 300
            unit: Minute
          clientSelectors:
            - headers:
                - name: CF-Connecting-IP
                  type: Distinct
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: drova-jaeger-rate-limit
  namespace: drova
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: drova-jaeger
  rateLimit:
    type: Local
    local:
      rules:
        - limit:
            requests: 60
            unit: Minute
          clientSelectors:
            - headers:
                - name: CF-Connecting-IP
                  type: Distinct
