apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - drova.yaml
  - n8n-dev.yaml
  - monitoring.yaml
  - services.yaml
  # - storage.yaml  # minio not deployed yet

labels:
  - pairs:
      security.category: rate-limiting
      managed-by: argocd
