apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: cnpg-n8n-prod-backup
  namespace: n8n-prod
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  bucketName: cnpg-n8n-prod-backup
  storageClassName: rook-ceph-bucket
