---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-postgres-credentials
  namespace: n8n-prod
spec:
  encryptedData:
    password: AgDdzur+va7fvSPNUb+aSNfMPxIhQgA/SHUtYesn4AJgnq5kUV+6lsBhLYWX7vAutMEacyH/esrmP7Ak0NB5qQudteLqGdbOOxkGRiFs6dgpv+Z3ZVoB3leJd7zTp69WyGSui/Ww8u9SMmW2wU1DutkhM/uGfn0Tb4D+pBIMX1SH7rIlCmSDbaAV4ybjUjsNmlEmqyIEcgHCHP/uTnxNPG7e5IHfIDhOjqoYCYtNmOzOp1co9shml+CxnyCThYfNpecwXn37WCOBowzL/tbVlwHqVTB+8ZsVoWM2/u3OgYkRI7GQ9Eozw+RaCcwc6MoxI7ru8fuKNZEQHuDb2/FImoA/mAmx1WOmF+/DL/Ht/FrDu9dS1jn7RED+EtLgMdtKR6UqIDXkKF22Z8kqH3KUQYjSOa04ID9Y7OHhB/N5cuDCeE+XNyynf84Biz6zJ8m2+jE6W5zCBCsdLW2yHcbkju/2MpVS20ENoJGS4nHzu47CgahC/38yQr/8HzkLqMvJdRvYhd4FhYQFGxPS8bnH81n2SpEMI2y/5TidKDBqNZosbbRncmwhVS8pTOsFlSs5E5tiQ/1y5qYMX+Zw6ytgmwqNKqjAnpDIpq8cpARczF8jdPqfedp8bgheEEx+KIIZ49YPoIF37OgBMy2NZnq30O57jy1TnB4krMK3l+AJPeJKFBRGNhVtb9Ivj9m03I65JYjWsvaVYWnPKoPN0mfrqw==
    username: AgDaj2YsxGtAE8rvfPWc6XjrBI5f5D5B621c3GbGSqZwiAGOalBBxu5rdjoVQH+hE2ggXwnCICPY2bRkxudVfXbeGwrpdq6AzmyLtPTLeqPkbUuhWFYu709yoHXK5A64LqmMtIcaDxdYabMtrmeedXP41AGjDWErBSYDyMiVuPr3BD1jbgY3hwHlWG+xp1VHs0RoUtR4MMJVDY7RYCM2pVZK/jNp2Q0Pt7sQ8yw52p5jdkMBS3ar9dWk5pgWOtRRcuJxxf5TmlJa5pvN6LYiPRDACjxFfRSB2leV/4BTED1AaDm+JvSuVJ+rCGbJO+ZXVQVd8z4s4lTnp2qvUo/8pdRwOC3ZfmEtJ+xvOotHekmW7F15lAyutvneVBqg1TX4doKjWZBPirXOxx9F5YnpoA4pyTu/JgFTUhlHBn7hoVLPr7vnyY/7pubBN1EcnTTnhz2M38P8zCuzSA/NU9ouDR+3n6KXjyXCJ17qsOYvATf01jrDtGOnj7DykALeD30+/ssjZYSUDp5hAVcrHaoBwFWyglhw5+hWPbyw8QbR/6WnnZWiVPn9+u8SSGw/WcDclhSLcuZ4ojrqXAU3c7YC8/5jf7YBp8PQMtPYZioiydfYguHXPYfOb0WdhjB6IqRWxVgbDBXh99UOUp6RaUGcSvaPsSGidZgDTtCxdmZXch1S7/8CGlVHybn1BUn7p9BEAc8y7vI=
  template:
    metadata:
      name: n8n-postgres-credentials
      namespace: n8n-prod
    type: kubernetes.io/basic-auth
