---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-postgres-credentials
  namespace: n8n-prod
spec:
  encryptedData:
    password: AgAFkug/V6+k10PdI/ZEXrGdJYWuDo1AWwte+fraLPYPlNa01QaiTB5gb/rw9XnTJPXv9g1PIuiEF9D91FlSWqELnCe6b4GJuM6t5HEGmVPCgRcAr12kUF9Nx5wR+4P7vL9Kk3VgfCErAHaA2XmxnXgrtOll8H35x22QQ5azBXPwLYx+nyRE0LwiXI+hgUZHxMfW71X/djoYRMiMUJY24Sf2noqDhZ6pO8PNKkb73LL90K4cbEhTt+OjHr/h0Uj2MhYjEitByclJ3mYA3eP5CIIxS530CtUkfCfTnBllsXOd1ySe4x8q+2u8NJ6uSVBpb1WI1SJrMIAaWptDPUya3hfkKsCXRocV1goZwcNYqQSAxfd2uehAz7xq0v5okcsDCVzmz3nVLJrN8A/RAcU2jxoUlarpRk6vltnWXmBoKSDOR43MkkJaQmbaMn9TZVGP6rpdIgvRHjJhzDZN9EyGflbBqOJGwCfSpV9s4kzSReU4vXTvgwAhRM6u0ydVxPwQYGF9U2WsLGKHUWtNBQOHcUiTlPmmkgMNy9gbuf4LYDEyFvSwAeX2Lb9T5CigpCDg9l7aAFIzDPh96JGp5cgyEhSYwJIes6G+X/kfDDjGfWk4H5BZMojEBotBwgUiquf7rg/TId6tYkTbIw8/1eSG9V5fkF+U36l4ciwyqaOQX0zgIm2c0fcLs58QcQb2mmp/foCijtV0IbYNzCVwoP4vKQ==
    username: AgByi4jd/8Zl+JQYdPl0TnGhj/OScvulCL+zzjVvGLlRxuLj81n5eRLtEFKpcu4oTBmm9h1S7LhwEMO1ue6GfY+C9Bo3hq3e4yUM9Qej8rbgZ/FBsc0yd8auWfbrYfk1AQdaypRF83G2/2rfbgXaGJMEngcNic2SmFFUSokOLjP3WJy0KfLvnbRwTLQU1XDDsF/e7nY7HP6BfLAnJs1kDjX+9MJ1JQwiiopHMRNMEP+2oDkCzxm4oChTgNQGX9rPsqyQhfBvGDpCDam92CNA9mQlgNU5gTF0QLbL2P1iQsAnwnieBqAToo88WYwLeQZyBYcMIq2Ng3tIk591oBu7ND3eQ9EtwAXqh555uW0dei1vtVU2S52Hdqbq3PCKDd/X02mp/ms2RtFIvQK29wF4dBOWtUDyLzUj91oooQulUloDNywNP2mxvcPiCKUyygT6nMlF6/YvsJaCNSBZHIgpNCa6MpmXnmh0UE4Kr/uwkulhJYzY4LQ6XN0ZymeBWw9uBwt/ewnqmwvnhkH5sWtWCBQQemPHVzZF0XTsG8FQqNbiCZczClMYNEY9dGx7vh91C2j1pp4s12N1LGYB68aMYzRKlloU68kBTMQQGhVCtZNpKgoD/QucHkE07zO1gcXTcqqmz6Os66KeBu1OUpMoxH64oeJ+G16YdGnKy1EgFrDf07WeAn11nCT28eM3HRIZZoV9A/M=
  template:
    metadata:
      name: n8n-postgres-credentials
      namespace: n8n-prod
    type: kubernetes.io/basic-auth
