---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jaeger-elasticsearch-credentials
  namespace: jaeger
spec:
  encryptedData:
    password: AgCXfNUxz8tWI1oO9GPZur+aZrA0YY6PZK5xWxKLaRfCQFy4G9FMMnhykOkfcUUJoR42EjaobokaUcM0bqAZGHgrnR2PwCq1VRVXUVe82pVuwx67ApEld7Nvd7JTHC9Z2wVpR5rEMbRny4Tpxzr6zxf9+fbNtqrzEhFY6NDbdMDu/BM/DJevf15gw6+G3Gx6SqTKuipHpnkvG6viT4J2KCXiSY6Q/GvbEl6kajA+ooS86p6xl+C18wQhaZl1SAYnPgVwVdcxnaQ9Oms3yiPZ1W2dVRkexMJDwtD6zZcHrfxZfNf3c53vQUTus0YhjuPe4PsV/GAp2WibW8QozpDZFmKGmOzJ+5HDFxqlV/jJwY8VCeAs1reOFnR0106zeKzEPPY4GXTKDSvx4e5VGkbz/BPh7eBKuDsZRSpU+2zFsWoks4vIHcePsoICvm3exANoEChcpkmtB4OvcxrjQ4pQiS0Fv2MR2QjB8mOwrcgJ0VuuGnfLiIyoFcC2PZi7bhmBTr56TQnp/jA+IYTZYBFl4Otzr59R4Ov3yxxS1hGZmsXWiEu4PD3wWvNiMR74iTB6GRwqF99ZZze2soXutDfK1S3/S7xL1ccGoq0XwAJv3ChDONhERiMKgQylh431JBXHyS6Uu00zgm/pdiUOAAa5K5+2RXRh5dQGUEKM+nuwNy6dVG688VnFaKLzVDUFbwUbyQ4m7iAbB20iXVXDf8IeBvv4tKIwDLesxpL5CYkclqS6h2rXi0vWvHunLqu4VFvhaVE=
    username: AgCroHwx1X1G7dqSzB0tBbZMokl4LXNw3MGfDh0EEhai2SO+RvZSKh2+AU0DUvTxCKYLp8SB7RobhGBEbEth52GeBvexl4qCN4kpsnbXflHPWmfA8+f2nF4VI/yTtbjGcWESwOlzhiNFpqXH4C1ijeR4ooko31DTQ6IRlJxTqXyihg4ozUzC6M252VXMCuSNwV6TgGG9abacIw/pLaniZlS5K4gLKFEa7kM2j6qiOpTPIwG8Ds4ZqsszN2MDOZS7upXFTBls9XgLiZVoRYIQZy06+hIpPviBNjumTJm/hs0BqIA9kKKTwAOnXUsWQTia0N/PbfnDA0vuJQkqkdPLjZTNkgwVB/LeIWc+awk2qG7nLNQHkIbWQ3sWIQVQ0qQSbCjemNHr7qbpHZssEeTegwGd7ePITtnzPpEP9pC6HInE47G+3CG8UnrEqX/nvAzF845/Z4a5x8Q2LS8bJN6ck98l7udR6JK5qsATYYluUOKF922tFDwb4E9PlUOw9gc32SSTjPV04avh/VbgaOJ/dIYgahMS4PnQEyFA3YeO8e1Lg/hzwmczreUrVVYLcDacfZI38X/rYmg9sN7Uv5622un9ncmvGCJ3Vozm8u2Lj1er9b2ybu3ADuGnLvVOtTJpVEopcL+5QD8FPGxFvfeyeCDK7j3GPTKrSqez7pF1yv2mCvWW2X8XDO86HKb6/yP5nWZGhlRDwkQ=
  template:
    metadata:
      creationTimestamp: null
      name: jaeger-elasticsearch-credentials
      namespace: jaeger
