#
#
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: n8n-main
  labels:
    app: n8n
    component: main
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: n8n
      component: main
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: n8n-worker
  labels:
    app: n8n
    component: worker
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: n8n
      component: worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: n8n-webhook
  labels:
    app: n8n
    component: webhook
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: n8n
      component: webhook
