---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    url: AgCuO6+2tp5AxPbd7dOw28YBLf91ILhuEkUuhUzqFZ2QY9M55lS0g+IEdbdR0c5hupkAtiU2SrtmFsOvcY6IyNt9gcUklnN+NC/hjmSrCk+GJMeMESq5yFh2E7uBIjTRErUu5gp0JvCH5cAXSd1/tvvDDcTJFzoYOvei79SME+Qcj80E6kbLcRc0miaV0aJ/vc/7UEIumXBUa4sHcS/Dzj9KpBP+NRnGqM0Y6zGMfe8BkHV+C5IhG1veaubdqUsAm9fRVMi9s4cjgVSUyov3dF+m2DhftFJ+BT+VuuGfssibXvI2LOX0AYlDLFQsRw7Lysg5mpYtAH1zPG/McdbfnZk/mIctIMB7t0oP02TuX9ZKWrBhhXVJ6Ax/Ln9cceh+854Zpv19uoeo65pxVnB3sjwOIkiomPxWu71F9wWRIzvRB3C8XZCC86z01Wuie1OgXm90cTpwd4c1fsg2em80I6Wp0v8LyjSfGe5TF60sEf8aL49Zlc2Kopcgpa0tMGsyavULOTvsBLwauwg1oITJWJ8GNPvQP8Mt3A67YpuK8bSSQA7xuXOIjuzPbtv5G7hBJEsx7pT0RuSVYpGAwSoVZkso3pQ7UlfTSxtKkLrYzYP/asY9y7DCkqltdA36yDM8Lf5N+A/SorznTcOyfUxyemh8/z7vhjN13uiQIBI70vGiJGOzJr1jeY81va1o4p5VJKXwdxkyJjv0fwAXgaMIWzIEIeYGCwGmEOZ1njWZTlVNtzBNfjV6xjiLbQe2bEFgffo41H4mVn0+ERxRUswKHXrxPk7hVFeO14cTqXbQcoM2Vwg=
  template:
    metadata:
      name: slack-webhook-url
      namespace: monitoring
