---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook-critical
  namespace: monitoring
spec:
  encryptedData:
    url: AgCmqqqHYE7NABNOjVq63phwBhUczcBiBV02E4lKvZ4Y2CgpuKC9Fzv5xbMMMPnJ5yJAaB0b6aLK5McGPfcH4A9gcDD/GC3nK+Da+UHQFQpYOVP4DAaRVV7cT/E/VXtTj2Jc/DvxcKi4nAT+dbkp5/bYcPOisfBC9LrY11UGMJhC3OpV2UM5zTH3ybaQkEQ05yI7sZ/DNM+Zta6WUflB2G+hIw6Q5xL/BcAF1/GicnIN26dGgFo6fzTyNOYzEYFhHp6i88spb40MsvjgI0gZyKWM5GsTlQgBZzj6v9a4stoW8ijBEyomQVOQC7agGAdLj/Xwsp87eINoDIPDIn8yVtKBLJOkvull5o3iS09wFSAC7+RFr/JbN7kcs6ZOTPb0IAhgTjWtDBfh0md0GbsNKI4Pa4vTjreEjZKG1CtLrL4jfsqWe+7lVEQ5rDGVzKC1is2uF2G1tu/AIXQpwSHLjY6KdK4vrHw6taZaswKjKQl0vjUfcfy2ib6ccI5PkMBUwefCdBd4hKkzaGRKNXcvlByA1hbLxOx6PfuwqBice3Fm9HyCRRCyeAv67MLx1ehiZKuKQltaPOsXZgMtMQRs4rECwpMRjsdLXqtxeswCjVGNfBaKwi2aedkTHrTebZQIBe/grJLHE+DMVYf3ic5yZq40azX3dH2uWYKgRW86zID2lNOuMYRvgMkGN4Le1yrbrB87kX43PTpCPp2DCXkTmeq34LlT8g3O97wvk3Chln3p4xE9CydE/IRZGow0ty2NuiaJDAEv6APJGT6qiRnnvEhf2RTA6LhtJ8o/Bh+RSUs4YxY=
  template:
    metadata:
      name: slack-webhook-critical
      namespace: monitoring
