apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma-prod
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    apps.environment: prod
spec:
  project: apps
  source:
    repoURL: https://github.com/Tim275/talos-homelab
    targetRevision: HEAD
    path: kubernetes/apps/overlays/prod/uptime-kuma
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
