apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uptime-kuma

resources:
  - ../../../base/uptime-kuma/environments/production

labels:
  - pairs:
      app.kubernetes.io/environment: prod
      app.kubernetes.io/managed-by: argocd
      team: timour
      criticality: medium
