apiVersion: v1
kind: Namespace
metadata:
  name: cloudbeaver
  labels:
    app.kubernetes.io/name: cloudbeaver
    platform.tier: tools
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Namespace first
