---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudbeaver-credentials
  namespace: cloudbeaver
spec:
  encryptedData:
    password: AgB0cUcrxwmIQssGvsD4KuDG/7fw9Vo081jrgnIACNnAUYCXaBtsHwrEs6GP/JHmH+QLpDDEm4QIHAG+MykbCHxNZKUbnEE/PiK8m7XEYZp64JN9S+zLyCINxRMjgpUkoGJQecPPiFUPBY1kDOxJ6YY+HdUf5DhDyH4tEOrYvmP4xsNibTSnuS+gAD41O0BWBdOslK60JQNKeoLm0+8ZsTgoskDUft8I2Wioo3TjtQ//c/sg9D0EoGoB0UgBU6Qyj2eP/IZwvKkzzDU4C/Ie9P7PR7Mjc+cXjK2W6GbPXg7GlHne6LSthodG+6V+68jZ58w6H1mDuswhA8TY0Sx2KygFvSq2F0DEaHlMCLr1QXFwQ+X6/pQgbtGjjGaEDZtcNoFlYzn8CZUEVW9qs2LPUiHV5BXNoKHZWr9xsamWRCmhtJvn0RPReXDHlf1OI5qnMzM/g6nkFCFb8eqAAYNo3bjXRK79xeOlwe3FXrpOC2EusRM85PxU8lCWvTJPuygFq67R1U2PO1LcqP6r7Bv2n6i5Hm3o6mGLif5oEXzVpZTFRHAeS8Y4MdqnDgfdGK3nRJF8I0XuvGQbo1euuTNnP49IZ9rS+DsKwnSnLQrcpakqYcPmn3ufnBeJQNQNp+dpzuo1FJ6XHRrV01v+6HWt803S46DY2qhuKAbIaj1DRUnA8AXGwIMdPfyOEOQyzfmI/DJShT3ZhBN6x3lJ927vg2khQ+Sn
  template:
    metadata:
      name: cloudbeaver-credentials
      namespace: cloudbeaver
