---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudbeaver-credentials
  namespace: cloudbeaver
spec:
  encryptedData:
    password: AgCYuMRQkZtuwxT0Gm67ynlRXLo9ZpWTPJB36q2UQC3zqls0DzTXhkA0C5YqWYVuGt2nDDRmHSddXVyV3+i9aV7rmw8Hypd+53/blsdXh11I9Tg+VURRkv0sxfCZ97w66A1ywwyEfhkTLVY8I8UqVerrYDJLhRD1ui2kxMfeCkGZeNajgh6yJVkIDbB+pGWgzxhNkYBlfDS1DiSj6clLmji+77nUr/TcJH0YuWtpp5lWr03/k3NCzQfMjvhWxSkkTwvO9uQRtqwDa4jlVE0mtD23mjNaRZR+8iNHQlNUQWxnBCEdS0BeTXb7svtWHC/VCiesLSy1u1IRNRCSxwrkOBwbGOGucTfJs9+g/BubZbVbblotMC63zHx+ravsbedL0DI6dBbHt6i0smB48BWo6l1NtBM6sfVGcS6G/lKeD+fRqBoDFjLiPjqBOrN8Ue2kHSzYWPjsT7ZM3hUWehgkL5BJLglVpcoLL7v4Nw5kcGrq+guBPpmt6nK01XvbACjB3WSXl37K+m3UYpjG982tjW29uaCfcNr5kWL/aFX5s5X+Ng75E9Omk4t/zPsTt3T8uJkINm2byvdsVFIewwkWE/qGXQZYS1eZSXmSozm9NiIFRw0v0NhI7Aiy0WvUoXHoQ13swQqIfB5gjzCwRy071z9HMSt1BSUc5WW/9Swynj82R5NFMpP6IlKsptGUylIb4M/SGzRRltok5fTUVvmUKTuilNYZ
  template:
    metadata:
      name: cloudbeaver-credentials
      namespace: cloudbeaver
