apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-bucket-init-rook-reader
  namespace: rook-ceph
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["rook-ceph-object-user-homelab-objectstore-velero"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-bucket-init-rook-reader
  namespace: rook-ceph
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: velero-bucket-init-rook-reader
subjects:
  - kind: ServiceAccount
    name: velero-bucket-init
    namespace: velero
