apiVersion: v1
kind: ResourceQuota
metadata:
  name: drova-quota
  namespace: drova
spec:
  hard:
    requests.cpu: "24"
    requests.memory: 48Gi
    limits.cpu: "48"
    limits.memory: 80Gi
    persistentvolumeclaims: "30"
    services.loadbalancers: "0"
