---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jaeger-basic-auth
  namespace: jaeger
spec:
  encryptedData:
    .htpasswd: AgArszLrJSpfStgrebBMu1NaO0/DxonAxRKc74NvoZ5VZ0udzV0Asgp2NAF7FLG47l8obBWXEu67HsXWMMbC/ecgvrMAarv27PnF40yzlBOPDOtUjmar8YeeYFNRl3rtwc9egKAourSAajc7j50Ci20/ALxMTkmkdV9XXDWqxwdPyS4z8CI5Uv/7AD/xRPAE9tbgn1qp2gAvqYKDBz3Yke53g61GOlRS0Zh3+rfgWDQdDK5JeKl313E3fKd37SgKyEmnx1aCjMcNB8jLoE9jPnCTBeWw4wZaZQBY5bRp7XGghFE9zn4H2zgCh3H9i0eFYmlBKxFGJoSyeFcyvPwaDBxBjXlOqETpcok7LpKGof686x3+aUoQR6WxkcquQYx/yuoqaEgefN+SeeIUB2GmbyiHcbaqv2n+1B59kN5pMLQZx/lGhj5G3b2dhlKPB1/e+BHFI1eGTVzAHEtsX6KVnpKTka7isjdf9y3LLssUQt5gX+gnBYE4Jkj7Ue7p22G3VjyjOcH3OwePlFq/tJ4YiTqPO32eSAbvYMG9MdZebOzIA8j+dAU+irKTcqFUjsDGOcDUoLbJWBeAZjlu/p6LH3d/xSBOpC8B8g9QwO4NclM+QFlioCmX0DEi8vzt0/g0P3g/Ow5ZJyrIhYQjTwcIFo3JVi0bCA25K8OxtkPrqjTIwE9wQinbf8rpIIB8uB+ObME1zSga7Bs7Ios3Vm8szqx77mf9CRllKxIj0aUXdtBgYSadR53FeKb3
  template:
    metadata:
      creationTimestamp: null
      name: jaeger-basic-auth
      namespace: jaeger
