---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jaeger-basic-auth
  namespace: jaeger
spec:
  encryptedData:
    .htpasswd: AgAz9XypfEL8wL6APsdB+dGa829utDWIpmH2r7uG8zUgvjOBymTz9nHoidYRupJZbpBBVWlj67AYkw+Byv/8BT/zj1LR7KOAGCT+00cmWbQ6Sp2dIy07F1AP8V6tv13pWqDqMAuXzEq0YZ9k62IxQ/fxs+9Crc5wP9EPvLHBPhoJw3zn1Rhj6O3QcEIiEparM8mA+DZXBVVCGumhc8H1QpFGYV8tY9bVmIEgaETl/1kf0yosR5jMf57cRIV95+yQfFlk00U+1yGNeuSD1BL1ypUYCoEjkHP+7Kq8iXIUD7DOAabZkZdhsd6xLJ6OM8BA2niTnVrTQh3poDT8XH+OZMw8in1KCvF93iISKRNkU3AYMeadJG8Cfu37e0dz0d++ewulLGM9A6jyn6fb/vmSRAuxbMQd7Ycw1rq/Ecaf3PfaztfWQm5ATDkL4D65qTaDcfcPgqz9X2Ucmtzw5Mb0RCKteUP1UW6U1sZ5tQGhcU3g1WJhAahDoDi6eC0eOLLWlH2Js1KDn2DPfakqaLNmEkSIUP78JT5HHCOxN2O+1OrhdLpCSJc0/803hesVMDnwYpQZAWdXzDkLvskCgSjoKVfhyZcXslOJ5XLTr0nC6LuaTuqjWVeiAvAnMSCiantMOuAh/RsFy4K57NmFe95x+kunwxOOmdnu4tjonVVDnzc9gFOpa4rzr2d5LDqpVpTAuMMXhOp4XLZWCp/do/V3FhSuNEGAUIY10GMQTVlLNtlqWeD+j4HEBD5D
  template:
    metadata:
      creationTimestamp: null
      name: jaeger-basic-auth
      namespace: jaeger
