apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: trip-service
  namespace: drova
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-service
  template:
    metadata:
      labels:
        app: trip-service
    spec:
      initContainers:
        - name: migrate
          image: ghcr.io/tim275/drova/trip-service:latest
          command: ["/app/trip-service", "migrate"]
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: drova-pg-trips-creds
                  key: DB_URL
            - name: MIGRATIONS_PATH
              value: "migrations"
      containers:
        - name: trip-service
          image: ghcr.io/tim275/drova/trip-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9093
              name: grpc
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: GRPC_ADDR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TRIP_GRPC_ADDR
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BROKERS
            - name: OTEL_COLLECTOR_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: OTEL_COLLECTOR_ENDPOINT
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENVIRONMENT
            - name: MIGRATIONS_PATH
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MIGRATIONS_PATH
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: drova-pg-trips-creds
                  key: DB_URL
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: drova-app-secrets
                  key: MAPBOX_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
  namespace: drova
spec:
  selector:
    app: trip-service
  ports:
    - name: grpc
      port: 9093
      targetPort: 9093
