apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
  namespace: mail
  labels:
    app: postfix-relay
spec:
  selector:
    app: postfix-relay
  ports:
    - name: submission
      port: 587
      targetPort: 587
  # Apps nutzen: smtp-relay.mail.svc.cluster.local:587
