# Istio Control Plane managed by Sail Operator
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespace: istio-system
  version: v1.30.0
  profile: ambient

  updateStrategy:
    type: InPlace

  values:
    global:
      meshID: mesh1
      network: network1

    pilot:
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi
      replicaCount: 1
      autoscaleEnabled: false

    meshConfig:
      extensionProviders:
        - name: opentelemetry
          opentelemetry:
            service: otel-collector-collector.opentelemetry.svc.cluster.local
            port: 4317
