---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pve-exporter-token
  namespace: monitoring
spec:
  encryptedData:
    token_value: AgBnFp3D999RZZq9mbbMuI2/nCxQDdYBzAWX9fC9izwRavC6OIPKK6P1HLyQ2LTaEx0dt05dQNxrgmudmWfnJiXwgFVyRYqpd0NL04kl9iOgpNSYaBy6jQWte8HtOdy8A6EVvtYb3fEPK1ImbTKhjvoebdDZ9lQwA5iEfMUaSa2LCoccSfuRZqGlQfZ4pHXdPWbYcQP3tCtfjESSqMG1mO73qzD9aTqFyeucjRRvg7vD9/tji8LGQWZATfCMjQvE9LIwiU87IrzZ3RhT7ZL3QB4Mj2D9LxphDZ2ZkhAEKuGEI8WjJZ2PCSkDChA3wmDLKA6uCMf8BtOpx/pKZCZ8spSEXODZi4hVmo5dLFNPUv9Fw0bvWJFiHtrTxJaYXpF51hZ3PPY+bBjUm7rd/cyAhTOECipW5YI2Ymp+MHwPQNDTV/6kTQhjazBhL4LCkdQiKikL7KwF+pr9qjcwR0U+V+q7XgJ6OHf1kzN1nWhQSYWLxPKe5EisTJsbCvoTuO/jGpmIElVxbBUmyf6Itla6e2mLqlt8vUi8unegEfjuXjCWPaHMCS8mQvudG+jjMy+cML19tJm7NcQ8NhsL/QJJv95vRry+197cjSZJPLH3e0xGiyuJKzzWJ1wgsfNLejrVJ8NbLnK4juuOtR4iP0ibxfZgTkO5jpKgF8b2fe7WKFbeQUMAZIapLEjmeKMy0OG+PhSQmtnej9hcHPR2+gn0zG1xeevfRun+T5ToVPxoQLkDBd9qEFM=
  template:
    metadata:
      creationTimestamp: null
      name: pve-exporter-token
      namespace: monitoring
