# SealedSecret: Elasticsearch password for OTel Collector
# Same pattern as Jaeger - uses the same ES cluster
# This replaces the problematic es-secret-sync Job
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: otel-collector-secrets
  namespace: opentelemetry
spec:
  encryptedData:
    ES_PASSWORD: AgBAR73uh3++/8ev1SFzUuYHhC6KPj5mbhoULNZsMpIn/+ASs5UZf8oMvav9PWwQCgU9KaVyzbWwcp38TKQU2ML5EfZGu1ug7QWYyfV+6K58dO6RbkcfPR973LqQvhYUj6AuN5PSkFL4TQxvkbCBrjN/Ya5wKFdXJ7DoD7AiKtTG8KCa1tYwBPgnFuRLUOKUJUcMMJL5uykpk2BBrqqYqzJ5WY3n8eO/CX6y2VD6WXUzQ3ouKMhOONJfz16tnCaYqRfnviP/H0hu0yhPXeP4qsmiBpHBmoOB/KcODZFxO5dLBdnl+MP6fkl49oI5PwScil+R8B1uXk0/+jalHvB0FBqA1kNR3B2LCioGIlhy/twD0442+6x08vt3iO1OpyoLEIasl0Lw/e5R8kT2JWT5zPA/FX1nrWU/qksYfixuuopkMYf+hk/u3/It/4/7weoQwxX3mPHkhMZUENzAN7jmelyGbHEmros/CwuzxlgqhC8DHyf9lVutarcHPUBtUL0rlao/SW+EZGfPGIAW7h+DUw+FMJtNS7WWyfZ3nSyJqMQXjouNvhy/h8rqRYSl+CHn8uekobi+gTDWmjT5Pbh4pKr0t248xml5GGSYSbrmR5rFvytpkkhrwo/SjZ20rVk0zprVyCLySbDyru8GQ7JA0wofcsmuhjg1/IhuzQCux23HW1CO+B/Cce9D6dlQ+7zi7oHj7prAHh/S5teQDfEzNJyQkdwlwYN73rA=
  template:
    metadata:
      creationTimestamp: null
      name: otel-collector-secrets
      namespace: opentelemetry
