---

#
# AccessKey: L46TPBNU9JGUD811DPHU
#
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAQ73EsYkJVeZn4aDJeBQV45zi9P8ELPrWd6KG3Y9IqkzXNYFjgYYzHbRFfsAdllBhf5YCG0SAyHJZagleK6i+WtlxltoxjcrClfW+eRLOBmjn3E6++CaSiqDuUTVn33DGejqsVVKtzwmgx9nJL1YmI2ynpG4vmjCZPX1Uaz0IQX3OXmIyynZEMb7+dg/ull9xsRw97XB++1aGLYf4kS9KKcgn4mClgxJE3AIgm7sJWneNNXTgbr+3Jjz7oiFAmZ9GR5M7UbqwckF8LIujmVMWdBWlgBKalcUx9+tY+FDrqnJ87LP86dwdGlM2eGr8ysVmH93sDsSw+mDh8c99isrDMAiPmD5F/POfPxN4OPnxBU27D/EcotxnEfWLdAcehjG4Ty/2qjG5wqCLnqmpC+31kCoBJcb/c6GpgjYcDSCnlXvTI9GUsccN0sQrLMmHqw0SztiNY/uukciK02IA4/ylVtpaklqxCVJ4WwEVxboHiRYF7GOxUk1IMgnyP75sOLHjK+uBd9wV90x/sIJqFbtPcdjulGyOAeeecl5eQlbLzXDV9THrc00yd0mHlmSPmW9KVmPmIIEgDlb/U5OHWVHMZdkT2TQuB45mYUTjBQv9Pf5GkmE+w9OZzwogTp9k0X3vfb/a6wmUR/Nn747Wctk7KTlGZR0mPMf6w0oD0LIZ4Soflr4ZP8lcibcQf8YT9VoYiT5ioAjNVRzYyY+tMe8sUNFBAmjE965eexE5PNe7nmlbucPWW77VB3oTMZBoGQPIdBLK24hJWOmuF0bBENFDhurNIpyduznE9KqaYYtSlSM+LFl/0cDeGwR2hZhQS6DxdIlxgT/bI0ULNPtIR6Txn
  template:
    metadata:
      name: velero-s3-credentials
      namespace: velero
