apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-cluster
  namespace: velero
spec:
  schedule: "0 3 * * *"
  template:
    ttl: 720h0m0s
    storageLocation: cluster-backups
    includedNamespaces:
      - "*"
