apiVersion: v1
kind: ResourceQuota
metadata:
  name: drova-quota
  namespace: drova
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    persistentvolumeclaims: "30"
    services.loadbalancers: "0"
