apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: argocd
  infrastructure.domain: storage

resources:
  - namespace.yaml
  - rook-ceph/application.yaml
  - radosgateway/application.yaml
  - csi-drivers/application.yaml
  - velero/application.yaml
  - velero-ui/application.yaml
