apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drova-kafka
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.domain: messaging
    platform.homelab/tenant: drova
spec:
  project: platform
  source:
    repoURL: https://github.com/Tim275/talos-homelab
    targetRevision: HEAD
    path: kubernetes/platform/messaging/drova-kafka/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: drova
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
