---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: require-mtls
  namespace: n8n-prod
spec:
  endpointSelector:
    matchLabels:
      app: n8n
  ingress:
    - fromEndpoints:
        - {}
      authentication:
        mode: "required"
    - fromEntities:
        - world
        - host
        - remote-node
        - health
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: require-mtls
  namespace: n8n-dev
spec:
  endpointSelector:
    matchLabels:
      app: n8n
  ingress:
    - fromEndpoints:
        - {}
      authentication:
        mode: "required"
    - fromEntities:
        - world
        - host
        - remote-node
        - health
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: require-mtls
  namespace: keycloak
spec:
  endpointSelector:
    matchLabels:
      app: keycloak
  ingress:
    - fromEndpoints:
        - {}
      authentication:
        mode: "required"
    - fromEntities:
        - world
        - host
        - remote-node
        - health
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: require-mtls
  namespace: lldap
spec:
  endpointSelector:
    matchLabels:
      app: lldap
  ingress:
    - fromEndpoints:
        - {}
      authentication:
        mode: "required"
    - fromEntities:
        - world
        - host
        - remote-node
        - health
