---
# Require mTLS (SPIFFE workload identity) for n8n-prod pod-to-pod traffic
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: require-mtls
  namespace: n8n-prod
spec:
  endpointSelector: {}
  ingress:
    - authentication:
        mode: required
      fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": n8n-prod
---
# Require mTLS for keycloak pod-to-pod traffic
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: require-mtls
  namespace: keycloak
spec:
  endpointSelector: {}
  ingress:
    - authentication:
        mode: required
      fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": keycloak
