
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgAU44K0KILUFA3lN+1nuhvCTSJ9L9GJZsvkdMauPTjCYBFY1Itw03ggi+a7RuD1JdwzYvXqGJNuDiIvzomahOekUGn41JG/SbPm4fmoxE5v9SUqDlia8wxqGS2+OZVDXBUH9XNE4jdpFDuBha98Al5e7+PggxxqpjnvjXj0fZAOa9KH/lfSt1nlb7LT8l2THKhBSB2WBTDYg7UW2srF+vhH80U9L9ai1zqkU7wsigPr8U8zbIiHEodQvgRKqMBuhL3a4SVU04+v2wS03vlF6A0iWvQJaB1M6oTTH+V7YrHjCBdLpJeLOHT5Hjf6BDcRfdkMd66z9iq6gh2AVz0akiJ3MNvQM+ycFtNsd3azVZGT/YbsVJ3e2x22+R5YHuK/iwDlj2/EhO21nxtUJMtuQaH+yHMKfF29KQG7jZdqIYzKQCvj4MHDILSHCj/+xPu1cSIbhVXN8nh2GZyVqQdi+LosEnXfvYFXJcet8GivdSj+drdl9a7tnGqgd01aOrMvQ/Nhem0t1eiVessIZgwKzAMVc23lfvN7J7v5NLUbF5L5rslS7p/r0U3tNPk1dfiDcwcBskyRwn7LvPP97yuCXV9m5FnZyGEQnbrcFA/F1VHwxKcrzJS/TZqiBVk9oohxyFe/BSzZzJhqp1vFUOi612TMFu11urrQ0h1Du8nRv59EQHmK8BZMCKOc4IaOcPui6kZZlvXwc4ZvIremkHrykRNOGtE1ayR+JGJHT+RMcE42XqDnYkr4BwZrRXo2jcA950uUXaO+1BSSQvqsF5Q4GfQn55iQMsKSO+h9NsvMqbmbvYhhPuAdJs2sSlKvDzjGB49pOW4O8F4ZWz6Dj6VrqSvEgQQCJ8/hcCODlTP/c7890fXu7D19aClXeH0GXhjFv/PByrvXo7QQsORr7H551meIs0ZvXCcUatPa/Z36vddEtkjK5MJq4NJ5XhGlsriU
  template:
    metadata:
      creationTimestamp: null
      name: proxmox-csi-plugin
      namespace: csi-proxmox
