---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secrets
  namespace: n8n-prod
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: secrets
spec:
  encryptedData:
    DB_POSTGRESDB_PASSWORD: AgDASqI5nys+ACaM4JOGf2LXD+GXWpHzKebHUsIB5uurGAh68gz3zwvX0oz6E1Se1QfhOq4D0HYhT/C2/fABSIs5vsXtKOWrguAEJl7KiiNCz/60laiBjYdFwMPH6HrXRpr3zdi4nzIvZH9pBA8JTY+WeYGXn4a8s6JxUMzo6xN+P3YnUQa8mQGTxtVYy1tEfzo23Q1GodnwDz+4jHUwwiZa6v2rrzvgqqhtWp3drucniQXXIEbpXmQ5Ls77Pi7xzOLhoK3xZ4bWcgLpS/8uASSILWk+AeAtM1d0RndGH6i4KwtfC5Fh2BGC6hff+vE58RCAomUPTBqM3GkEfkR1/z1r+VQ4MDc5amRB4vCUf99kq3yq352yQT4omFv6FkEDrjyX2cHIVbAjVU2+Ac1L3tPxjpV6SzyGMdz2PdQZS5Q5oDJdpElOUSMFAMbTASUZqeROdacG++zEU5jeTuDFHPH11Pz0tduxf3UJf20ZHKk8rIGvEkv1XuPuEpAEWRdoKrQKpfs14TLkBaosQGqB27uS57VM3QcwIcnUhXIU31TQNMg4DFt0H1X8b3uDlr5DGTvcflcLnYGn/BVNx6uhHH8XGyVCdNUzklbCPkUae41NHyRABk7mCm+TdQl5fx6wFJpt75LwrMf6R/lv6FqFvsU91ngbu5wGDMd/4wKPNgi75p14HsA75wPr9AyV+IQQa5NqtziPRDz5XLZmmhiu5A==
    N8N_ENCRYPTION_KEY: AgAu9v7OIy4SUnhEPcHF3BUBV0mDb9zyIVqb8tFIDY3FJILXTmfQVSeiz77wscMP1MVHTg+yDpMIzkPfF++vwsr9CEGK5s4RKDJldlN4f4T2P+c4fvahFbzi9az88T09vaLg6Ss3Kp0/lpcalzmv32PNqrs5q3T7+8Do2Jsv1hJVD0mmUt2TPbWIjikTCOkfqYrixIqdFUkhVIYSlfqlocQzQC1x10IurCriaUkIawHnfH96VMqhHb/kHVagy008CUpf9lhn3oLfB8SipIzRwjnPP6rMIpWTvWUHJPeIn04NsOYJxcsNYE6xvv1nKNp66BN6Dkg8LNS1MQ90gjnmcBedmmTkrYsfgfSoz7Y4DwJN7KgWAgtk76SmyFoPM/zG198lH78ob+CeJ0P+4nRvH2mSZMcfjiKE6T2XcMa8ZT8fsaDCtoYNvHvDHGYKiJKFCn9o3/LInSlf58oIvpDlQ+9yJmReWHTZLbuIOA46KR/7xI/SRxzTJVKVe5SX2mibT+YlI6b+o1BNTR+hD257eyy2HK7r90bNymI8mOHEaOTHBhYEqG2vu2HBrlCfsKqmhpIBmNitEByLW+n0U148REvHcVblAW5jVdfwzYvogCp6W+HHW5ZZmocMtB8ggbStsVN/8jsXJ1U9BxOEX4SPGX4zfIAARSTsRTY++EMrKdeYTTBgqRHWawmVm3JXEdw2gYyaVXJ8G51CAVCH8Nrxf483p0bOSIr3wo+Yae9tjvcLgw==
    QUEUE_BULL_REDIS_PASSWORD: AgCuRj5n0ujDwvEvVRlTRea8Il0/Jm2WcCTtvM3Upq8WZCCn4XiQiDkQdfiAhq5p8DyUpeLyGwyaRbbTriQH0gjm2rKT788WKul1MfFgQZ7s0JDtjpnm/2k5hPfXXZlW7gcNy8AdvGUDgI/KDBq7ys8w5SUTXf6R2hdWTsuLtu15XI+12iRTENexvhXEZ3jh8BcEYfmdQt+Cye/dGV1Nt57688k/L11qLFAKpI73GtCxq7Ik+CgwOHoUh6GZTw05jkAxFV/oSnv64p4mmyIgO5ArtjqVEW0oS8kJZwB1hK1D4/1lKM/6qzY4BIjt9b52BQSz32uecN14By+NuAsbvF6K7cJY0Ij0BVJIADSkeWhnAflJ5R2+u1lhuv9icYQSNzpV1FV3UtCGsG91G0ubCNabOrEsTHJdr6msxX/jEYFcH/LmFdiGi6CpFb2spReHm4piT6Qsssdbs0KDz2SIGWba7k45e54SxKgkK2Dyelvhbcihbq7tk64/WUzdHD0NSLN1kLVjNdt5LG7y8kIO2E0v7Ct0TUVjg3c7oJcUDNnBLGjeYisDNjfzeZpzpTEe8xLEuqrVTOB/WPTmxpSch5rVsrHi96taoMt1nXKvXqAeuVVVJqVmD7GYVBp19O1b45ZZ9ki0kcA4tCUUG5jh8tzHofeXgdDMZIxmM8cU9YpjCocvYBtaFC47UKgjeS5ZL4Oq1AoyEdsA4+pFPiuC
  template:
    metadata:
      name: n8n-secrets
      namespace: n8n-prod
      labels:
        app.kubernetes.io/name: n8n
        app.kubernetes.io/component: secrets
    type: Opaque
