---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgCREx0LFZclM1h84OOO94IzxIxe/ilDTHnmw+0SUI1mJlG+edWS7JscEtdQX4ZgolZ6Ig2DqG+Pdb+NM+BX4TvvKYan3D3djp4uAU36pjg5599ftSOWruqR61n+RlShCWbcysONh23Ls9EH2hSqyCC6coPClBpa1AGiYa+2d4FPfeB4nQCHq50CeBCTDc/CTMJpsNg1bkE8Fy53Y7PyBsZWaLdLqk0XWbLhSKSE2lwlx/0cJpeT8eacYpN//CsfeMUWqOZSUpC7PUA1C2PvTQ0o+5CzeEy3ZX2pAy34yrkv7YZYUI/v3Zit8tOzT3/Y20x7ECpRvp8CBTsa5T65d6k7Tkpld/fh7vD+l8uWxMNsK0Ig3JyvlP+4rZPfURtysDgQVbLmr0vbfGQoIee23j10aAyIMTKOaIvYjn4bIu6a8SjmUspwVEWUzEprCFU0ERI/4U185icvwDnUvWHdYN1wBsOHCJ3SliiVn+HYTpRPwAeZ2NqmTI2aw1YCbuRnj0aHsUyGzl3CXAhan/06vlCY/fUArIYaOX1dyuFtnma6erXeCTj0S3tm+xGnCg/NuYYxHlxk0576DyTw2d6bSZi8z1xUabs40JNZMsOEIjOCj5yiDs0m9AyOfxO4Hc0Cr8d/ZDyu0CEbBrBqxPf7p3OZjEhjaFAZCKNnAdAvBR6Y3Yj+wAisKer6uvJifbshAfP+fwciLLXXUgegS6YPcCArPiVWR3Jl9o4=
  template:
    metadata:
      creationTimestamp: null
      name: argocd-oidc-secret
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
