apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n-prod

resources:
  - redis-config.yaml
  - redis-operator.yaml
  - redis-servicemonitor.yaml
  # - service-headless.yaml  # Removed, operator creates
  # - service.yaml           # Removed, operator creates

commonLabels:
  app.kubernetes.io/name: redis-n8n
  app.kubernetes.io/component: message-queue
  app.kubernetes.io/part-of: platform-data
  app.kubernetes.io/managed-by: redis-operator
  team: timour

commonAnnotations:
  argocd.argoproj.io/sync-wave: "15"
