#
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: coredns
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kube-dns
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
