apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-dns
  namespace: monitoring
  labels:
    app: external-dns
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - external-dns
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
      scrapeTimeout: 30s
