apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-server
  namespace: monitoring
  annotations:
    argocd.argoproj.io/tracking-id: kube-prometheus-stack:monitoring.coreos.com/ServiceMonitor:monitoring/metrics-server
  labels:
    argocd.argoproj.io/instance: kube-prometheus-stack
    app: metrics-server
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: metrics-server
  endpoints:
    - port: https
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
