apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vector-agent
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: vector
spec:
  namespaceSelector:
    matchNames:
      - elastic-system
  selector:
    matchLabels:
      app.kubernetes.io/name: vector
      app.kubernetes.io/component: agent
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vector-aggregator
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: vector
spec:
  namespaceSelector:
    matchNames:
      - elastic-system
  selector:
    matchLabels:
      app.kubernetes.io/name: vector-aggregator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
