apiVersion: v1
kind: Namespace
metadata:
  name: renovate-operator
  labels:
    app.kubernetes.io/name: renovate-operator
    app.kubernetes.io/component: operator
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
