---

# Bucket: n8n-prod-backups
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: n8n-prod-backups
  namespace: rook-ceph
spec:
  store: homelab-objectstore
  displayName: "N8N Production Backups"
  capabilities:
    user: "*"
    bucket: "*"
