---

# Bucket: velero-pv-backups
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: velero-pv-backups
  namespace: rook-ceph
spec:
  store: homelab-objectstore
  displayName: "Velero PV Backups"
  capabilities:
    user: "*"
    bucket: "*"
