
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCPRzUdNjkXgLkbEd/ZPijd5oa7LyGTj/2EGjPEZhUriXuiLXhfQz+6NorimnYlflpuIzmD62VOCctagBWnwr6X0Stlj0KuIv18k/XSZqvfGA+9GxGEXEDRpyT612O3lDYiXLXhPHe2fK+KLmHVGL689CiOq7JVPnF7pacNAOT0QUuEtxe27EQ8x5l5sXfU0U5AmcLTg9//oF6KU2F4QHcJkGJiqQFZCH1GFXxXg7T/u8/wewnVAm6A+JPtpL36G9lQcgWPz2k8jVmhzZe333u+51EBWG6UkTNoV7d6CcZEFKGcpfK/8pNW0adiZ7btbLGLoJAyr7NaZfEFxF+nU2ShejTHVfAI9CPpKYYZItW9AnNkc3kRUG9GPER1abXQm90cyLQyx4BCssIGWr+Sv5O+famvPk7wL55PLSKGIvDhRYkXGQUpNe3SOj4kFYzqYQ4FdJ9HNecIF0/8NPU/O7J5w/1W3jtRtLH5dZSchEdZJic6nITVjgq2lYC9AjOJI6EpzhIQclRlrEY+PxN/44FX0OzaQhwpHwArjW/AdJy51nvDEbLscyWczDulj/y7Ls8Gw1lXP+7EOYQcAL0eRWkBP/yqbMVClLMo9bZ2lCz1vFq/d55YYzUQPlzRYqdyoYQ8StsraDrAYZh7hyCE0yEiSYvKFk7VthG+r/TAV4OeiSXuplE1XU5DoSy89613a0CZxWdNfQ8FqQ/RA33+tsYf29CC3gPALJIQ5dStxtj/W6/SWrpRE9q+
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
