apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pve-exporter
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: timour-homelab
    app.kubernetes.io/layer: infrastructure
    app.kubernetes.io/domain: observability
    infrastructure.domain: monitoring
    team: timour
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/Tim275/talos-homelab
    targetRevision: HEAD
    path: kubernetes/infrastructure/observability/metrics/pve-exporter/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - ServerSideDiff=false
