---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgBOl1MJWLgrcOjG8D6MJlvC5VmjM9RzDgJu0436L3Kx57P4nl+a1e6x3XeXfs3Qsl3Lo98pBv1WFYRIDCtyll76i0ovy8Lq9qE5C+mnmlm3ysY4cnpjvQuERAtu+W1U6QaYysuJmNy2ZpKd0IXrgC6VAroyFb+8qUW5dy8uLrj+KaFx+/0ftj+lDRuS6Ire8CdW2AqPxrimQAn34zhWuHcIr5tkgqdNYR5UAiH5SoZCidRxc/K1O7MectZlK6/6zNGG8m0Rig4LD6RIDYLt4Mwv1EZOrV7yG+w5nOM5H2z56VZVqPxC/gvQCDVffK6KMlJdcjPwQl0IdGVF7PVep1j4GyT4A+V8uozeXnWNfsl0tN1RuCB0jinnGDjcfT3PHMGG6xcWzw4C4OawL7NM6ndfrbySNYkDRdfDGV5wZWBW7YSXCphWIMhW7iHiKrXGt7VzztY2F/TNLg6R8tT6G1X3AW/soY1N7bN/Q4DPSHHiinwu+hIRxCEkUjMrUkh0FoPz5a8hHHHCsmYCpPeSr15zIeTtmQOFIvQ9IiTzahelsMo7FuyuYrQrUnTcLaW0wm4rybf5j3g8T8O4LBHXYlNZ2ofo5MHjWWgXE5tkweOUJVdEuvtK1rApguA0ZF5cxlhWcNggCrms0lhZHELF8gOABoRhaLvw4VetdX+3859ssnaTHyPhBIl0lRJadzxDvHRhyq3VUP3iLgIogElk95cuf8SP
    username: AgAvLt5mxladyrY7+PFWYIMDhBfdXufI++S1dhiGKiK5BPxSUfmz62iFG7Zzpy1klTenAebb5vQ62KbEMX90HBXfvkMrjWD0tIH15hsCKM8tq75tGxyPh2Y3kTL79Qt3V2Vu3Jx7LpWgf5ZqXzDrtBW3vLimFJs2p9CYQkN2Bj/lTKCRYJUeAb20KD/bnT+g7zucPBiYApIs4RjeMRDIyt+b8fJ+dpNRZ26yVoi8YHqH3/GBMPIMG1XlzNRJYiUrO2UXLsC6l9ERCMQoCEV99VGags5T4CczH6gr6dcydF7JOqXB5OrSirjCqJT/+nad2M3v5yXD3bmz5LdzmTvu8kHxbcaavex2LSBPkbBx+aX0CP6pKZY77Tl9UUbHDCa10T+hQwbQwnbEmHzdaaZ0ELYerFX14QBJnmLzFw868bFcf7h8U6L5ysiI6Z/NLBW4NDpUNC1ELOOycC3Xf58cE+C/gboDj6N6zke8RsmHl8kglfJe9+r70L/qe79XrnFSuz8O6ilEaBSixII967x5BAUQc1MuVRYJG3fvUT7ZCcH3hGyTJv5ZrhUbKDTCxaXCiTbudwkjX7YFIQcsKH1j8SXbMYHVdrktz6BKMuB6ocrvlvTlVgWjEl/ln4PhiCwYga915rLnDFUIRSHvIX8EUHCx4XwB0jxg9ifz34H9RBrDlRPLG+yLjnudH2kJSWuDZxSDUdIFw==
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloak
