---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgCbNeQf8trG28Inc7hdRjFF7AOBOMskoBfWLgAye8Y+rtqFuz3sSD5fgZqUwvClPqxonF+eyne5qDG3Z7VP29EI6dV9yEXsfln2I5z9i1bnoQc/Koss88rmDf0A3dbvdRxzwKxtHaWg+96aHMekblCsrx8246WhltjQp28jR5PeAZzrAo8bwIQGhgjIHla4pVCoHbFdl0kzlUpgc8d8h/ydljcQpTRCJjV5ALRfE6EX8PNS1tZ64VdAVyvoUoNRk+dXzwXPDH12kgRKnbZ7v3J6c3lQ9/mCjY5EwYrqdt+DTSmQku/6r8bc8MOqDF4A+M3LlubWcSHC7DF2axYSPnTucotVkUSpVgKKEcW24GWtC7fqR4+Qe3W2uyPNIo4XKTjr5hA14TkrjXwqPM6FxlGmtpkg4c41l2SHIkz5wXG/zqWeEBw6uhLTdtjIUmjwNRGXuDRNQX6j3xsLuS3VJKTrQ9X7GzqhF6lP4/Q+DNX0m3Ycoasl31c7wMMbxT9ayrcSEzS0YgCmnAmzCvEGxVbvDkntB0OwEX65uYDi/C1ISi0gqJ1gqFWXEQaHH7dwNBGGFNhsckEWwOBMlL7CWnvlASaqu8aqPBhVcB8hJL3Lf9mpTxGFbNojYluSMhcFRD4624/pevViuzk6qAaAFUF6PqoNNoYld+fsWd5MH+rH5cNJeMnrbnGPe0tEM9jVJdMj399mkmiMjaG62FZwNIf3sC8=
    username: AgADfbGucHV+e6p1co/SYn+Mh+ahq01n98pWMz15Yxrtqw9P4IAbgE/83R7GwmsImumzDkWrwLcKUuKbBr+WRejfXp4fSTOkKzEdU9UfGA7hbAS38ngEX9DmghtcUuu9ClKCSOdoaRE4RSsUHB5T+hafV8CIII7ERKUKQ4I6M57/MYsd1hBqc6SgkmKqTuaQrS6vWxY6yeCmekkSTH1gxr/wRJIF+/SIHU9ZLl/emQ4/xIrSFdJbQlqQXn/ZDyauw0tJkqqFbhxoUh8O6kpg80sCp7LgjMDDJWkj9s23wB7M4Ls0LyZrP7sZ+FTUPriIAGDEqvqbBtnWVKbb1yK3E88o3lruxRabFNJTaKxrhPKTU9/tyAO7OZRZSg2jgIpPXot2OguzOxFnko9J8MOH0DbNQZkP4SYeVUuLSHknqjfxCzR5bt5zC73qeSGdRqIp4hfa8DfUKAGHHlDx95ROUar/1gN4C5IkTaW4SCX58VsaeMutXN7GTj7f38CjTTOiGJUxv9njHATf8WxuH5AlM6Q8wGSP3yLbTZjZXPJbJ6Qe6xRZ9LGt0bM9ixzJwsUPfjG19Bz+h6j8XQxfBysRTdvVDBIPzq0hfiI4z2j8iuAbkBswdHs0ce2x97zj5UGPKBrhkzVF+Zh2y080fL3JEopWv91LocGlhEVXO2SwIyV4K7EpLde34etg2G8tuvIZti79mi5Mzw==
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloak
