apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: cnpg-keycloak-backup
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  bucketName: cnpg-keycloak-backup
  storageClassName: rook-ceph-bucket
