---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgAlOEJXY7xDtXqJze71jk98cgYCJVY3SG0/Nh8mKJDvrV7aPiZuGCQ4DT8ne2KitBPhnJXXoXmvXvjxGdLF3i3BXfXoxHUy2oHIeuYcvBTwaBVOM8YSDA/jo8wifrFWPgl4d6172HePfbCQhEJRe4TaHTVBRmT5J5gGbP5Wpuqhs5nvrpiegz2kBebfVNsJ59+xo0rojKP/zdimy33Loy5tFLaREOEpLifA1UW8MbxQfNDAGKSNpmdUXhKnsAGEExHXaXQgUqBFKlojSTTOMOJjQwPR3SNrtSSkBtDcJhtst3QwXloMjOYUDUCmePKcpoSVovlWuAl19aOJ7ySohcK73tvtM0WQC+B9rQJs1cAZtltS8POdDiHN4IB91bPv3Df6PiOte1L86cfhR9vp5FwH199uSPEbaMH/fdzHAr3nIFzyBcxaYTy7qdUl6RKBEBTdxaeRYpLDWVEL1tgrnwaz62oDz3HJotaRWsWVomHZyMPwMPElgu5eFvvlwC/HIb9WO39Sruj3wQvXjX0/26JV9AoYspucklcdkyG/6j/Beza5pVCkxVmDa9aVa1SEzMojpAjGb/+QdypC4pgrFtTZaSeqFArXQr3JopsGbJMM4wsUVlW2PzddglHm5cpvDdjoQ9Elt1/50jomcrMxz0ZywqKd/0AiyLwYVqSuf9dnPgbHV5b3Svp+X4qVKAPLMHgynPaw38dE3283M/rY8I3N
    username: AgBRaA579c2/cvDo1BvR9nCf4bMjMcZDUCu+Dt0KVjjWvyIYCX/O0fJWgGgdA37k9WXJb7J7P8Dtl3tEmkRnR2vHLdZ4eNmboCYSkBtB9OZ45qc4o7zg83L+f86XhLg/vsZcF57IIIvo0j0DFbp2GZH3DPiH2iq4d1vSZ/OTc7x2RFKy2KdI898fhIh/jRjw4aIdWoT81G3qJCs6tAjcUEEtpXHIClIbsKSkt55xrsjO3d1zOmrQTtCbf6DN8Obb0cWIxlz0d9HZ6Lr1aZsc8get6SK1Mh85M+t3SIjf3n3w5QJMf4QbhpypLviiFf2rff04PLwD/Ku2iEgwUqTyTw9+E32njleiecF6p1b5zEVjsxMlld0fAWt/KZxND3OFdBjHwU4W8ZBXgqxr2HcqyGs9THUZYGh86Ppo+cTTdg67N6CHL0H7Ei33D3oo7Dt1jQYxnCPD/eAiT0XToyrfATGeiQ6lV92MKm6ZI/UGVSwp0RMqDl2fP5mQcdE5U7J/gxpkHCt+Yq/8XBcwkJcT5+0olUGzumrUJJ9+YeUbm/FCVx+49FkMsEvZ2OICQNWknBAAMDv0W8LVSkfWWNySKpRenXvB28cFiBeWMZRjX8q6h0vHNK5qptd9ziYc8H6/WQ2PPdjEBDPCsad8e77AghJtJRh6lqiAXvgPxuSd/gpQs45HzNw13r/XZsFk7VLP9EdrID+Wt8A5ZQ==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak
