---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    url: AgANKztmYKdIUi5cu6ysgb24LeaeFf+HvA/3RfTkO/Zr7sCsVpSf1gqxlU5OVamCkcClTX96w2PeufNMM65iDNPj41JGpKRIH23iYH5ki/taXs8zN7YxVGNn09oalmgNrUh9h6fkdb2CqYZf5j6JXV16uvDfytKmWHtbxs6s3n9iNWG+A5SuE7YEXRdk3fHtFjBDwws3Lweypdc1oFzhH9pCqb2vBYhlE8xJZsIi3s7FHK/rzNdookH7ZKZUnANXFBVWVrBXmSZsVy7dG6CnuLHEBmIEbt5dTnBBbMRZ92p1GIh7DEclNLU2VxiuLCTRaiK/Ho+EPA1AGAmz3ablXXQB3zj2fe6N0XHIl+fSZ2x8EStBvWCDbHF/gkp6ohv+sJpr1NiJ1ZFNR3wFEy3gqdfbRjtSfdrvM+8MVXaK23p3KsqfFn9X6spmBxvo4Y3ci74sgadCM3ZXaJVU0GHvg89uTw44UuybqOdqRwkjBa1p84ugZ3wkXVqvuei0f3VMsgslBbr9w6C23Jdmiw52iLvIxrVwXH5065izG8rEDDq5AkFZJInKknlqvu97ngFwAQW9YbbWKffTkdHJbh+aRlmkDDAEVEQh2mmrDBkycX62hOmBQcVPFonXnhBDRXhgoX2ZCBGUsAUaemVMtETgI8JCW0iKOXjK1HO/XQnqzGWn9p45oxh2SvTGHHdNc7hcbFlpPYRCwPF4eK1dzggwBoX7OppHQdbhzfYs6Zo4d32lx346z5UC7dwdI/6TRJ7tC+dtv+NOzh+VNH1WggVXJ7RMxFJG0kSTqrJ0XQSzU7Xov6Q=
  template:
    metadata:
      name: slack-webhook-url
      namespace: monitoring
    type: Opaque
