
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgDPvfrJRgUYxISo7gHj57Ypx+nbFQ0Ce/DJ/Y3TYQogFYmcEucvJHSF6zu1ogqrHc3UVvCA62wprITKxSEu6L9dPqVsRqYXLeFw8m58/ajiHIFmOberprFuwqHanWGbD4IVQ+Dz3Yi8T8akDC63kpPdXzHmVbpwQW0Jc0etKvafHxrvyc3jqLQv88XYw91Rgv0TYI8s5f0W8d6oawbn6P1XzxnVeZHUkSh/rkBy4TVWRhAV2vfCfMxFFG4k6xo9Q3gusbl7MDvflFkaMRg3r8IaTpDUmQU8Z6S+5WA+LWSHmyQ315zaeO/Xt25kzMlxo+kSF8LWFz/a7FdvzspjcXmLzYbpsawWLaEgV4Wxboyxeg3JrGn8hSvKdT5I+4SI7ArFghM9OY1+72mPuDAxlvdX9rwuDXGypqxIAPKhz/nJCkkEb0O0Qw6UuRy+n3GJ9kxMt+l26fENwPJPaMsp104Cvk7+TKGV3y/iqWsBPrQ5QDmsCCujfdtaR1Lslhy3sy8289/avSUxmBK2eVYcS9iK5GES88pNxkvPpPvjgUwun5frP0JPGTsrxoSAftV+IKm1MIMhNXxHmgXMyZZvN8DVNuAcS2SxOo5nk+dBfHgFsmh+pbU4yGQj+Sz2KjPLvu6H3JEpKyMB0nuh+ydVkMT+RSv9lVgUA3IohOFMgYixqZcQ8YQ55nmEEwlrWf6VnbUw9nVkUwllf5/A9BHFquHrUP1kC7uy1hHRipx3K8SGzD8L6vTUaY6R
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: gateway
    type: Opaque
