---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: elasticsearch-exporter-credentials
  namespace: elastic-system
spec:
  encryptedData:
    password: AgAd0P6gEzzadAMUpbE6DKUkqYfzEoujZt0p55M8yrRTADHySAuFM5JgVk3ZVSRA0yDEpUfCAZg5iqvg+gJ/iP7kbrYcyO553ZqrOzLj1IDwMva0z8Lur3EtiX8cyeQztxNi5qsNMkMk4c5y+qoNeQ9fNlBsaLAU7WLOp+5tHFFp+B7qQkAU7rCTbCzPm0273jwOEWcxjBJZrfNHMRafc1pKuXpRgxxBu99pJgPx+k3uvXPQb3WN/rSym8tXV09sObCiAreLUKQcJOMllOQOP8CJ+nKv2sMVFsaoEyVtoHRCISNJ1BNNU75/q6KtCM2c88gmdT17AtF1mPe79CobM/VLkkno1zuEI0dWc1SuVmKaHMi6cfGGc6jpFYnvTncCFPO+Q/maj7mr1IP/s3NZ9OeYwt0DO4V37rR2f1EatpFwOoOJBDrHrDDRoHfoObp2b4QkSVXS4M4QwS2nzFNOx7QtVYESKa1tdxectMlJ0lZRc6nwMYcErHIWEaQwncOc8POe5ZgmPla35+BLd8cExPtCZnyu+Xc42/mutTdAxyxQYxUGnisLcO9W1GcMqKspInKXDAtXMLDhSOWonKrwqSG66IdWmd6+EzP9d3OY5GZ4a++Xtc4w9WiVhMdboHOhd+BIzSWUmVk9XEjwt1zdgF5mZh/s6raaH2V5nYXEWG3NhMPaGOnn15eixZ+VqlfNeAwolz+oB0y3MspjEsU9UqFfr9Vep+91GjfqAA==
    username: AgDGyHZWMTF90qWr0+1u11mOctB6CDyv2wywHE7Oy5MtbL+GZo/X3UM2Tsay/5ELyxXsmDOOzD49m/ktMl/cRAIt8oKfN0S6qgTxqd3VoBRHYnNf6ec6Zv+gK/Id2XZVLHO/BC5oU/q0wp8UFMGFTcZ3HEpCcWeWx0fXEjaR6LI/AxpLBk0jbpAgQxBHRkw9jOUm5at2Zk+ZaB8BRoZTadcKMxvDeoKw7qb0mhDQlme0eNHMRBWLt86pSAZJB8RPD7j9er6urqS24RVDX4E6xLaYwDME7VyU3URxPaI8yIx6hdE2ucNw2snTXemZihDJiYwCw249gKhMqPTu5qZBUuQEWIXwWQuVDArRzG7wJo26N+V4BVo0JXExk7xHhFtMuWyVNwmUyEMyiRWEsccvQwFIE85xYvUdUrLZjhDd5BOcHpXg2NHxTpqRlJ5SAoX9Falom1VnOnbtSyPFzPGLG0Y/WFek2Zie5e0II1LI0qGMdyaGeZlTA0RgyEe+oN+rwoHQn98sNB4w99zjDBW9skvKJjhRQrJEOuqTqDPv5NxnBLZrnkQJjJgiZOrvD2E84lAATLOsWH/5CCkoDeZz86T+nJFcNpfendUFIYCslXeNWOhsA5OSLWAE27D9xshop8W1uP8Nq5IoBrMOQPXKFXVQtQftgZBfWGtDrJ/10Ctfzgty+0WImzFKZf41jx9ylQswkocdhROUXPmi1xlRSWuFfD5y
  template:
    metadata:
      name: elasticsearch-exporter-credentials
      namespace: elastic-system
