---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: watchdog-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    url: AgCMFMBSJ8Hncs+ymVQa1lp89MaEw8IquDu9MgC9+br212phMzgMzybZEUCj7Mn54YwLUd/UF1izVWYfcjW5oV3wBQ0tVOdcv35ZvkvDZ3Ql8EgEDJuDrMyMuefzGBB9a2Fa8TCS8cFU58NAOZJOxQtcVt74D2hZiq3jZ7ilSDbO/Ix0MoNiBgIQYeYXI8cSoF/UmPZR+Cny4hrzaLm4eerxj6EOWuzmLq6oogjBkdcfhgBIUjLt55xx2QFSLzTTrAUtlr939avmWskmxTDMPaY6f2VSDVwwHWlg4djSYFv2IyKcJecfTrWUBXZznSCyZSP+ZNFK7j0lFDclZeLOEV/VyxEmo9aoWoPZwUjPMzTzNF+rlYumwJ3LMfQC9Oa9DEzyQKlzcPig5dOzlFwdJirvTc7gqEaP+IfYKVZsNcdoOf4r4qGB57t6jkrgQ0BGDLfyMcnvC9uEPP2zq9sWvCIn4glG08Xsh49Z0ohUvdXM88ocfK5YWZufy0eZN+egQ6NM1Z+Xv8UriYR0ijfcW/B6PbGTgsOacA1P8dDjECWOLN1Dk0p6r0o+k4qIZqViekiTDkPPGAvY7oJ0Amjo7TYsIVHKwjnDyXDqz6BA5+dwiE6i8+K2FTEGs9ba5/Vo7a/BJp26gMNY6mG4PUmkOxC0zZXdl2Qibb9GKmlhTZPi6hyM45s9wLbfBzc1c5yDVMWGzHtNCl+NUXh8wBo9pS4Kaa+vbaoVAMEWpZ/p2bVwVbHuVSoS6RZba1SyyzQKEvUW2UWlOvGZYw==
  template:
    metadata:
      creationTimestamp: null
      name: watchdog-webhook-url
      namespace: monitoring
