#
#
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: worm-weekly
  namespace: velero
  labels:
    backup.tier: tier0
    backup.type: immutable
  annotations:
    description: "Unveraenderliches Wochenbackup (S3 Object Lock COMPLIANCE 14d)"
    rpo: "7 days"
spec:
  schedule: "30 3 * * 0"
  template:
    storageLocation: worm-backups
    ttl: 336h
    includedNamespaces:
      - n8n-prod
      - drova
      - keycloak
    includedResources:
      - '*'
    includeClusterResources: true
    defaultVolumesToFsBackup: true
