apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-backend
  namespace: ml
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block-enterprise-retain
  resources:
    requests:
      storage: 5Gi
