apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: uptime-kuma
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/pod-selector: "app=uptime-kuma"
    gethomepage.dev/name: Status Page
    gethomepage.dev/description: Uptime Monitoring (VPN-only via NetBird)
    gethomepage.dev/group: Observability
    gethomepage.dev/icon: uptime-kuma.png
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: gateway
      sectionName: https
  hostnames:
    - status.timourhomelab.org
  rules:
    - backendRefs:
        - name: uptime-kuma
          port: 3001
