---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-exporter-token
  namespace: monitoring
spec:
  encryptedData:
    api-token: AgAYMA57Pnv6H9DwDvBbOftInlnPk5zmyhWyGk8MIlNgqAEpLKZJJ16iePGH1cTee/0o9csJ+UCF3RpMrxIAE1Sx1RcdZ8p8vrStRXWErFD7/g4G5Zi6C33RsGpd77YVKK3Q50tnYRXq8RiGrjmQsRGRZlc782bIy0nf8eABQnDIIf3vINoNXdjhKO2DI2GBrl938wfC8F4eNKObncX304NrLGDYwnb7xww+AfWtfEb1Cm5EiIdBmpmUmHfcZoxTlFphrqWfLbwT3Bmb/2Yt2oXSjgWo1JxoDsIPhrroTqUL4ehsa0dGJ1XESHnCu2LTV6vNBs1I2xkaTM4+uExKVi6NT7mpsslejV85m2TWbHL10doeoXcp+n1iCT2mmGVA/amzYVm0ZHUUMiC4wR0i4bAI4MJBsCasRjkFvt08wvgNUOUHPddxMBir3jZNScRu7cVUM2t550t1nq37f153FusoAkaDTNXLyoiL3r/Ky+nWNG+T/wCchhFqYuIkl5zRizWvJNh8e4Uio6wjv1e4PZCFmpCx6rvtSTiCdy0sL4pCTmBJM+1DE8F9oMrwUGPns/Gf2F2vZtDtWPC0wANjDxnuJu7vETAnh4VAptbxUYmsgXKSbqFsmwWh/lgL8L8qgOq2BHNxpLv5egHnijdc1nsFQel3L9nDKRu2Aa7bVN3Sp68mqKrWla4XXMjUh2UB8nyp/Zu6LKIJqU4bRzR/XfOmasjPn6KhlqfY/zTb2wHrffE/dkVsOhDF
  template:
    metadata:
      name: netbird-exporter-token
      namespace: monitoring
