---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgCu/YsAmusg8ii/GVxnNyksqiyOjywJ2VoMUHqgzo8x00gzqLwyLpZu4Gj6H0nMVPd1VmQQDhmPRoVPOqo4pNjdH0DtOTlpcvL1ZP0vjNEVxK1WQ3jVSv21DS+3PtWYTvBJtqle9aGSGBpuF1Ir0rWTOH40fuByNTHGQdm79Pa5a+y0B7xcIR5o3C0+FlnaCErd8FQtK1U0pJZ1ktoiBHXafnsafO6m+u413sVAHNR1FoqM9XKPLp1qKgzqSlqmSkmKWIIuiBMPDIQej2TvVLAlCCfzU7gbdBalmdIIDsFYpz8y2bQDyoV4XbxpijH9DbYkNP6/VZwMjEG5r/QeOwNdCNZTzA24yOpVMFnNaMIoLdE/jW4WBKm0m+vpCdKS+AEHpYj6HzCTDZy3q42dSehNVYWzPaRXcZmzBrCYb6wqsz4ojQwr0k3ClAV3FWRqASH/D3VEsEQPu7zra0N3g72TTG6vICEnhrHnA+yvnS7Ty5m6FSBKh00MWqnznVHTpjoYhr5AnJfK3v4Lz81m4HFdue+BplIP9OmpJZ5+Teag8vIOyqqtclVeQFwuaNquxFZeZD3ScFPE43h/1BW218cWyeuWrqBT4Dd0pbt3VPKVukntkcoekC23+UEAVUUEMcBTZTsrWNkZv1iFk4TYgv8cfacpktwTGnMU0J2ZxqPnz3sJ3q+Y/nnbK0/QcBrLlkPKpfiPtGoZjU6MZP6aTKHYpYGbo9DmqVB3iIuxNBY9kg==
    username: AgBPWZUa3eXDmOy5VOtm7IF9ih1yTqHfzQsj7iXcpX032nJ2QuiUn+ytLV+e+IesJFJgOzVzZbyAauOENyoKRPGvotQ32P7xmQpd6eiU9jPWx1fainkA3/G5kMtkKAkMy3DOshHr4nXnABBszOuDYSqmCFIOLXHMVo5WZRPi0uQflPKadArrSrf8AGQR843iqbdj0nC9fCLJLIyEKdUDk3bBTBZ8opDfpsfXT/UUnP0RQlnXR53bcG1UCWcJfJiC327Z3BAaw4RA/r94s+CXgzfCa6Z2haxSQS9E11MwO3HGLg4oTaKBbGxLYc5tnaeCE8jRk5s9RI4tyz+SM39pioO9mfImo/xR0ETGhDI9kGcYJ5zOR0u1c2W1CE9w6Oi1DiNfV0kWeuntxzoaY+spr4cYEblMNuvxSw/0nZeFmWydRQLKJAiJzYhXc0PfXHeEgsA3S5GdEC0No9rNYzxsPUQ2b397mSdpq/6bBV7+2Tv2knqDdw9fnqffGGpUKks2YTJMjAq+v4mobt9GtM2AjvOErM6at/VxIwYgA9lDvCOD8b6RrDS8tct6zQxDGGhGLuJJhJWpoVwyn3KhlZ4Abs4zRQr57vokagkR1q3dXeWlaFB5J00OO4myUITol5tz7sMDOfNpsdApmigFLENVMNdIXX3T9HpQEODtgjR25s0ONcUqZ+TBKeB/TFRcehhUBV84YGkMWA==
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloak
