---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgCOIkirmm08VaMvQ4kABUNij22yqFpXyOXkjXyf9+2Dg9IMHC67IqGuaQbRBGe3zF8DyHWC7MiokKzRwvu11OgscswuHtt/T8AtTUNA4GavdoiyXgKIrUF1mr+1o6t8sM13RDDpiY9nRH5llpnG5C7svzEpfvGMA1RXNZPHUNs9wTUMaUtUu8fSH+BPK6T7mZCTO76Yo+C9WGucRdgll9IJxG/TbPXjIkVxsNvq0G8dpVhkZAypFCDy/4WI8Ucgu6J64J7vwLUNZb+Cxjgvr4yppH7SjG59VwMGmBcXmnF5Mf0UB0IxFVnfJFsOgkpFm93R4MQem/jxpaHSH+wrUYz1IwWu8qrrqrLdH2pWucIiEGwcx884Y65Qwnr7FVlypza6zkE8m1S9Ck9l0rlrwqW+PlneiQ90ZGrxdPk2olR5OFrsrGHY9Szfmygm5MNJkIVPV7Z3oIawCUq7Toz0rbxu+KHGGUVrZvguyn+uc5d2fXn75V4PLzCxJzWQ6f4TLNbEUoh1rLzEwZ+uNiYSdsbArmEe18W9A4K9008t3NMSVpF10Z0MDlj/4YSEbz1CjXGpIBXnXgQT4eIYbYp6oGnmrJTIHHbFk7zFsd//y4/tOy9SaZnR1WwDQyCtgcQ6KN5FIpv3Ibu4tp3BkK/PmCEq3Brm73xtJOhakoWeYqElQTKmLVX0Gx9rpkKoJflvnT7jslTVRMoBa40lh5KTOVwbWLE76oEKLq0dRhGfnzr5Gg==
    username: AgDWL32JrdI7+oY6j0hPyVB00R7Pv/B8VXGeiTNelAGrJTgCncYKpO8UhqPjqrViGQf9sSJmh5J66NvaLcRUAZsdpbFdnTSYLQu0NE2VErxLKZ0cSEbI27p21N8G8mKryuBJLlLIJKpq6rEFugZuuJDf4bjgeUui7ETvVBuBPBhapeFTV0W4dCwIrp/+wPYllDSR0uGttZZVf1r6OiGz0+1AlvcAuCSI1YqO2MJXyMXZRV0W0x1UahAD4GMKW9hOGyFc5squJOBI9IxEfoFzZAAPaSoNKD/uZzJsmcJc+YUJIwCpG4u8aTkJ2mzK/o4ufsfFB1/sQJfaB07sJ9HV3hLrTgMLtkSthI4L6X0i8aWCXy4/3lrMUMGS7htQ1Y6zjDOfDm5LVhsEOoGkUSR2qkjHVbSQ99lUdNcBv5rO860dq8ir6O20k2qLKJfpAlwXcui+iY2unl0h7d4FwJmA36pX1rlnAS96WNcPpZbcdQ9WcJzbhn8O+8DTG83rwuCqR61KcztfEMD1wc2LpgFQXurngzoz9fIgGOBOkR/vRttZuEhSOrHJlmPhK2OvsVoGrp8ZooElrzeevF6Q0vn3Ywa4n4F41Nb5KfnzwkMTFwTFxoubDxSh+6Bf44YpT8Ylkf4VSox/Z/tpOEIoumUj7MV7tMSw4+LEGgDS4YeE2cKW23WgO963V1gGLakdsatc07vjHlJEbQ==
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloak
