---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-oidc-client-secret
  namespace: keycloak
spec:
  encryptedData:
    clientSecret: AgBzHvn5TN18rFpIh9rfy9dOwSL5+YxhmIeRZpRuwGQbwC15jCTNxWA5xWKOO9m4zirX0iPO0eBc9X/QZa5wtq5CJpGMSmyqhMeofSFv/mIJpuDUKmL3Gx0QVzb1nG279E6ypnt5fwZ830/WYor4dJbfcIAda6ir5+oM4nbkalDH1M/3pm9ucYsksgZTwLW7iuccfO7pIDhynU+KBwVteYlnW3oDocrp/OZJUywKaimB75LD3rwbMg3DB8Dy5ZogsLEV6JUXdwNBxulbyND+fQ+2JkdMpRn6PDlTlySlvPEioHZ6+ld8SVMKsIRfIg78kgEapEcVvaUtvNaCayyaI+5/eUM9iUmpraNQF4K/IsmOBEjJcxC2x5wSYpEidHtgqZQwFsVWxvWR7yvFNJ2tyFVbbovSG8f6JSv5t4Dh0L8dGgLM2Uxiu990vrWUdruTspsN7bg0d2uIf69nUsnA/jp7I97fYUfvgYRUrDdw46mzLflnk0/a9115b9dU/bLjMaHpxjl6vEli0bgNRMrN/8zB7PvggmLZeOybGitGjOxQaATWdhz/KW5Xn1hYRpZqVORC6fa3cKLBx+cKa+bxvsD3WZD0LCZsy4Hc2JHDcYVixMfPmnNASiVCdU41fJiUNdH7g8lG6pHVqqeLeRr62KGS/nIlmpM4jYYmPyV7luase/Xlgp5ZXpek1G7sEOdN8H/URteHA3ysVZ54O+wDgTb6vcs2fafitXM=
  template:
    metadata:
      creationTimestamp: null
      name: argocd-oidc-client-secret
      namespace: keycloak
