---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-oidc-client-secret
  namespace: keycloak
spec:
  encryptedData:
    clientSecret: AgCWR9wOhyTDSTPscg3RBEVDSdZbNerfQ3QQ1uA6/uEQLa38InnZgDQVZGKa8DKfdQw0iGuWZfUXbIg9IEBECpoJVl99nboHQiZY7I+7e21OReWuufCsIfUCMWA3rh21LJRhb9o18rQ/9meqXlD4cpfFFPVHxJc3zXwVQNdF+sAUvd4gyD+Yrn4GrQbne6d73A0/z9RkaVp0IMxuEsCFkN/Tv8/WIL8oYa1dvS0+x2o8lJAqQZ6BzC57g04Dd7OD5578fma2LN9aIe89u90flcK6gZwLZqMvKziEqBh+D5uIcw0tNVVcREZbgclADLfQdUvjlnuijNqS0LlOb4KICrfI2bPtrddh5SDwC11RMqTZiJht1t4Mpj2eclXvFSYbpJBg01lAmAWdi5Vi7ieVGjb0Wg8veL5OtU4Va+g3OVu4WkC69evbJsP7Q6BKfLAheBqpDPF9aLrmxlv+n3OIa070LGQqAUvXiojjvdgpzpZukDuXa8M13Vw6M/siOtHrUjgKJoARXgLBB1hCCp0Efsv6E6kehFvfYoqDrqyLvQQJmsDWzXgPIRyqlJ1Pqyj9jpa2+odA6fsEYpiVSIhH9I6buebJyFHeZikqtF9hUboPNOBDDG2/p7YcyhXuWGwAdTjNrvIXV0MWnsxPW7COi4B0pCeYV3SLWbqHNAYvWObKr6Ts11EEhKT+OqxhxBOFibbEImVNUiTRGogVdfGRXoW0FpGgDITulBU=
  template:
    metadata:
      creationTimestamp: null
      name: argocd-oidc-client-secret
      namespace: keycloak
