---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-config-automation-master-secret
  namespace: keycloak
spec:
  encryptedData:
    clientSecret: AgDP33+GCu7ahKLsC1ND3oX7+fZWycceRUq7rE/5ke0qRX+krOXPfEI8hLZzgNKu0Yp/t50D6BY7/mR4irr1jbR9dZL8kZSJCWf3bgIUDWweglco4V+y18hUzOqDA5WOCvOWnKlrVoR0/16JbbeNz2r0wapAFWZZkvzNh/eA9DC42FBCy87yk34vGN63nc0f0eWZZNZ45xAaYv8OxkrUvSoPRT0pRWh530Q2LXzOxAugINZMUFzEA6AU+k0ckt0Wl5Bc+eoKNiGdPTAi5Lz+AfcLW4tymXOVhNn78gU3q2gO5UIKPyNpSPTDtNc+H9nNLc7Xh/NgRAHKqbSunBIiYLvma6/4Q1Hx0+Nu8GDWNsX/e3Vyq5D6axtISYSBPN6+lRhqutEHzOySpkY9BZ3OyMGva0wv0fUTOxQn6MC/TShuhJ5sAJee9X6k0SaMX6ik9pVf+1d5ig22JLcbX2QUW0npkPMj7RSI5dsDA3LvuB28vQfoTGtSKCtR3LUCmHeVqu/5Tkf6M1sjAVWHJznHOdyD87/+IEjOX7iUnNOb6vFAZUr5SyiYz81Sg1oeiXRoJqpyaSzQrAj+Q7nTdPveHq4RmunXP6Z/ZD8gInf6AVKQpJLAqxfsHNuG9NKrf3maGywKl2XzY7ono+i0X+1Um1a6pxXLfdiOVsgB7jtpBZ+LtetL7HeUF76HijAQ6C1wLPOspjdre1Bna4kpEzlCnFm5vgrH9szHLwe3dFia7H78XxRWN1znulbDiA==
  template:
    metadata:
      name: keycloak-config-automation-master-secret
      namespace: keycloak
