---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-config-automation-client-secret
  namespace: keycloak
spec:
  encryptedData:
    clientSecret: AgC/bq8YI7vqG8TW1yyr1axXrigk2jL1yiVVeW313kEOQXFOz9XEwEhZrskvy+HiE7X2ItjIGC5+YtbKTc27gKlY0rlM09PR9CeY7oLpNXsZjMo8x7GcsWnO8motvEgJj+9sGnaUs4wOf0EkR2aQnjHImsKLL+Dj4ERN8/odSwnUaUn4TEMUJGNXv+bgt/BQ7LTP9JuKXqP9kkQt38Bth/AOrgDmcJhxuld1DAcY96idaWXXpfiGFJ6Gd8kOhRba9+xthqIgmzxHy+5yERIwNKMdug1Bgf9GYh3arOkUjuEOkBjfiHT/KQ3UlBhuhy3NQNBBmXvTDYbQUSHkIq6v5Y2UBJFFTTlZHHLo1KwWfrEVjlQYy8vh/EV9lRPQfjccIJe7gEzI8YJ29tkyx8QH/ShFYc9T1rlvTdqbqe29phAwwyt8giNTU/Q7NQ+3XH6OmXmItQCYQaMmFDftljkVsAs2NV4XHl6nEXCvh9tvqWeeWq615gEzeaXgf3tOBcY0ZTPhgkML4+1lZeBbnWIpD1wTgkMWIJkPB7KiB5RFGuRrICQQLj9HwSCF7U9tJwrV/EOjaeTIo/LHnBiFUqlYqEX4gB+E18wiby9uP+Tw12EeVnHzA1ilVih2gbzmnyKzI0e4xmlyOmFHfDD4BqKhPO2w6soNZ4eIYCUKY7zmnzP3N8cRHfmXeGuIK19xRn8SNYdZadQtP3WjPn1k7Yp9fxptJtJzIILNjPm+PADagD7i+ItVi/nW5axdTolhzk/pC7O7rRuYhoLN3w10ndJB2Umx
  template:
    metadata:
      name: keycloak-config-automation-client-secret
      namespace: keycloak
