---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-config-automation-master-secret
  namespace: keycloak
spec:
  encryptedData:
    clientSecret: AgCljoAZNliTkqqjnnvwcMwvhBGdIbODqTwtdRCHU/5CZUNe/rHq6uqboPfnmw2QOt+AiTqPJU6TbsyeNPuwELo0aDkutdYcdpWOhHlE25R70MK328wqG64OFaRgULVXfPQx9BM/FtNZKX9o3c6w9w3mDSaHEgsInyxU7ZJlugbsJh1pREJoLArY7iJKMvXS/t3ZoORG4m7GZWOcDJ1+vpGK+iE1DCqtmz/nZytJ9vMwREXrIsKfoB5Mj3jaOVdz4JTwjpwjQKUkUUfie6v9HEzq8FzyDwY/IX4JiTJ96wIPehkLoIV7Oo/rAtYfDQunbvr7FW9yUYOToObml2jVLlZpNEJLR9vcITh/zHo/9ys2a8m6ScFEtTdPusc6tfSZQqCYXfTjtzxSAtNNVp625ichg6mvKyp98vtBSrFSTkWMoVMnaweB4U3SYcHk6FpZ/5WbeMWxLtGtz70ZjADpj4WMaaA4Mr2QNq2jKuydb4xaEiTailH8Bit0GZk/xtBbkWmALhCLyaiXFC41x92rOBvQnK+lxVcuue87cpgIy2Qzf/K1yC8XrDone80aRjJaRVbUPOw2SsE4EInJy0nKsL2hVZuAFDo0Wwu9e2uvTbSUMkBgHcl6lBojjnZTxuv2krOpcdLW1qVLNBbpvaZvw9lvwOGpEa9GbOY2C92PeLoOmpamqBeS3DbuNZX52Mt7ZuWsPDe7B++M4mE/H+MtUW76VdA99rroPWOOUGXAYNxuCuHbAvJg/8Xf
  template:
    metadata:
      name: keycloak-config-automation-master-secret
      namespace: keycloak
