---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-grafana-client-secret
  namespace: keycloak
spec:
  encryptedData:
    clientSecret: AgCmhnkduCZXkUEua8dNwD09p+zwk/HJOuZC0QtPW7dUR/KhGWI4LJugPl9ux0DG/A69Tvh6CnfFhR5DgKVvE7EwFc8nnFEb85979Qq6dhV3fEo2b7KCHUfCgCLwLkcc9LWDxD7hbbM6MFoIwP4/Av3tSdJnsIS3LhsKJAE6pFGutIecOwOcx7Q2o8Nzy6Pv0WIR5vRkbOL+kLkIcFYbaHYz1+KXar57DJiFb8EcY0HJePTrp0cSb3BfUiJDX8gKji7SO7+NO7kdcaoh7IcJtxA5/6OB04++2WSusPm/iuZ7tDYhVtKhMaphYNpyig3Vqhf+8b7InqMFcdwMmckHpH0f1Lvy1oj+INsZQm0YK/lYFjXK+ZltIQHjweipVw6qdbDVphtdzGW+CKIjQ/Esc1covJeOzdVSsRG8nGfW2yuuaYmct7/mCgMN/Jj2+thzDNRxAhdxKLIWEWkzBp6+mfFAxrAvR7HtQKLCZCig4RcxYnb1Fos0f5EcTRb4UwCiRs2+6iqOhhXHYWYZoW52EAm9n/hU40lkzjjW0Apt7XehePKaV4bs8wfo80JTeLhU214lwjV08FvsX27xDEJMEmpLNowYo8C/mtc16LX+x45jKdgbvRcXHug4lFo9tjcmqIDWVXikD/yytl+fLqLN3woN1jHTL8Le9fiUMiFyxTItxUPBUj5LSbo0Lw5taDLlMn0YwtY306iEfwXcmhVtXgurM6QQGA2JD0Wa6PwUZKGMSA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-grafana-client-secret
      namespace: keycloak
