---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-grafana-client-secret
  namespace: keycloak
spec:
  encryptedData:
    clientSecret: AgAEosbyNiBVPtKVzlsLW+1OU1SywoSJcLW3vPKE60sJUpl05ch3JhbM276+KI9dxsRUKUWy/TtBzmNBigiHof3LwseG/fHpOSp/cz7qNYkddKMYQlTym5B7tfi32z4So2FEmjYVQiSqeuZSHrxQIWFHhHQdDANSdROaj9KoFluSdeof1chrO2obkxElW89zcMBP/jSEMetImjtQfAxSajRIZYVtbMin5fKeE6Q1lDXj7FvhFdl/A0z1I9H+5UWcULfR8Vn+Pgj4hpwdckgH/BV/FkPYPPu6+O2z/SsHou9BKmyE7LKbY25ikSoa8CA1cxAvg+3ADkIGLz+5TJJQPdmjtB5pqwJarqkuLpzz9IeQ3Ys+gBsYx8utR+u9H+7ZsSapTt31qRyGCCbi9XuJRKpnsRKE28ztzxPAQUJ6ftJEPThWnRsRa/UXir6Cx4HZ3DIhuWzP5HtZanSxCFj1PTny0rr/xRfYfr0OAK1EixTff8De5D/LSm1Y+YyxUrvOaiNVZxIteRIWx4jQ3ed0C6JcGaaU9RF+CTYLoAbHYIFoLlI2uqAJ6vXKta6oZoJj446o2paI4awe06KGxIjHOQey+/Kdd9lgZ9k5+wW5ctZvcIHVNsCnWHXHEP1GJeGDbxubYz+uG8I0RCUy4QBxTQF5F4RaUlGwBeUR3ZzTvCGIdOPiOnqd0/vsi0qZ3W5/lbl7xaid2ALOv3V3ObSzyQ47EzVP/tHqOmd1xLpWrkk/3g==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-grafana-client-secret
      namespace: keycloak
