---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-homepage-client-secret
  namespace: keycloak
spec:
  encryptedData:
    client-secret: AgCeOJa6wtp334Quw2Rn4i5gFzVuS3fegkn7/Zh5XTOjfskfktULEghJATlR1J+T1ycwZmBnQqSlRAs0qGUwx2VjKOejLZErOpl5o/ruULJyJGhuUs+kE6y3UUn1aK4MvfPbIgb/DERF5q616UNlLJRcrg4jRI79oDvZMpLwK0U/K7GWXmdoJZfB2a0r3kS3s5ktr8ks/7qtBCzOoTnr9QoRg+TTHZm1DRk5Y2Zg4y8H2fUzXMs/Oe6Fq6XjMxK6np+5HZApuyx/gGjWhVIqFpE/CCkY+cb8KwxICuGzBexmiMQBBPI1u+RoaTh31pezLjPi7xPolq7aYTXIG5EFMdyhXYVx+n8PzMkv/qkeJnySgwo8CuI9GhrEDO1RqfBnC8VE5J2rnOzMR1+0UATeWXRoNkEZniMPUZWcFl1lf2bByE/XQ+ySrsgE07LsEl8YCJh8t5R43ywHCQDt8aFwhujfWFlWzN+QBgartfrX9EIkKm4+zVo5APZHjALrdFHcjQL8JnT+zqeDRazuberLvt+9/cDE6Jir/AnfubEQ227xGPb9KvHiWSW3O1GGvrAtxHZE6UBJgFb24nQccKV3NhozA3uwwsIPz0UeWiagmPwukYEzJsXjKCILZN+Rlzd2RiXcUx4giGAmWCswBewKmWy7Y6ZXe8eYsJrnEbYwfgdd69XHtCudaLDTxdFwzm9v8S9oYTM2PMOuMI4zrNZD6N/KxaKjQvEvxYPXNRt7y3BNLg6snfGZiDJoGXKligxBYJ4=
    clientSecret: AgDOzwijfjOuoI3dUJjL51QmcKgwRCGuAJIWLqLxZ8JAlYnoZgN5fPC79okctU+78QXPadHE4xBNQnf29/y59iVEwFLQQ+0bwFqyJb1BiuB2kTGPd3woZSpasnvjbKY6a5sjjy6BUdajK/iFKS3F6vEtYhOIRzjYLgrtur7pa4dHPGSg8ffH8YITMEtFo66nkRy+SF4HfxMtwPqTE9O5kl/Q/oTsaSw6VMVCihvokdZ3t9gV90YeTVEoa2QcEk8cn6dZ7xiFSUSXL38ns9L8FbUBao7PGkNwaIsxmly8otzK4GHZpH+Y9ZvjR3q3QDRI8IzAk+aMkDOysR9foyN9xknVg+nkL3jY/WAR0U01MXVWvfVkQtgHtoaBfJkRTU68dOg/eSzlgHPrLo3DW//jyeVrDITicEUdaSDvXJb9mjbzdXXz9Zwu+nxiz6LDzA6r54L4h4gwz3SLJxnH+IW9Y5l9PURFFyUe6DoPaQAj8jPs4Ajf7JScgPFgZUlXJAyQgiDMkn6hAl8PIkKaDUh2SzJs0GCO/zP6L5IRbcuZrccEUfND2EVkspHgs7kBOkr57wW5Gb3TdG1BVzDT7LxgyPq7gKyMPgD1FHHLuoDQ/Zgdpcqk8VUqkQv5vdA8GaAcTWnzGz9Ua3DDl30LSzO45uzI8kwH5dvYdolrrYjCKhVwfi1zI66lr8C95oyhyxLbYFaM1zWWY0YLgQcdM0ePwtk/oo6Uq/bdGJikgqNLveFwr8EeiMuWAPcM1Ztb6dRLIiA=
  template:
    metadata:
      name: keycloak-homepage-client-secret
      namespace: keycloak
    type: Opaque
