---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-hubble-client-secret
  namespace: keycloak
spec:
  encryptedData:
    clientSecret: AgCvzsbiMPqmZK/cbtQyQThUJKy42DLVF27IwL/ROx2w1vWj5ngbL3zG9md9FfajtcR6dS3JYnTxxFX1F8Vv0WftjMYImfrIKx3kJDNMci2yDEBeMyyna5ntEZjOMfZpT49EBgO+0QG0z2NeR7lQ64Qul8In3xWcyH67PsyxVtTb8kmL+OvET3nLKsEtZ8QTz25qmDVtq/6etPpdnLTJm8MFB67bYzzCS2VmUB9G5MjG2ifr6q74VqEf2OnKiXpoagbNhsIVBLIbR9MMuwts2xIDWB5qEqnRfAekiTekjMDW/bIqTCsNB8yS7nSwhoNJrYN8Q/+z+8a4nxbK1J2zrkK6f23YaTlnXS19SG5mTO32Hd1Yc9YALhFJggkxF5dSVbWEYVWDONyMN6zN7Hq5hynL36Sa/Q9LQfcWVF0+BS/TJ6MsX3bAEmuv9qmRXGQdij13fJNMcbUvaGpDHLvnZb9qJtr1WJuG3peB5wMNWwY0PQK2N9qQRHGcE0VgWd/wsUN2erRyTN4/6OEpq6tGJnJ+U5wJpz7FbzvGVARneY/hFIIt3w10CFKswZnldtN2Lr1DMA7MnIBXnf2DLJpiF+O6pg2J1Hyd2HzCj+NA6FOSOy6PuqFs+VTHd+O/n+68kYlPOWOjGERyaPVkRdsc6cPvKhUxCgKSWYg64jU+1ypwdf8b8JkA9myUPS0rss3LWyMExBs8jkrAAX0I3D+CTrv631uU6M2MKmhBU0BcXCWNTbvqiBoAGSwmW0dzB1P+C/k=
  template:
    metadata:
      name: keycloak-hubble-client-secret
      namespace: keycloak
