---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-kubectl-client-secret
  namespace: keycloak
spec:
  encryptedData:
    clientSecret: AgAKMAa1lI4MNv4NafROqNDRZIeZM6aFo9Lr908Y5yTZR1iByYQCVY0eVglImuebRlzOuC8EvmgCBJvHdHaW6EMo8sOpAfNVZyHw5fg8Ym6HU/tPARLz0/I12gqLT+3nyBzESBSL1ZTT3nCpwr03hnQmAWzTGhDLDIWyLyIxoH0VzwBj2/xpnHkWVQGMhuuClk5jUSOmNRKty5OO/LkJlL99UwXRpvgnug5xv29wXhwXNklCMGkCLocrsjZKJMmBC6hmCIKC6DvVP18YzgKrIcrXjKYvM7E1HXLDk4TuXhuq8CwT1e6UCQSzGg8wyLkaoVR68BCvGDHQ2VpkKM0vOuUZqV4RyXE96+GGzydnzR6/WXXw90Mj0+9wCzmqBdr0XXjnmtbT0VI9OuOQtlgXUY+B//y+3j8MgphZEvkZR8ax4NRkB1i8tuKRRiqaEj49aUd8SgauDQdQdWldmBLCj7L1GqdIT+TN2W8RfIP3T7Dl8YIzyoKoKwrlJJW824eJGjEvqphS83PmfdL5jFVf/rwRTVJrskx9oWOcWGEq/fJJ3ESpk9SItaMxGlkGMgzYFk+45Xj357hTra7Zb5cNPC1x7LV2jhN83vCw4yrBgTnzcYDeZAM5uCHdT4FXud1srzvQSeZSfNpP5yS5iOWb19WPDpGN2kzwD0LxTAAXSDoEjzP9lbKnUSpBnDC6tnLl/ujYJ9PbKaEX4T7qN+j3F9b0sld2cCsXWo8fVz0ogwRDWg==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-kubectl-client-secret
      namespace: keycloak
