---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-kubectl-client-secret
  namespace: keycloak
spec:
  encryptedData:
    clientSecret: AgCtUbC6werzII4isiksbC8ch0HyI005/BKn2R8CZxbYdm7+PhpdZtYYpAANhRetgg4nMCWMtC+Odwz1U4puQmJ/c6ry8V8W3vEDYgNAsMinGGv6q1X6oxZTSe8Mh9BeJS/Bw4OP8X0rh488oklEB5Zucnd6anQdi4nKZppvECTSVLmvXuZ3MDojk5fiqb5/73n3xbwr69aUOJL3jJcvhDDrYZX4ry5/DGBWuYtTEwiTblMbj0ZcuJTFWTo4kAut3YvU5MAwmSHp7QlWaUOf2yujV/0rv/TOiuQmQuVb/987G5Vx1oj0UyQO1zlx3PZ1vbifOu8ymVDyaTF41sepm51qEuG48h46YrxrqPwQBXOy53pd1z+kxb8H1mIK7aPFW5wnB1I8w3UQ6DRFzVzCU9Cs2U0VlSQbfMWLGEi+T4bFGVAdqEGf/f5eivkkLjtj6cOrRDIh7BTDzaqr/Xp6zommRSK7q/YG62TiTigJYxdliLJFLPozZIvypAWmvrDVrz3hBPhpN4O/Y/bhTcvYt6tggW4Qe+Em3eElahiOtfq5/I0+vJrHMQ+5m4EnxWqkvLe6AQG3U+4qPW1LJjpaDL5DkjyheZYhZIx3LxMPaXPXNA8XgtmKj0Q2qQ8D92ThqhYMldER1/CSrNy46GaymtB6+clMUiaTm0akhrwt1dhRx7qaDv9zjGcz5kUO7ZiEKPZndvKIYjc8+qRsWYrRSkMnJLFv/BFnolRwzDBjkcsJzw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-kubectl-client-secret
      namespace: keycloak
