apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-ldap-ca
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: keycloak-ldap-ca
  commonName: keycloak-ldap-ca
  usages:
    - client auth
  issuerRef:
    name: homelab-internal-ca
    kind: ClusterIssuer
