#
#
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: oidc-provider
    app.kubernetes.io/part-of: platform-identity
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: keycloak
