---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-realm-export-client-secret
  namespace: keycloak
spec:
  encryptedData:
    clientSecret: AgDIhhB9rie8ItsLMILeAV9sJKzuLnCA7mj18APFh3GzbmcjtFEtfufyGaD06opSNxswRxJ1a6gTCvgAhRTrBUkM9ZsX8a36luNbxP+GRO9Lo4TymAFymgeM4MjKKQYgtBusi+plIYv+Z1m0/mgBkxvnWCdpV++J9P30es/eX49uliwdc+R0uc1lgosQi9Dk9qyeWxa+hBP8udtVpQ/O+izCQHWP4g6kixDzP6pVLCNNDSiJsJEVQeuk/UFtl0fo+XnriXXhwBzCupaE/VwH0ultKldv1O/v9oyIuWSgZo2Q+ALnZWvkq4wQr7be++CT1YTLmfyFmau+OfBg2BoABmfzzOHThiWo7Vt2DbiNo7QD85WBLO1MhVRd8tk7OE4Hwi5UjJUZIgripLXuMYtdqB8DIaqhCjpo39JPh29SdlwLB7uWcaGjUJ5x5Rb//l2OIJ9Om5o9FLnwRi1knzGqP34DznRplSugv9CMlsrJkZoJ3aalJAPnB+oB3WazWo5hTPz1USzIai8J7WEWQ9AlcGy4PpnPGoitYaUCSTAaV+fB8FnS0vtnPrxbqpGu/IjnIUaAAwMVyATiouzKKQtrYxV77ZJA+BLUpdmeO/Ywp9w35Ag9GtFBalsKrECf+/dmku9l+G9kcR+NnpbURzASm4H8mUm22/KHPC4ZXMNLC6jY8EghtBRQhWo7V5wFFJUv8WN3qj3uyD4mZ3s2KHjxcg9qT0Dt7YTHJbdgg8ij/qkiKz5RJA12T9C0oFmGIL8dXyWIFVb1CGzRkN4QPgZOj2Kr
  template:
    metadata:
      name: keycloak-realm-export-client-secret
      namespace: keycloak
