apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: argocd
spec:
  syncWindows:
    - kind: deny
      schedule: '0 2 * * *'
      duration: 3h
      timeZone: Europe/Berlin
      applications:
        - '*'
      manualSync: true
  sourceRepos:
    - 'https://github.com/Tim275/talos-homelab'
  destinations:
    - namespace: 'kube-system'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: snapshot.storage.k8s.io
      kind: '*'
  orphanedResources:
    warn: true
    ignore:
      - kind: Secret
        name: sh.helm.release.v1.*
      - kind: ConfigMap
        name: sh.helm.release.v1.*
      - kind: ConfigMap
        name: kube-root-ca.crt
      - kind: ConfigMap
        name: istio-ca-root-cert
      - kind: ConfigMap
        name: istio-ca-crl
      - kind: ServiceAccount
        name: default
