apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - disallow-latest-tag.yaml          # Enforce: no :latest tags
  - require-resource-limits.yaml      # Audit: report missing CPU/mem limits
  - require-resource-requests.yaml    # Audit: report missing CPU/mem requests
  - require-run-as-non-root.yaml      # Audit: no root containers
  - restrict-image-registries.yaml    # Audit: trusted registries only
