apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - disallow-latest-tag.yaml
  - disallow-privileged.yaml
  - require-resource-limits.yaml
  - require-resource-requests.yaml
  - require-run-as-non-root.yaml
  - restrict-image-registries.yaml
