apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: external-connectivity
  namespace: monitoring
spec:
  jobName: blackbox-external
  module: http_2xx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://1.1.1.1
        - https://8.8.8.8
        - https://github.com
        - https://cloudflare.com
      labels:
        env: external
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: external-dns
  namespace: monitoring
spec:
  jobName: blackbox-dns
  module: dns_external
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - 1.1.1.1:53
        - 8.8.8.8:53
        - 192.168.0.1:53
      labels:
        env: external
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: homelab-public-services
  namespace: monitoring
spec:
  jobName: blackbox-homelab
  module: http_2xx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://argocd.timourhomelab.org
        - https://grafana.timourhomelab.org
        - https://drova.timourhomelab.org
        - https://iam.timourhomelab.org
      labels:
        env: prod
        type: public
