apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: api-gateway-strict
  namespace: drova
spec:
  selector:
    matchLabels:
      app: api-gateway
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: chat-service-strict
  namespace: drova
spec:
  selector:
    matchLabels:
      app: chat-service
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: driver-service-strict
  namespace: drova
spec:
  selector:
    matchLabels:
      app: driver-service
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: payment-service-strict
  namespace: drova
spec:
  selector:
    matchLabels:
      app: payment-service
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: trip-service-strict
  namespace: drova
spec:
  selector:
    matchLabels:
      app: trip-service
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: user-service-strict
  namespace: drova
spec:
  selector:
    matchLabels:
      app: user-service
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: frontend-strict
  namespace: drova
spec:
  selector:
    matchLabels:
      app: frontend
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: schema-registry-strict
  namespace: drova
spec:
  selector:
    matchLabels:
      app: schema-registry
  mtls:
    mode: STRICT
