---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: user-service-smtp-egress
  namespace: drova
spec:
  endpointSelector:
    matchLabels:
      app: user-service
  egress:
    - toFQDNs:
        - matchName: smtp-relay.brevo.com
      toPorts:
        - ports:
            - { port: "587", protocol: TCP }
