---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBuJ4uq4RQi8qW763gC2y0fodlxktijPMX7Qno1xjZkHh5OT4KU8qvTzgQ/aWWuWiAUbCA4rC871yg+zxMpJtkBtnmYU4cB/fn1Y8yS8JzspTMbJUkdhEUJqxOT5tTPCj2ZWSkGG7E8KU83LWY30B1CP3z9zHX9LoIu0G1l+pXoCQtQjlGGrupygt6Emp7Y5QXoTB6InjRHI6BNr/F+TmJS5jMzBoVNvYKHVCF4hXzVjva8w5hdUlx86EATr8lK4ISP8nhpx2gxHLDRbpq3RaNacLT8J/nY2qaLckcaQbzZv9FHvhrCio0Q9e/TXl1CthIoAi7t7D6pVZjm2PnAzjQVtwnHv2RykM6qbJn6MEhwffJByCr8Bi+9TZ6nshcz2yuyjGEyO0QVA9yZcg5kiEwGx5h2nl6EXFQ2AxwVQAzZPUyl1WSM941vWjzT7LnFFZyN1hT1S+cMpMJqax1bTrdFfoB+Cc/txFCXSK/ki1trmsThK0Vwma5DFnHQRdOjv6K37Augotmlu8UlAuU+SHfTXN2cOkjoNaXgUsTTvOnMmIv5W4yiHOdWIcyBYJawWfBZqxJVx7OkhQMYl6SO1lhtbWDGw1ug7xLnDzmHM115eOk/zUGYwA+kQe5bboIlityRqrrhrggPnep2cfj2c/9bV8gWe8HFlexrmD0ONsCwIDIbUZYEtlMgaJ+wLgmG3eJIqpF9deOt+0HdtDbAFRw8astCLO0FXuMB4guhzLAJMEBHX8br4WUeUOg9jPYG7qWpmpzs0zoQ8Fqzzy8sk23i7k6H/wR6DjxlmzXQYudU/dd7U/z5XcHpoUDHLnbQcKpQkFVrNmAaXsXoNjbvisai
  template:
    metadata:
      creationTimestamp: null
      name: velero-s3-credentials
      namespace: velero
