---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-restic-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgC0mVfiCZuaLULG8JQTlnIqnlwOg+aoQmXcHsxWO0UYei/uogstrDcBto3YioSrhnGAf/HmmKj1ITjlnmNiuHM2IfK/b3HEM7RiVFwXvPCPGug1KPtDPGA1qM8G7eSnRVHKxtGakxWTxNzMb9HX25fV3b9NKfvXLYvPm6gUZUJ5oLnLHlI4IUG4+iXc13O4WKbohmBhPfqbeli0qDXmTt4gAoBSBgFRbS1lLNcSa5/GFaNgsE99LkzP+q+GSA2x/sT+XAVFputHp1Dw2XGzD+UoV4WqPbSqZ3hVD8UuSfcY3Ua3/J3vZsJ5xKCs1adI7Hoe1Q+/DY/qhJWAYiiQ2um4/ucUz/8AbFz0ahr3Agk55ftDXd8/Qg/E8ZTFcIVlF77CBD/T0BdV2yaD8txlqBTIUcaWufWPKmn3YiLJzWe59cIoqd5xsRtJU9Ou4/J2UsyY77pZ7zcvy4uHU4nQmWVMePB5fRzE15KyHBFe2fn14+NCAJdvdkBQz4zB9u64Ft1r/NNR8pGWrwEmnrq0MJ7+krwfrzMIvLEq4CyP0VfJm/ZZao0AiamU9La8QzuTU1HTzpRi6bFkEz25b44pvRbT+ChuBtrwwW5u44RmdZ0Hm4ZRixV7roQR8hinmotasQg0LSxZXCjr/Q98WYiGB6poLLBoY8+TE9j81OZwdyClykKX6LofMiT3hdPjGM6nR7aa8JRUPWVtOxSKbdEmYAjBhVIovXQY2UpzPYiQk1KNWWoeyWQ=
  template:
    metadata:
      name: velero-restic-credentials
      namespace: velero
    type: Opaque
