---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCAH1vCoS8l7ED64b/Y6C3PtMerfk64vTNwlkEWPgEJO8Qg327+D3P+SXOu8PDrCb9mSQtVfhB3bYE7ZyEIkJkJqAorlyeO/9NVz87mJzlSRryghpTbQHoUGyVRVC1zcgNA/iehPO7r9g1B31t5Ub/1BqCJRx3xtb4bF4ASCBy/Hi8XDij/Lq5RYzOeCWNMHSTKuMkSCYkmnliV7XHhN6hLaUspJxC3DbvHlCjfFdoEfTm3hsAfWg2mx11143LP1SJapssQWhiHo2VqGdvoY3Hiz3AE5cn1Q0GazWx3C32Kj63XCW3vYoam43tn87aVCtL3OmNpMiZQ8sBIC4koYoWdkl1BpYplhGMwRH/vgyGvw+90OtuMdK9jUB2flqDIXXLSTpGVyzSikEOnLqCDcfCx4H/HHEcYZL54KpgXNEvrZo3fmVEodQcbEvycda/nqXISH83fbO432sNvjVkGLGMYKYcP9zszdnv8xkOHWYCtq1pcAPAASmGTNkkVY2QfuLDu6ab9A3hrJiERt63AQwBIIxArBJCAbChaAXyKftPXdS3KsAN8B+PZ+eeHNAMALQCguh2FNudvDKt0/7cRFWdoIAUmvt9UgmslseKTIRstCV8CcQ0QHsbQuh2Guq4eVkjandqJtNd4ncFC1I0pmkBiDPxGR4kW47o8OxvTRMQ+ymhBZMB4CUAFMWR4iL9QxsxOXdj8mHsvWdHalRAdGSw6Q1qNRdOmxy+Pn5Em7bClQN3shjfgmuTaipV0+cQf2/UF4pMjIc9rRI58IllnZHv23BGF18C/ZH8e/IYJf1vmONIWFxpR30XUohzH/KDKDojuIF5ylEFT3EmpOdWooSFJX42Beg==
  template:
    metadata:
      name: velero-s3-credentials
      namespace: velero
