
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBIkNrF1zgQ6b0We6GoehZA/JCJt7pHJb6RfgThTdrXyUTwuFzPYqLQu7n5gwkNDnH/w22u/EFGkdDF+a2o0u2id5r/Lps8ZF80/YTAka96m7lWt2aY3CLuWfZainbLiv51F9WAXVL+laBQk/3RbvZhm9tx9uuTrWd2LL3xyKirDl4JfBhR0NqlWWzAuw7mCri21m6v/9/wdaunSMmVr72DUPQ4/EiCfBgn6wjSha13iX29dDJxWCOUNjG+92LbFIFES5hibcCgrNq8M+7n4K2LQzLXylHR9TI4/Rymw5wIrya7p17q4ine83cTNj1FeSC3FJfFcvbZAM7QJm8TA7rhgNsLNl9D8n/PI8KqV/BmPRKXhpzNBStwfaWNdn/LZMEV6M3L9UcQrGgW3JZBePbm7nrOWRmpE0OoPCIAYBo91Dld8gn1U1ZT9rXboCOunLBjbX9HLggMiY0L/6Ow8uVEczm8VsFDobObAtVpenihxuptseoLiYLq/5EceB2HmrcanDiLaAyqqmD3RS4uNEYvoUwCpRUhBl17/nzCTZVvNRt3BEnD0uXGM0WqIHldwurYOHYhXa4Gwmrr1NteqAJhGd9NNm1ACrCoHJRve1Qp4/JWYN/KJXvvB9gVJWoLHplFf+71/cK5oNARrCxf74hAwW/L1MW5wvhjfMauSV/lGygvD4ddI+TpOyVACVQTiCkposAhN6Hg8NtJH1QhgK7wbNoHCindV8r5RixSHjmAHFNZWike4W047NM6vKYXokB3aNbmjZxbdXOQwPWBGerQxfuTiSiWIgRMbr8bD8YZUmXP05GsPNiKg2V+ZnAniz9JpdQ7bV5mJsCLwKS86hiuLjFUm8tDNeJ+HEJ1oWoQ49Brl+9L2DtvKjztruKWukspgLD4e1NGoN1mTTFVOq0t0w==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: cloudflared
