apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: cnpg-backstage-backup
  namespace: backstage
spec:
  bucketName: cnpg-backstage-backup
  storageClassName: rook-ceph-bucket
  additionalConfig:
    bucketLifecycle: '[{"ID":"expire","Status":"Enabled","Expiration":{"Days":90}}]'
