apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage

commonAnnotations:
  argocd.argoproj.io/sync-wave: "15"

resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - backup-obc.yaml
  - barman-object-store.yaml
  - scheduled-backup.yaml
  - app-config.yaml
  - httproute.yaml
  - networkpolicy.yaml
  # Sealed-secrets — siehe SETUP.md, Phase 2
  # - backstage-db-credentials-sealed.yaml
  # - backstage-oidc-credentials-sealed.yaml
  # - backstage-github-token-sealed.yaml

helmCharts:
  - name: backstage
    repo: https://backstage.github.io/charts
    version: 2.7.0
    releaseName: backstage
    namespace: backstage
    valuesFile: values.yaml
