apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf-prod

resources:
  - ../../base
  - namespace.yaml
  - pvc.yaml
  - httproute.yaml

commonLabels:
  app.kubernetes.io/name: audiobookshelf
  environment: production
  team: timour

commonAnnotations:
  argocd.argoproj.io/sync-wave: "60"

patches:
  - path: backup-patch.yaml
    target:
      kind: Deployment
      name: audiobookshelf
