apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drova

resources:
  # Infrastructure
  - redis-config.yaml
  - sealed-secret-redis.yaml
  - redis.yaml
  - sealed-secret-pg-app-creds.yaml
  - postgres-cluster.yaml

  # App Secrets
  - sealed-secret-app.yaml
  - sealed-secret-pg-users-creds.yaml
  - sealed-secret-pg-trips-creds.yaml
  - sealed-secret-pg-payments-creds.yaml
  - sealed-secret-pg-drivers-creds.yaml

  # Configuration
  - app-config.yaml

  # Services
  - services/api-gateway.yaml
  - services/user-service.yaml
  - services/trip-service.yaml
  - services/driver-service.yaml
  - services/payment-service.yaml
  - services/chat-service.yaml

  # Ingress
  - httproute.yaml

images:
  - name: ghcr.io/tim275/drova/api-gateway
    newTag: v0.9.0
  - name: ghcr.io/tim275/drova/user-service
    newTag: v0.9.0
  - name: ghcr.io/tim275/drova/trip-service
    newTag: v0.9.0
  - name: ghcr.io/tim275/drova/driver-service
    newTag: v0.9.0
  - name: ghcr.io/tim275/drova/payment-service
    newTag: v0.9.0
  - name: ghcr.io/tim275/drova/chat-service
    newTag: v0.9.0

commonLabels:
  app.kubernetes.io/name: drova
  app.kubernetes.io/part-of: drova
  environment: production
  team: timour
