---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-pg-trips-creds
  namespace: drova
spec:
  encryptedData:
    DB_URL: AgA9kM+oGj8y205mzAXTFrC6x6rwOBgEj93kI+76wEeMRONkyozRlSi6El6yaDBZz0jxk4nroSDSrInw+KW65SGR4mt7k+E4zPA8PPJ6dKU4xeRD+KG9OVPTcRT0tV8yzIy+akr/jXvFQTI1hXRTuaNVnCztJTZ5qEvs5HX/yicbJDXThknBrj0OXl+LAYkVbGifE3p/HUIGfCIzMhhT/kmb4thWy5WcSJ2/BR31A5TdcKl2INsKyGwrWEQvhpxBrX/Mlvio5WCgWNntOrWMlusRrakGdz9P/YP/cqeeaGqvsTNtjiwicFnkUaAv1PEU+F/ulC9Q2Li8CNSR2EXyff5nJLG+g98mCkNv38jdprs1sOkeBh4fmIgFMcxbps8eBVdUSN5E1Z96Ivc5JUChNNcRjF4R0t2x5rH9x/M1s33gETBvrZyNCPRRUoBZ5qN0NnCp8TrOt/ClLmefwQAlhagDXurODlWKI1AWWGHPs2hThTyXM1BNSbMGoYftDxGWPTak29Gd4uK4bWRUDTqdmcYnH9TnmGkdaVjqx7dJVbwkTqrZhvNYCd9d7ohY0mBlPBj+hHDmAZ1qBdl49JqgeQRTj2KUARO0vOK4s8nOhL2l7f2WjdbucFhCAHDtCJqJVLoeZmj/UrkTP6wLCrCn2oHWxnuQsdf/4jQOA/hn9zO4HMnwUSBv0WV3L0zamlts5XpA98t/LrmlYOZxnpNTQmgZ1WuRDky8qCxqcAWGotIWlxTjQn8KUcojahha8COTEqAKV3Ew0l5MPhpLHiS5gtcyZMj0XqCVYYGVcjlAN7XE5LOIerjkq82rwtbzlzh5lNHpQgoyqUIo39bvRiy0/tk8/ry9s08wVgEtJ9sDkD+RE8BtYwWN9dn9lnP8rB5w9slOonDlAivaig7vdNNAKUJg
  template:
    metadata:
      name: drova-pg-trips-creds
      namespace: drova
