---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-pg-payments-creds
  namespace: drova
spec:
  encryptedData:
    DB_URL: AgCvsCmjGD1bpYwnm5JWQoUyCcWWknfh7/A7QPzfUQyMpntW5GsM5VvnnmNmYp/cT44E/H4zBOrRjpYfX/k910QkDoQEVScQsG1azIwJ6EcK/Sc9SjiVrHrfPcffx4ChO9rVAZtIqibCnGPmpzqVnQELL7JZqsNJMJzsX5UJCgfunTkcYX0E44bWaxhU0W3LLeaW8rBsoH8dDyTo/eYOX1EyiAIHZmvwmMZ8vf9C8aD9mmdioHLwNRaHj++IrdavmVF02gK9G2f6Y3GorhJiFf7s/SspNma6Qw38Ouog/BcmAydTxeXP3x7ywYhH67Oad1tBOa7zlpZVpkld5P281eKhzShVRhEx5DXhKZJ4VOZ5pVevCm/tQbpQ5ErU3th7jWvokgtBpMRdr2WJibMU3194brGARo++Nt/ceiEfXt65CElv1CuWL68VvCN4/cDFq6JUuCs9gOwXIaXWoL+Y14QVaQVlYZJTG9ciVIo6tz5osLLbV7ydqYJA/2bkYzhuXbNVxnVzy6i0iN0BkHbFx3oq6bTtvYLpyo/lIIzpmELJEtPk/JZMbvLxaLK5fQnySS1BHLbnPvd/DfAi7L8HymEF05DdlFmkMfLqmsLyub3zxozefCDRjp086zPLSVmpYJtjHIWKknGX1Sq8O9Q39PhL5uS2N6wZ8vrnHqDP9DXNkeFg3gbaXzMUSnW9L44+OXko4SYpKqwbc2SkWr3iUBcOBiXHeuymcwxNjKsCuxtvo2aimbIWtvAcP3VF05em4Bs2QuBp9LujlwCgtmW33tdtZz9qMeTlw3CTrbF02FazsltMntmUcW5zz+qpDX3L1uwjYc92I7Wz9LXBRTIS5IMiInWXGeUoU9UeN6JKLRmirWgOsLeEVTu7WbsxBo7K6TR9PTC275cqD4XOJwRyvq80C5U0fIQA
  template:
    metadata:
      name: drova-pg-payments-creds
      namespace: drova
