---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-pg-drivers-creds
  namespace: drova
spec:
  encryptedData:
    DB_URL: AgAqOkGYgfW2IbVSJW8rI19/YLGM96nlfRqdSPVjWcOdy/2+Q4Ne63Lqv2iyJraMYn5jTqmn8Sw7iFgf4I0TL8AWbDt2S4EpFUMG0v4KMpLPSVl7N25p9lN44GxghfMVh5K6hTiIv3WgXpwgaiySYY36SmhQ24bJhR6ijid5sADA7g9pxlOFrLjDobqUEiycBQreQoEUzUImI2+jUgoqlRr5LOLiYBHBH0GY4N7uZUc4JE/+TLEcf/0KtP6/c8T6ABEGcFr5FT1RZX6AFKk8xJBBwwbWF/Ljtk3vmEPnw2geJPTcD54AUwMddlC9Uoq4jcTJlJEDeV9GRwKjchn8NYHZSITMHQ6FDUjfw4wOfuze3GDqFM01yqTAGkZV+0eV0DQ0kfay9uxlImF5pMuzwZDucykv5AROQhSBiz3WzxWgR1kigEwbwUs35SVgPIfKBbdtk254Kige/06FH3KJqd1nPbq2aT4mKawn4GmBt70rEVSsbIcPNLnoQcrEXQZkD4hm7N+oVUhPAfwNZai395s8DPBwFpA2P5Vaf4oebUc5uqLYjeQRKJkZyivlOlKzznwfpeRmPKLc3Uoq1ynfH3vDFD02Jro4BKWLfk2rfLihxKHPaIb7kgP4cZEd7sgwLV0v9qXmIv7XVJ/ALpTMbiUOSXI6aejHCdA2XTAyBf/B152AfcRA0EEDZr7jWC8rQuBxO+cmtJI/a2j+vUv8nsUFebKtt3QCyksvqsGiOBMiNDisiYpZxDTqqVYSuURJ/jntge25lkm910LTy4a7BWisFnWQvvZIrauRTKStLxqjFXszVLTeXTDsA5fRCxYm/SPY7CVtUv0iL33KCm7m
  template:
    metadata:
      name: drova-pg-drivers-creds
      namespace: drova
