---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: drova-pg-users-creds
  namespace: drova
spec:
  encryptedData:
    DB_URL: AgDAbxAcdsMHBov3i2fA7v1Lc5shaJhoAkBrOfCxZWVOWOmir2NmiAl0Tvo93ikA44i7fQ4GzV6ymRo69p+vYWPfktqPdonr8UVqAN+BNUqfCq0xZwwz3610virpY0+7KbSoIOX6rt22qwb4dAQSxGHFp7RnX1oYVn00Yer7FPeya5xEhH7JMgWqqGRFjJuOvyUsSdWuU7rVffrVUaNkxBqsJYBFIrxeFYy9MuOu5weDcz4FeR/Q0123Onp/ulzhOrW4E8/UioY5ifwAI/YXfKpsrVzdX9d3itExXJt9ziQlGCqVqG3LSxGNBpWi5kFbji4iOLooFTeKWSS2sVoeVHgZKlSFxxPOj4D/4ZxtDLLzzuQQoCJz8gw7IU8sIi829dPr0qAiJruu/sYkcgFM+9L+yv17/0RegBG3eP87m0TiHry3ZWXw3MZjCoeekiDxAHjqo5wZ6jST9on0fOGMcfduxKygh7pDJaZzotrMz5asWKqpkDhpgOFpOCQYW/E0YEh1q1nJJNMqUc0PbBOEDT9zQ9vI4I2mAv6KQ+88sNW0V9CejFfU2HzPcZLKIh2XAcZaOkgpEN2zSIr/ThIH9jad/CnB+ujJ6zfiYYGHmx534oP4S8aUGHYign7+YsJbhIfBzv3NITC3128cqfxdJ4yzULjjYNa8/D0s04kUPfRIoXwNCBIV8aR4RIwUJrCddquG6ZDRUCYT9vapaE2lIJKdj2ZIO6NDBRkcy3fKtHjdLS0WALsCfmSHNB+NgGkEzP2U4iwEm5OITtr775ZLHATqX6G229ZihhsyaNWDUApW0k+J2GXvE20yaRv6zIpgxqBRl7cqQ+BgK9NxwlJSKJfXavCEiTHDExcmNJJEflTgoCBCHp5+4pcCvit31fzC6F/E+BmsarIiJA4FIR5jw8eN
  template:
    metadata:
      name: drova-pg-users-creds
      namespace: drova
