apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster-rbac.yaml
  - crds/040-Crd-kafka.yaml
  - crds/041-Crd-kafkaconnect.yaml
  - crds/042-Crd-strimzipodset.yaml
  - crds/043-Crd-kafkatopic.yaml
  - crds/044-Crd-kafkauser.yaml
  - crds/045-Crd-kafkanodepool.yaml
  - crds/046-Crd-kafkabridge.yaml
  - crds/047-Crd-kafkaconnector.yaml
  - crds/048-Crd-kafkamirrormaker2.yaml
  - crds/049-Crd-kafkarebalance.yaml

helmCharts:
  - name: strimzi-kafka-operator
    repo: https://strimzi.io/charts
    version: "1.1.0"
    releaseName: strimzi-kafka-operator
    namespace: kafka
    includeCRDs: false
    valuesInline:
      resources:
        limits:
          cpu: "1"
          memory: 768Mi
        requests:
          cpu: 200m
          memory: 512Mi

patches:
  - target:
      kind: Deployment
      name: strimzi-cluster-operator
      namespace: kafka
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0
        value:
          name: STRIMZI_NAMESPACE
          value: "*"
