apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster-rbac.yaml

helmCharts:
  - name: strimzi-kafka-operator
    repo: https://strimzi.io/charts
    version: "1.1.0"
    releaseName: strimzi-kafka-operator
    namespace: kafka
    includeCRDs: true
    valuesInline:
      resources:
        limits:
          cpu: "1"
          memory: 768Mi
        requests:
          cpu: 200m
          memory: 512Mi

patches:
  - target:
      kind: Deployment
      name: strimzi-cluster-operator
      namespace: kafka
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0
        value:
          name: STRIMZI_NAMESPACE
          value: "*"
  - target: {kind: CustomResourceDefinition, name: kafkabridges.kafka.strimzi.io}
    patch: &retain-v1beta2 |-
      - op: add
        path: /spec/versions/-
        value: {name: v1beta2, served: true, storage: false}
  - target: {kind: CustomResourceDefinition, name: kafkaconnectors.kafka.strimzi.io}
    patch: *retain-v1beta2
  - target: {kind: CustomResourceDefinition, name: kafkaconnects.kafka.strimzi.io}
    patch: *retain-v1beta2
  - target: {kind: CustomResourceDefinition, name: kafkamirrormaker2s.kafka.strimzi.io}
    patch: *retain-v1beta2
  - target: {kind: CustomResourceDefinition, name: kafkanodepools.kafka.strimzi.io}
    patch: *retain-v1beta2
  - target: {kind: CustomResourceDefinition, name: kafkarebalances.kafka.strimzi.io}
    patch: *retain-v1beta2
  - target: {kind: CustomResourceDefinition, name: kafkas.kafka.strimzi.io}
    patch: *retain-v1beta2
  - target: {kind: CustomResourceDefinition, name: kafkatopics.kafka.strimzi.io}
    patch: *retain-v1beta2
  - target: {kind: CustomResourceDefinition, name: kafkausers.kafka.strimzi.io}
    patch: *retain-v1beta2
  - target: {kind: CustomResourceDefinition, name: strimzipodsets.core.strimzi.io}
    patch: *retain-v1beta2
