apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: strimzi-kafka
    app.kubernetes.io/component: operator
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
