---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bgp-auth-secret
  namespace: kube-system
spec:
  encryptedData:
    password: AgDjimqGVLpS0e5UfdpXlR0fWyM3X+VbHa3es3cN/ExyTygsXLm3d9U1txf4VoiCSo4vRnDDC+Nkx5KfRnU1JcRbsKMlcyHm7uxdYjC+TGKdfghwejeId2ybJWVmES/opCI0959NfRKcTOPb30TkiGcctcQUVfLxywg6rtgjEFOdRzrQ3jvOaeziKRtcUUx5TN68sOMnzAMVsisuToERbX+BTroReaYmu9DmsaXa9GdH6J2rHMm8A5GtoQzxaPpcoNVbeff7/WGvSW6nsKocbAY9LrtoN6Px+MjnludLnqbgLONp/FhKrPTvNnetqyqw1sR9c+5VIgabcUyBnZSgM/Zp0LvJAA/QfR/8Ykui7jBQHRyqzeEDwvp7ShZ3VS3gDAoSUvq3wUA6z4g5tucuX+fEUOL7M8CMoNPg6W2Kn7sT4DYb7vQRlMOvXMpPhIVxIBlnv8yQWbax+PDQHQxA+qI3P8qh5vge5quPvLz0C5/5ENi+jj4oSl9pEd4vUHSL88pgRvKxCtqtig6DIS+PYkcc3Vcwv83yhYxVbCJ7Nj53jDrB0C2AmFG/GnlqepBxloso7tuDQd6B/KZZB5bqIL8qxNRo4ymh0f3OFCRFeyaAsklouioE5n0DexeJejbe6R3IkcCeIMc9bB4SRkVp2LLTKb0ZMh9S2iX9ilFmmLwwM23nkmPunnlczUCCH08yGuJt3e5pdDT8o1O+VfSvCHj0JujD37SrMRhndnRKBl/nGA==
  template:
    metadata:
      name: bgp-auth-secret
      namespace: kube-system
