---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bgp-auth-secret
  namespace: kube-system
spec:
  encryptedData:
    password: AgBKvC7N8aOuj3EFvxgSKf1gHPsgzViE8SBjyCDtmA137hDHm2eGONSzEh2feBhYT0HzqPS1dLiokVuFgDUTYBExfH0R9NOxBALCVhqag6tloLsIRIn8LFKWNTSD02HoOSW7FWVV/fnC2nB49c698sZYX92LQyzOEIf12Z+OMOQBHFt6bvgOu0c2aDG0ezmCyxU7zjLWeWMppHTKWqUTul84k1Kdi+tZ1nYkuRXdk7akfR0MdvPyvYoH6USga8y5lv41C/esir+r3AIPU+UtQMFGs+ha9Nj8nCGmxktklroyT+jH40EUWoG9fJVQ6s3jPaGV5T3wwELHwpKeiq62CuPp+KNNuU4VVBCBQWs5pH/HyfEe+IE/E3L3Pjdyqz5SGiRXJArlhdC9t01MHtgoJPrAwVCwYa2R9Xkw4J2uvRR9uSxYl7Av7neeKWtSDgYmQqL6E6GJ9/X2224bs+ay+hu1WhA5/JftJ2v0mghPoqdOzWT8DVk/ikjbC31dkVvyCZJJAhvJRsr+YWjm6jja0OmeehXNjkfg05+D54sBknK2VC1B1p/hrJS4vmbPrIzF/M6ab3GGPthZnDmqkaNmSp/etsFWaa+i+wnEWg34Uz8KRJ9hcOzmWQhU7rBXDwflpaZbMKK6WoTumbtSfeyyle+9abTy4696dkHg1QCWTYobzC2xV/jQUjflrl5cS6QI2R4D2kitmLbk+9YSWrksQ5gJsUN2Xkbv14bn643ho+LgAQ==
  template:
    metadata:
      name: bgp-auth-secret
      namespace: kube-system
