apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: drova-kafka-broker-metrics
  namespace: drova
  labels:
    app.kubernetes.io/name: drova-kafka-broker-podmonitor
    app.kubernetes.io/part-of: prometheus-operator
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - drova
  selector:
    matchLabels:
      strimzi.io/cluster: drova-kafka
      strimzi.io/kind: Kafka
  podMetricsEndpoints:
    - port: tcp-prometheus
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
