---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-basic-auth
  namespace: renovate-operator
spec:
  encryptedData:
    .htpasswd: AgAuhqLnaPY1dCZPLi2WnU2KpCz4yVFH7fUd7gsxNWg425AtH2bpQaw4DdXXTXAwi8r4fOyd5cm1a/gMcASFwWbbClS0WmeS32Gq26GpXwSS7v1UDhig8ClUlUZLfprkCROA3LDC8BHi3W1oWM/z74lSYXgsyVU/r8x5F2xVse55PL1klu3dk6AhRjgZg0ukdfQeahRO/ys5REtOP6UKg/MLzx+Z+hLaxjJNNtZxmPFVxAX4lEwn8wQTPUYBfpaLdvd1L2UaWsxiv05J3NN08S0QlKz8hjFN/FWUBZLKxJFU7fc71HO+SvPaB/cb+mMlfoAZukUphiHnlLI0OJpOs6el1cf/M5phILZ2L7QHhAHEHDtS1POCMPinXG2nhj8m/p8WVXzswsGxrTZnnswvvCiDZZxRO9PnfqYwSNAEeOKiTcBkB/Wvqj4oFm3uw84OwE/RmiQ7mxjirXCQaS+OPDl4qmJG79TaMWEwteVAwZYbHdX9xBejMdwE0XI7rUHuqNDiC4n3Zv2AIUCCdr95inluZ/8vBsdEfwShMGbgvfz4RuV0yzvo4FgseZ3UwgvHKg86HSwohOSjz4SmU/gkzj/KapLNyNun4HliuiCx3uwX9vm7ZrpQsrRbASxdxn25o9KVAChc75Z5Y89YEe8NK+6Rb+rdSY3/IccbAvbGQpQtEHEOX2Q/HpRPoVtMlAYgKj0=
  template:
    metadata:
      name: renovate-basic-auth
      namespace: renovate-operator
