apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - alerts
  - servicemonitors/servicemonitor-grafana.yaml
  - servicemonitors/servicemonitor-grafana-operator.yaml
  - servicemonitors/servicemonitor-cert-manager.yaml
  - servicemonitors/argocd-complete.yaml
  - servicemonitors/servicemonitor-envoy-gateway.yaml
  - servicemonitors/servicemonitor-ceph.yaml
  - servicemonitors/servicemonitor-ceph-exporter.yaml
  - servicemonitors/servicemonitor-elasticsearch-exporter.yaml
  - servicemonitors/servicemonitor-elasticsearch-cluster.yaml
  - servicemonitors/vector-agent.yaml
  - servicemonitors/vector-aggregator.yaml
  - servicemonitors/servicemonitor-vector.yaml
  - servicemonitors/jaeger.yaml
  - servicemonitors/servicemonitor-influxdb.yaml
  - servicemonitors/servicemonitor-opentelemetry-collector.yaml
  - servicemonitors/servicemonitor-kafka-exporter.yaml
  - servicemonitors/servicemonitor-schema-registry.yaml
  - servicemonitors/servicemonitor-rabbitmq.yaml
  - servicemonitors/servicemonitor-kafka-saga.yaml
  - servicemonitors/cnpg-clusters.yaml
  - servicemonitors/servicemonitor-mongodb.yaml
  - servicemonitors/servicemonitor-n8n-dev.yaml
  - servicemonitors/servicemonitor-n8n-prod.yaml
