---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgDg/Hmi3Omzp8f0+vD1sz5Z3HL+Qm44Nqn1j4s4GVNi6zLRplqYkS8xgnYb1B1WTDdAQnFGyV87dcbuMPL02AwhrYoVhOeL3z21LEpp2SBzo5wZUbTBCm9wK6z1g+N1hc7nGT/1BABh8EDc2tfBZIISpFRDvKnh72uqXRR0ELYxLJ4/TtnDyF5oA/JXwvW78vjd6Z/nf9Sio94fxcjzCcFC5hGQoIx8BMzK3An8F+YCyu+vyiRJAZb6ROcA7eW1/Rb3XzT/9a2+sU7ZOcVFOXCBx32jfh5AI8u87pkJ5juHgYH+A9yljcJwPqEhQkAETfrPIkGQcLsyjbTqLsfrnHm4RPWzGlLh1/9hW4F5mS2vGw34ZcK/ppxYclIRa0gbqQef6kkxCIzOu+K7hB9dS8jQ3eBpvV94FI2ddLR7VVMP+uxJBpDvYtx/tXqtPvnSxx3W0nPlFUZCEr3enPxg4GhlhOIhmuQazgKcF8ZBNm3EPty3ggGdkDiYKqknH6Z2rfVQ6r+iMD6JRXGO3J1obOVRQJ+/+Lwamwol6kloI4qHtstRsO88CKgU7ZNMI+nTntqjiilTa82s1NDiabAbuIL43rrrnfEKysbf1yLao/Y7noCUm0lMpoeW18XAZPhNQ8Rr/p8QcTvPEPp/MkbBjaCfaYmhrsBjkUrR2TcBAeZr8xSdo0pyhxPAfSEsmvHQLr1HMYdv7M42LlHjz+S9N5fDw8k6cPEvwR3EWpD46YxUw/HG9MYbigOQ
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
