apiVersion: v1
kind: ResourceQuota
metadata:
  name: keycloak-quota
  namespace: keycloak
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    persistentvolumeclaims: "15"
    services.loadbalancers: "0"
