apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drova

commonAnnotations:
  argocd.argoproj.io/sync-wave: "12"

resources:
  - kafka-cluster.yaml
  - kafka-topics.yaml
  - drova-kafka-user.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: drova
      platform.homelab/tenant: drova
