apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret-sealed-ssh.yaml
  - secret-sealed-github-app.yaml

helmCharts:
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: "0.14.2"
    releaseName: tofu
    namespace: arc-runners
    valuesFile: ./values.yaml
