apiVersion: v1
kind: ResourceQuota
metadata:
  name: infisical-quota
  namespace: infisical
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "0"
