apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
  - backup-schedules.yaml
  - tier0-databases-6h-schedule.yaml
  - keycloak-schedule.yaml
  - worm-weekly-schedule.yaml
  - restore-verify-cronjob.yaml
  - quartal-drill-reminder.yaml
