{
 "title": "Elasticsearch Monitoring based on X-Pack stats",
 "description": "Elasticsearch monitoring based on internal X-Pack statistics - no agent needed",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Cluster_UUID",
    "query": "{\"find\" : \"terms\" , \"field\" : \"cluster_uuid\"}"
   },
   {
    "name": "Node",
    "query": "{\"find\" : \"terms\" , \"field\" : \"source_node.name\", \"query\":\"cluster_uuid:$Cluster_UUID\" }"
   },
   {
    "name": "Index",
    "query": "{\"find\": \"terms\", \"field\": \"index_stats.index\", \"query\":\"cluster_uuid:$Cluster_UUID\"}"
   },
   { "name": "Adhoc_Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Overview",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 2 },
         "type": "raw_document"
        }
       ],
       "query": "cluster_stats AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Indexing Rate /s",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Total - {{term cluster_uuid}}",
       "application": { "filter": "" },
       "bucketAggs": [
        {
         "fake": true,
         "field": "cluster_uuid",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metrics": [
        {
         "field": "indices_stats._all.total.indexing.index_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "options": {
        "showDisabledItems": false
       },
       "query": "cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Primary -  {{term cluster_uuid}}",
       "application": { "filter": "" },
       "bucketAggs": [
        {
         "fake": true,
         "field": "cluster_uuid",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metrics": [
        {
         "field": "indices_stats._all.primaries.indexing.index_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "options": {
        "showDisabledItems": false
       },
       "query": "cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Indexing Latency (needs to be divided by Index rate)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Total - {{term cluster_uuid}}",
       "application": { "filter": "" },
       "bucketAggs": [
        {
         "fake": true,
         "field": "cluster_uuid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metrics": [
        {
         "field": "indices_stats._all.total.indexing.index_time_in_millis",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "4",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "options": {
        "showDisabledItems": false
       },
       "query": "cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Primaries - {{term cluster_uuid}}",
       "application": { "filter": "" },
       "bucketAggs": [
        {
         "fake": true,
         "field": "cluster_uuid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metrics": [
        {
         "field": "indices_stats._all.primaries.indexing.index_time_in_millis",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "4",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "options": {
        "showDisabledItems": false
       },
       "query": "cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Search Rate / s",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Total - {{term cluster_uuid}}",
       "application": { "filter": "" },
       "bucketAggs": [
        {
         "fake": true,
         "field": "cluster_uuid",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metrics": [
        {
         "field": "indices_stats._all.total.search.query_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "options": {
        "showDisabledItems": false
       },
       "query": "cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Primary - {{term cluster_uuid}}",
       "application": { "filter": "" },
       "bucketAggs": [
        {
         "fake": true,
         "field": "cluster_uuid",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metrics": [
        {
         "field": "indices_stats._all.primaries.search.query_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "id": "3",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "options": {
        "showDisabledItems": false
       },
       "query": "cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Search Latency (needs to be divided by Search rate)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Search - {{term cluster_uuid}}",
       "application": { "filter": "" },
       "bucketAggs": [
        {
         "fake": true,
         "field": "cluster_uuid",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metrics": [
        {
         "field": "indices_stats._all.total.search.query_time_in_millis",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "options": {
        "showDisabledItems": false
       },
       "query": "cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Overview",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "source_node.transport_address",
         "id": "8",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "node_stats.node_master",
         "id": "10",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "node_stats.os.cpu.load_average.5m",
         "id": "11",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "node_stats.process.cpu.percent",
         "id": "12",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "node_stats.jvm.mem.heap_used_percent",
         "id": "13",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "node_stats.indices.docs.count",
         "id": "14",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "node_stats.indices.store.size_in_bytes",
         "id": "15",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "node_stats.fs.total.free_in_bytes",
         "id": "16",
         "meta": {},
         "pipelineAgg": "select metric",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "CPU Usage - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.process.cpu.percent",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "CPU Load 1m - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.os.cpu.load_average.1m",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "CPU Load 5m - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.os.cpu.load_average.5m",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "CPU Load 15m- {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.os.cpu.load_average.15m",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Segment Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Total- {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Heap Used - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.jvm.mem.heap_used_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Heap Max - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.jvm.mem.heap_max_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Index Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Lucene Total - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Terms - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.terms_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Points - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.points_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Latency (needs to be divided by Index/Search rate)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Indexing - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.indexing.index_time_in_millis",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Search Query - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.search.query_time_in_millis",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Advances Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Garbage Collection Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Old - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.jvm.gc.collectors.old.collection_count",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Young - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.jvm.gc.collectors.young.collection_count",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": {},
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Garbage Collection Time (ms)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Old - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.jvm.gc.collectors.old.collection_time_in_millis",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Young - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.jvm.gc.collectors.young.collection_time_in_millis",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Cgroup CPU Performanc (ns)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "CGroup Usage - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.os.cgroup.cpuacct.usage_nanos",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "CGroup Usage - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.os.cgroup.cpu.stat.time_throttled_nanos",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Cgroup CFS Stats",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "CGroup # Throttled - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.os.cgroup.cpu.stat.number_of_times_throttled",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "CGroup # Elapsed Periods- {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.os.cgroup.cpu.stat.number_of_elapsed_periods",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Index Memory Lucene",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Lucene Total - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Doc Values - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.doc_values_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Stored Fields - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.stored_fields_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Norms - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.norms_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Index Memory Lucene 2",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Lucene Total - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Terms - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.terms_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Points - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.points_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Index Memory Lucene 3",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Lucene Total - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Term Vectors - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.term_vectors_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Fixed Bitsets - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.fixed_bit_set_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Version Map - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.version_map_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Index Memory Elasticsearch",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Request Cache - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.request_cache.memory_size_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Query Cache - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.query_cache.memory_size_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Fielddata - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.fielddata.memory_size_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Index Writer - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.segments.index_writer_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Indexing Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Indexing Time - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.indexing.index_time_in_millis",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Indexing ThrottlingTime - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.indexing.throttle_time_in_millis",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Request Rate /s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Search Total - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.search.query_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Indexing Total - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.indices.indexing.index_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Indexing Threads Queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Write Queue - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.thread_pool.index.threads",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": true,
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Write Rejections - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.thread_pool.index.rejected",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": true,
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Read Threads Queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Search Queue - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.thread_pool.search.queue",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": true,
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Serach Rejections - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.thread_pool.search.rejected",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": true,
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Get Queue - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.thread_pool.get.queue",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": true,
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      },
      {
       "alias": "Get Rejections - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "source_node.name",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "node_stats.thread_pool.get.rejected",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        },
        {
         "field": "1",
         "hide": true,
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "source_node.name:$Node AND cluster_uuid:$Cluster_UUID",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "$Index - Index Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "Index",
   "collapsed": true,
   "panels": [
    {
     "title": "Index Overview",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 1 },
         "type": "raw_document"
        }
       ],
       "query": "index_stats.index:$Index AND source_node.name:$Node",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Index Shards Overview",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 1 },
         "type": "raw_document"
        }
       ],
       "query": "index_stats.index:$Index AND source_node.name:$Node",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Index Rate /s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Indexing Rate Total",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.indexing.index_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Indexing Rate Primary",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.primaries.indexing.index_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Search Rate /s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Search Rate Total",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.search.query_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Search Rate Primary",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.primaries.search.query_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Document Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Total Doc Count",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.docs.count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Primary Doc Count",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.primaries.docs.count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Index Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Lucene Total - {{term source_node.name}} {{field}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Terms - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.terms_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Points - {{term source_node.name}}",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.points_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Index Storage Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Storage Size",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.store.size_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Segment Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Total",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Primaries",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.primaries.segments.count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "$Index - Index Advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "Index",
   "collapsed": true,
   "panels": [
    {
     "title": "Index Memory Lucene",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Lucene Total",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Stored Fields",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.stored_fields_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Doc Values",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.doc_values_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Norms",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.norms_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Index Memory Lucene 2",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Lucene Total",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Terms",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.terms_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Points",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.points_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Index Memory Lucene 3",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Lucene Total",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Fixed Bitsets",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.fixed_bit_set_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Term Vectors",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.term_vectors_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Version Map",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.version_map_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Index Memory Elasticsearch",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Request Cache",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.request_cache.memory_size_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Query Cache",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.query_cache.memory_size_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Fielddata",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.fielddata.memory_size_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Index Writer",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.segments.index_writer_memory_in_bytes",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Request Rate /s",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Indexing Total",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.indexing.index_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Search Total",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.search.query_total",
         "hide": true,
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Request Time /ms",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 39 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Indexing Primaries",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.primaries.indexing.index_time_in_millis",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Indexing",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.indexing.index_time_in_millis",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Search",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.search.query_time_in_millis",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Refresh Time /ms",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Total",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.total.refresh.total_time_in_millis",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      },
      {
       "alias": "Primaries",
       "bucketAggs": [
        {
         "fake": true,
         "field": "index_stats.index",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "index_stats.primaries.refresh.total_time_in_millis",
         "hide": true,
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        },
        {
         "field": "1",
         "id": "5",
         "meta": {},
         "pipelineAgg": "1",
         "settings": { "unit": "1s" },
         "type": "derivative"
        }
       ],
       "query": "index_stats.index:$Index",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}