apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"

resources:
  - peerauthentication-strict-mtls.yaml
  - authorizationpolicy-default-deny.yaml

  - destinationrule-circuit-breaker.yaml
  - virtualservice-retry-timeout.yaml

  - observability-telemetry.yaml


commonLabels:
  app.kubernetes.io/name: istio-config
  app.kubernetes.io/component: service-mesh
  app.kubernetes.io/part-of: istio
  environment: production
