---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    slack-token: AgCbnK+KONPj3N5k1XKIRqxMVoO/qXv+0DPbf+vzPHmd2ZBd6p6jHep0fbCqEp/deQ9OicLlDRKJ+O5xyYtI5sXcOo7IuL6dqeJbUYiMAlOcZYDIBmkl59mNVwmonMLcOv7V8rdJ6UsRYVsn960gB8he464BUsi4Irelj8cZfzprFLG9ADsJliLFNXClFoWljhrR82ONfEXK1RJh+hhRsycnWC7Hq/Cccd5MWGYxTCjN9iRr6/IkZy9oA6fWqfIJE6KOCLbz9wHOawOGfttMw809YTUVawDrf04YNMQoEouHl4CZigV7Fse0X0tZN75cyrzIfjJPjsecF+0+HSq6GdW/Quwvn53iqEkH2hGstMnM1yIPX1BT8H47KzQEPO5Nl5X7B9t7EhdH1mRg6Le8XYKbTivke4l+VqknBBVJYd1vC4qY5qSCskbuZrmmSJn2g/ber5JI/dJLc2m3tGgTRX30xRd1Csk0nm7JLgnA06kn1lh8dyUklPVvqm9veA9J7B0BdXeI3dun5cSy0ExERqlw+w5D3aYo/ZmGG1KrFM3s5lltAts4YLoL6cAfeGFmskQ7x80C/lCFSELDwPUIIySnLOhv0FMqZ1/hs/hM/qPDyS2UUUtSmKAp8wbMKkry8bDe7ElOqcL9dXETq1jIEhX8P25uAweGfGGAixMpId1tJANEot0yp2lw9myhsdIi7cgSUtjctAkcSIddfFWwAlM93OcCqnV+wExB/+WlRZD1IBiRhEjlL7pne9y9y/0cuOBqdlwla1NYjtJ/rk4MicUcfqbHWY7Z654djRTS3D3cbo8=
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
