---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    slack-token: AgCKrJFq+2dch1kubLzbfrh9jtwR4lqaOKeucYgEfWacEKbhdwgDpovhjuH/qOiUeESmI9lICGxqgS0JjXbHtMU69lkFGDBoqcOxvoBW/F+OuaXMaR0jZYej5vJ0YXOpt7otPhWDl3NEHwSekfTOkZEfTqtib39fULFAuabVQZQZinVAdmkElWknWzwFzmNO5KkdJHJsZBybuMH8tBCKV9uE4hH78C+H+nquvPS61fR3QrCwsDEWh3R6eDHRsdRrRuwADRHVMiHoE8UYuD8banwgPXzeN+c6vh1iy+bHHY6GRSC5awvixgMOPcBsAOkGVeOdn65a5WY9aeGvPxlrwzNVbAkNNm1oSEWwrxAZ4VSUu/3D1aD7wrA4lYnZ3nHtoqh7gokzb23XvueDzEFAk3UtcRsfa/PO6wORO3q2ngytvpbY0HBSniz5ymqQGF/fCcM/OxmU460FksYQZ6cppUiLl6W3InQjbYr+cbnTgYSKDfFrhcdktieln9Zr4vG934Pd6sDjLrdemIJncfOxcrJsObNAHMTlgZ1ci+hzO4Azpo5pT4JDpylLjKj7gqQfjpu2DzywVAnUJwSEQ1hQh8tqsyJwW0ibGH0zWF9vNcoiTf7EjBvqiLSRS3mPXpEjuWy4JQr/074g6SOUkC0BTLB8RX00XNC5fdPDHCewTPqT/gkdnB6q+Gry4fFCu79vI8A2gVTGeDolfGPoiAz0u7aKabVOVEcmsmShJPwiz3caMHs4IF9R0SQdKdpt8Ir1ZEazGDyVfMlcAinAVfjVPgwDkDWdTwZXvsqHY83d+/8qXcg=
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
