---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    slack-token: AgBJT0lvbwDf3YgosH4TG+Wcdz2M49wMZUwt36z0ti0PQKLtzUXL7GNxkJAD863zxznKHuac0Lt+ZIwf3AXC8Aywb4lj3AarkmZgx87NpSkb6avYFRj2sewYOlxV32h70UKYnmqYfrBkHwARUPo1SBoMvVyaEQ52dZemh5lvK8NL2WB1nd+LQloUJybk69Rf3yak9yfh0aUVGo2n6o3l6Rub73a7PXJonKTKipw0gdrVwAKcParWxegGDgg7uSXqCgVK/wbIhEC4uTwWz596+lgmXHVPcWZBNTE4comZT4S94jqSJeU+PrldiF97QZZBXhlPQ00d485Pr+gcW9bv8CoBMhtNN7VajNC7PBjoLF+bqM6B9iLooPqv+zkZk2SQ/CrN8tm13J7ATgdZA5iBRw8+APKFlg8hFOLGiULpvUPoabOdBUoLd3Ajwr88kzoe+llx5JQF6tzr6WFJLtiYxklBfiGjPWwJiQ9aNc9JWqxKI6n308QMqhWAdDVkLMMoP3ud0UszVo60N0BK9S7Fpmel2lq8Ne9s8ilMhBkAnjGAEd0wkPF8MHuBarkQdvngsvSOfKEZ5oQaCYMCYn/Cx9S+uwqqX1WakzyvM+HZUEQl29vxqigejJa3mM6CbOygc896FfyUtDQe2nwHEUGwoqqKx+hj/+9E9kgTikaTbCWF/pQrEsYhP3tU5qJPhoZ1NV65X8O61Aep2tDQ8A==
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
