---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBkaLVYG1ePCmfHw89kndwwq4eyfkDqYyUKOIkJUI6/7phKiTbGDe11GY16zsVyzHGIF7pqRqmo46wd1tAJx7KrLsqu6sZ0avrEsY6ro5birxEQPniOaYjq95zm3jM6AuxG9Owju/w2/ebPXlmfaQGKYIBT4iN2YabjW3qw7Dvhe2mGsRE0RPNIyn6cii2r58e8Y1GYf9tK+RHkYqBnXxAm23c9l7dzgWQfMSr4F+gCP/jMBEkV905DPRrgGuLVsiXY7lEtL4XtcjPB6wSCGUQURDknsMxYeJbR+8mF4rHtxotalElMEBKFs2abwlAO1T3HiZbD46iWJA5XWuWQUyhHxBfeu0B72n+TSVbz8RlDlsxAulpzW8ydgPWsDN9BE9Epn8PEZlwF+qzxgeNxwmh0arpWBbIsE5Em9phQxYgmHBnK6QjM2oel8QVuiOnH01m7TeyUJBHDlonIV15IuypFdvvWsPIWaWfglDDWDYZBLP3hBRiMN5KNT8zdDBb5LRzAM962WOtzeloSFGN0kqS7H0+qPjQhrWXUoueeCx9SljwcSGTvogXj/t4F7LM7M05F9tU5Qdvro+5zTTNO2m2C/jP4GpxGO7A74S3ZpEH565znPbP96r7bdvGtKZ1b2A0cpg0OLHXLAeRPxCyL4X6A3gh8VoCa1CSgxC2jrfrkXsGTZktTJ+9o7v5zv91vjOKanZJDOfSgO7NsOjziHiGzZ5teR7fY+L0=
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
