configs:
  rbac:
    create: true
    policy.default: role:readonly
    policy.csv: |

      # ROLE: ADMIN (Full Access)

      g, cluster-admins, role:admin

      # ROLE: DEVELOPER (No Delete!)

      p, role:developer, applications, create, */*, allow
      p, role:developer, applications, get, */*, allow
      p, role:developer, applications, update, */*, allow
      p, role:developer, applications, sync, */*, allow
      p, role:developer, applications, override, */*, allow
      p, role:developer, applications, action/*, */*, allow

      p, role:developer, repositories, get, *, allow
      p, role:developer, repositories, list, *, allow

      p, role:developer, clusters, get, *, allow
      p, role:developer, clusters, list, *, allow

      p, role:developer, projects, get, *, allow

      p, role:developer, logs, get, */*, allow

      g, developers, role:developer

      # ROLE: DEPLOYER (CI/CD Bot)

      p, role:deployer, applications, get, */*, allow
      p, role:deployer, applications, sync, */*, allow
      p, role:deployer, applications, action/*, */*, allow

      g, deployers, role:deployer

      # ROLE: VIEWER (Read-Only)

      p, role:viewer, applications, get, */*, allow
      p, role:viewer, clusters, get, *, allow
      p, role:viewer, repositories, get, *, allow
      p, role:viewer, projects, get, *, allow
      p, role:viewer, logs, get, */*, allow

      g, viewers, role:viewer

      p, role:drova-admin, applications, *, drova-tenant/*, allow
      p, role:drova-admin, repositories, get, *, allow
      p, role:drova-admin, clusters, get, *, allow
      p, role:drova-admin, logs, get, */*, allow
      p, role:drova-admin, exec, create, drova-tenant/*, allow
      g, drova-admins, role:drova-admin

    scopes: '[groups, email]'
