apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: drova-shell-exec
  namespace: drova
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true
spec:
  kprobes:
    - call: security_bprm_check
      syscall: false
      args:
        - index: 0
          type: linux_binprm
      selectors:
        - matchBinaries:
            - operator: In
              values:
                - /bin/sh
                - /bin/bash
                - /bin/dash
                - /usr/bin/sh
                - /usr/bin/bash
