apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: lldap-bootstrap
  namespace: lldap
spec:
  background: false
  match:
    any:
      - resources:
          kinds: [CronJob, Job, Pod, Deployment, ReplicaSet]
          namespaces: [lldap]
          names: ["lldap*", "onboard-helper*"]
  exceptions:
    - policyName: disallow-privileged-containers
      ruleNames: [privileged-containers, autogen-privileged-containers, autogen-cronjob-privileged-containers]
    - policyName: require-run-as-non-root
      ruleNames: [check-run-as-non-root, autogen-check-run-as-non-root, autogen-cronjob-check-run-as-non-root]
    - policyName: disallow-capabilities
      ruleNames: [adding-capabilities, autogen-adding-capabilities, autogen-cronjob-adding-capabilities]
    - policyName: disallow-capabilities-strict
      ruleNames: [require-drop-all, autogen-require-drop-all, autogen-cronjob-require-drop-all]
    - policyName: require-resource-limits
      ruleNames: [check-resource-limits, autogen-check-resource-limits, autogen-cronjob-check-resource-limits]
    - policyName: require-resource-requests
      ruleNames: [check-resource-requests, autogen-check-resource-requests, autogen-cronjob-check-resource-requests]
    - policyName: restrict-image-registries
      ruleNames: [check-image-registry, autogen-check-image-registry, autogen-cronjob-check-image-registry]
    - policyName: disallow-latest-tag
      ruleNames: [require-image-tag, autogen-require-image-tag, autogen-cronjob-require-image-tag]
    - policyName: require-probe-timeouts
      ruleNames: [check-liveness-probe-timeout, autogen-check-liveness-probe-timeout, autogen-cronjob-check-liveness-probe-timeout, check-readiness-probe-timeout, autogen-check-readiness-probe-timeout, autogen-cronjob-check-readiness-probe-timeout]
