# Cilium für Staging Edge-Cluster
# Components: arm64-arch (nodeSelector kubernetes.io/arch: arm64)
# Resources: kein single-replica nötig (Cilium = DaemonSet, 1 Pod pro Node).
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ../../base

components:
  - ../../../../../components/arm64-arch
