{
 "title": "Kafka Cluster Metrics",
 "description": "With Kafka Cluster Metrics Dashboard you can visualize the metrics related to Kafka server, Kafka brokers, producing and fetching requests, and java.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "env",
    "label": "ENV",
    "query": "label_values(system_uptime, env)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(kafka_controller_ActiveControllerCount_Value, instance)"
   },
   {
    "name": "service",
    "query": "label_values(system_uptime, service)"
   }
  ]
 },
 "panels": [
  { "title": "Genral Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Brokers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "kafka_controller_ActiveControllerCount_Value{service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ClusterPartitionCount",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_replica_manager_PartitionCount_Value{instance=~\"$host\",env=\"$env\",service=\"kafka\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "OfflinePartitionsCount",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_controller_OfflinePartitionsCount_Value{instance=~\"$host\",env=\"$env\",service=\"kafka\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Topic Topics Per Broker",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_controller_GlobalTopicCount_Value{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Broker Message In / Minute",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_topics_MessagesInPerSec_OneMinuteRate{env=\"$env\",service=\"kafka\",instance=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Broker Message Out / Second",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_topics_BytesOutPerSec_MeanRate{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total Message In Per Broker",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_topics_MessagesInPerSec_Count{service=\"kafka\",env=\"$env\",instance=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPUUsed(%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (cpu_usage_idle{instance=~ \"$host\",cpu=\"cpu-total\", service=\"kafka\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "MemoryUsed(%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{env=\"$env\",instance=~\"$host\",service=\"kafka\"}",
     "legendFormat": "{{host}} - Total Memory Used % "
    },
    {
     "expr": "(mem_buffered{env=\"$env\",instance=~\"$host\",service=\"kafka\"}/mem_total{env=\"$env\",instance=~\"$host\",service=\"kafka\"})*100",
     "legendFormat": "{{host}} - Buffered Memory % "
    },
    {
     "expr": "(mem_cached{env=\"$env\",instance=~\"$host\",service=\"kafka\"}/mem_total{env=\"$env\",instance=~\"$host\",service=\"kafka\"})*100",
     "legendFormat": "{{host}} - Cached Memory % "
    }
   ]
  },
  {
   "title": "Disk IO Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_write_bytes{instance=~\"$host\"}[5m])",
     "legendFormat": "{{host}} - {{name}}"
    }
   ]
  },
  {
   "title": "Disk IO Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{instance=~\"$host\",env=\"$env\",service=\"kafka\"}[5m])",
     "legendFormat": "{{host}} - {{name}}"
    }
   ]
  },
  {
   "title": "Network Bytes Sent by 1 Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_sent{instance=~\"$host\",service=\"kafka\",env=\"$env\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Network Bytes Receive by 1 Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_recv{instance=~\"$host\",service=\"kafka\",env=\"$env\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cluster Message in Per Minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topics_BytesInPerSec_OneMinuteRate{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cluster Message out Per Minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topics_BytesInPerSec_OneMinuteRate{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cluster Avg Bytes in Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_topics_MessagesInPerSec_OneMinuteRate{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cluster Lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicafetchmanager_maxlag_Value{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total Queue Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_TotalQueueSize_Value{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Partition Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "UnderReplicatedPartitions by topic-partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_partition_UnderReplicatedPartitions{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Topic's-Partition's Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_partition_Size{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  { "title": "Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Producer Request Bytes/1 Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_topics_TotalProduceRequestsPerSec_OneMinuteRate{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Produce Rquests Failed/Sec by [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topics_FailedProduceRequestsPerSec_OneMinuteRate{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total Fetch Request / Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_TotalFetchRequestsPerSec_MeanRate{service=\"kafka\",instance=~\"$host\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cluster Network Requests by 1 minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_TotalFetchRequestsPerSec_OneMinuteRate{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Produce Purgatory Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_purgatory_Produce_PurgatorySize{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Fetch Purgatory Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_purgatory_Fetch_PurgatorySize{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Garbage Collector Old Generation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_garbage_collector_G1_Old_Generation{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Garbage Collector Young Generation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_garbage_collector_G1_Young_Generation{instance=~\"$host\",env=\"$env\",service=\"kafka\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HeapMemory in Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 107 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "kafka_heap_memory_usage__1{instance=~\"$host\",service=\"kafka\",env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}