extraHostPathMounts:
  - name: sys-kernel-tracing
    mountPath: /sys/kernel/tracing
    readOnly: false

tetragon:
  image:
    repository: quay.io/cilium/tetragon
  enableProcessCred: true
  enableProcessNs: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 768Mi
  enablePolicyFilter: true
  enableMsgHandlingLatencyMetric: true
  exportFilename: tetragon.log
  exportFileMaxSizeMB: 50
  exportFileRotationInterval: 5m

export:
  mode: stdout

tetragonOperator:
  image:
    repository: quay.io/cilium/tetragon-operator
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labelsOverride:
      release: kube-prometheus-stack
