apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jaeger-basic-auth
  namespace: jaeger
spec:
  encryptedData:
    .htpasswd: AgCDCZ5lVeojPOyCWSRcR/ttOZXoJCFiiq5skhg14SlDtlj2tRXPtdBawJYOYV8ogSczWccoUBAOee+Xz8tBHYZz4ozdgc1w0hKFLvg19ubiuKx+cecoMAUbZmAnOUFQhW5aXDz2UW8pVek+p/ewU4otqwhGtHD48snmTiG65HvOtcY5OO+ZRUeCDT/HgMbuiafNpIa2c5j6gKu12qJzjZAi2gYmbL3asddv4Ms+emZT9hbnMDSxVJZMeVt2XeTuII9POVgiTuAV9bLhGGS74P+6hJF5MV0c9QkFwD3MqTjFef49C5L0lqj85SnSXyFE6oL3lt2Kaf4bSJW9XzgBtXX7KSddhixfMTCw0crSVCcFbiYciLsrDpnMBkY/eyzMbbA9htgHvye9yaxDh7J/giv9ZWDYaiXdukb0s6HzmykDOXFWOVxZa3IsDXIJc7eLEcMNvnyJ8WcJ/ca6NinijmU9S0AOOfBmCEUXvMrBw53W/tjh/Mmkl8Xc2pKn6dxM8WJTiG2zz8j6sTtmHuWQwOPh9PnH3zuBAx7ErAJON7YpMC0XOo6Nt9tl5zJBh0J7AKXo3IOp6POwKh170QBjlGi4+9XZDOCj9iV6fnE2JrTS2d2SiyRuEwqtZGf8SjeMntlIWBXj1hIgW1DkxDGnwWXCLMgHVux25A9FN+kGLMmPimwhykrx490Iklgbk0YCwaJqFqxljVsKRVPiaHWNH+e0fipEyUdJgQlSl9RffrpQpM8zf97D0vjk
  template:
    metadata:
      creationTimestamp: null
      name: jaeger-basic-auth
      namespace: jaeger
