apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate-operator

commonAnnotations:
  argocd.argoproj.io/sync-wave: "20"

resources:
  - sealed-secret.yaml
  - basic-auth-sealed.yaml
  - basic-auth-securitypolicy.yaml
  - renovate-talos-homelab.yaml
  - renovate-drova.yaml
  - orphan-pr-opener.yaml
