apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - applications-project.yaml
  - infrastructure.yaml
  - test-appset.yaml
  - staging-appset.yaml
  - prod-appset.yaml