---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messaging
  namespace: argocd
  labels:
    platform.domain: messaging
    team: timour
  annotations:
    argocd.argoproj.io/sync-wave: '17'
spec:
  project: platform
  source:
    repoURL: https://github.com/Tim275/talos-homelab
    targetRevision: HEAD
    path: kubernetes/platform/messaging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - ServerSideDiff=false
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jqPathExpressions:
    - ".status"
