apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - etcd-client-cert-sealed.yaml
  - httproutes.yaml
  - namespace.yaml
  - alerts
  - servicemonitors/argo-rollouts.yaml
  - servicemonitors/argocd.yaml
  - servicemonitors/cert-manager.yaml
  - servicemonitors/global-prometheus.yaml
  - servicemonitors/sealed-secrets.yaml
  - servicemonitors/metrics-server.yaml
  - servicemonitors/coredns.yaml
  - servicemonitors/envoy-gateway.yaml
  - servicemonitors/envoy-ratelimit.yaml
  - servicemonitors/istio.yaml
  - servicemonitors/external-dns.yaml
  - servicemonitors/keda.yaml
  - servicemonitors/velero.yaml
  - servicemonitors/cnpg-clusters.yaml
  - servicemonitors/cnpg-operator.yaml
  - servicemonitors/kafka-exporter.yaml
  - servicemonitors/strimzi-operator.yaml
  - servicemonitors/redis-operator.yaml
  - servicemonitors/influxdb.yaml
  - servicemonitors/elasticsearch.yaml
  - servicemonitors/elasticsearch-exporter.yaml
  - servicemonitors/vector.yaml
  - servicemonitors/jaeger.yaml
  - servicemonitors/opentelemetry-collector.yaml
  - servicemonitors/grafana.yaml
  - servicemonitors/grafana-operator.yaml
  - servicemonitors/kyverno.yaml
  - servicemonitors/n8n.yaml
