apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-operator
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    infrastructure.domain: operators
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/Tim275/talos-homelab
    targetRevision: HEAD
    path: kubernetes/infrastructure/controllers/operators/confluent-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: confluent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
