apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-runner-cache
  namespace: gitlab-runner
spec:
  bucketName: gitlab-runner-cache
  storageClassName: rook-ceph-bucket
  additionalConfig:
    bucketclass: standard
