---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infisical-redis-secret
  namespace: infisical
spec:
  encryptedData:
    password: AgCPm1jJ74RyaIt11vwcS7y/FzGiWdeRaEd7pGP0vYE1B053vIsrvw6YANBbp7HPJ6XyDk9ZdE/HEn7T7Fy4sJkIzJX7fSkyKWi40/MTMhvIAw+xUjCRT8Pugh6j336kZjYYvzN0tvRbz3byyK0jkOPn6umwzxrMf8KonUoKNZZm1aNInoJr8oBSul03uMi8b5tQ2Xy0YF6p3tRWDuGipSJfqZBuVx6pVy/l5ZoUlPQ1jmJJgN9rGvy/r2qxv9f2YBx8GZdloBK0V4bwV8V72JFE6ZRihRcp63/ThlL8CcERb4Qp9ALWM3K6ylkGKdNoHOj/oRmfzZ+qWCkzohGB7aKt0lLl4+kDuKkSUd7Q8h2eDarCZAtYY/oYVOm3y3Vel98H/ziQZ7R11AnevupkwocE4geKZonXhtRjCe4sfdPUOtYJ9MegYwfzyXyMMYlj/0/3CoHStU0YAJK1lLa6frOJJsvEVK6gytAOn9crsPQMu1TcCz9QfhBDLQ7SPuRYXMjNFSdA0f23TzBsUfwwG59dC8Q1PNSqyh9kBiBeqTfMOfFMXhUlhA6jPttlnBeXDjJljBFcjHjYWWAHvwdPO3tyqVw0QZotiXTC9i5a9sO+IcCuupjRCXlVLtjGorB0X5q6LPfr3O0lcAl3hVy3/NsI6TYNm3rX2wkoImUUVvTGRlgciTr8OAD3Z08/cb6lOwkvSIIwYiJl2rUuTDik/vQ7nDleT1cP6bL6Ru/hb2iEYMYoTWIjh3onucBwgw==
  template:
    metadata:
      creationTimestamp: null
      name: infisical-redis-secret
      namespace: infisical
    type: Opaque
