apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    infrastructure.domain: monitoring
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            observability.tier: enabled
  template:
    metadata:
      name: 'kube-prometheus-stack-{{.name}}'
      labels:
        app.kubernetes.io/managed-by: argocd
        infrastructure.domain: monitoring
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/Tim275/talos-homelab
        targetRevision: HEAD
        path: 'kubernetes/infrastructure/observability/metrics/kube-prometheus-stack/overlays/{{.metadata.labels.environment}}'
      destination:
        server: '{{.server}}'
        namespace: monitoring
      ignoreDifferences:
        - group: bitnami.com
          kind: SealedSecret
          jsonPointers:
            - /metadata/annotations
            - /metadata/labels
        - group: monitoring.coreos.com
          kind: ServiceMonitor
          jsonPointers:
            - /metadata/annotations
            - /metadata/labels
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
