apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: drova-staging
data:
  ENVIRONMENT: "staging"
  APP_BASE_URL: "https://staging.drova.timourhomelab.org"

  GATEWAY_HTTP_ADDR: ":8081"
  USER_HTTP_ADDR:    ":8082"
  TRIP_GRPC_ADDR:    ":9093"
  DRIVER_GRPC_ADDR:  ":9092"
  CHAT_HTTP_ADDR:    ":8084"

  TRIP_SERVICE_URL:   "trip-service.drova-staging.svc.cluster.local:9093"
  DRIVER_SERVICE_URL: "driver-service.drova-staging.svc.cluster.local:9092"
  USER_SERVICE_URL:   "http://user-service.drova-staging.svc.cluster.local:8082"

  KAFKA_BROKERS:    "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  JAEGER_ENDPOINT:  "jaeger-collector.jaeger.svc.cluster.local:4318"
  REDIS_URL:        "redis-drova-replication-leader.drova-staging.svc.cluster.local:6379"

  STRIPE_CURRENCY:     "eur"
  STRIPE_SUCCESS_URL:  "https://staging.drova.timourhomelab.org/?payment=success"
  STRIPE_CANCEL_URL:   "https://staging.drova.timourhomelab.org/?payment=cancel"

  MIGRATIONS_PATH: "migrations"
  SEED: "true"
