apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

namespace: openbao

resources:
  - httproute.yaml

# helm-test-Hook: unter kustomize wuerde der Pod als normale Ressource deployed
patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Pod
      metadata:
        name: openbao-server-test
    target:
      kind: Pod
      name: openbao-server-test

helmCharts:
  - name: openbao
    repo: https://openbao.github.io/openbao-helm
    version: 0.28.6
    releaseName: openbao
    namespace: openbao
    includeCRDs: true
    valuesFile: values.yaml
