apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: openbao-snapshots
  namespace: openbao
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  bucketName: openbao-snapshots
  storageClassName: rook-ceph-bucket
