global:
  tlsDisable: true

serverTelemetry:
  serviceMonitor:
    enabled: true

injector:
  enabled: false

ui:
  enabled: false

server:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi

  statefulSet:
    securityContext:
      pod:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      container:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL

  extraSecretEnvironmentVars:
    - envName: BAO_SEAL_KEY
      secretName: openbao-seal-key
      secretKey: BAO_SEAL_KEY

  dataStorage:
    enabled: true
    size: 5Gi
    storageClass: rook-ceph-block-enterprise

  auditStorage:
    enabled: false

  standalone:
    enabled: false

  ha:
    enabled: true
    replicas: 1
    disruptionBudget:
      enabled: false
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        disable_mlock = true

        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = 1
          telemetry {
            unauthenticated_metrics_access = true
          }
        }

        storage "raft" {
          path = "/openbao/data"
        }

        seal "static" {
          current_key_id = "homelab-1"
          current_key    = "env://BAO_SEAL_KEY"
        }

        service_registration "kubernetes" {}

        telemetry {
          prometheus_retention_time = "24h"
          disable_hostname = true
        }

snapshotAgent:
  enabled: true
  schedule: "17 */6 * * *"
  s3CredentialsSecret: openbao-snapshots
  config:
    s3Host: rook-ceph-rgw-homelab-objectstore.rook-ceph.svc
    s3Bucket: openbao-snapshots
    s3Uri: s3://openbao-snapshots
    s3ExpireDays: "14"
    s3cmdExtraFlag: "--no-ssl --host-bucket=rook-ceph-rgw-homelab-objectstore.rook-ceph.svc"
    baoAuthPath: kubernetes
    baoRole: snapshot
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
