pyroscope:
  components: {}
  replicaCount: 1

  persistence:
    enabled: true
    size: 20Gi
    storageClassName: rook-ceph-block-enterprise
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

  extraArgs:
    retention-period: 336h

  nodeSelector:
    node-pool: stateful

  podSecurityContext:
    fsGroupChangePolicy: OnRootMismatch

alloy:
  enabled: true
  alloy:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  controller:
    type: daemonset
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                    - worker-6
  configReloader:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 100Mi

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack

minio:
  enabled: false
