apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-oms-prod
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    platform.domain: messaging
    platform.homelab/tenant: oms
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  project: platform
  source:
    repoURL: https://github.com/Tim275/talos-homelab
    targetRevision: HEAD
    path: kubernetes/platform/messaging/rabbitmq-oms
  destination:
    server: https://kubernetes.default.svc
    namespace: oms
  ignoreDifferences:
    - group: rabbitmq.com
      kind: RabbitmqCluster
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
