apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oms

resources:
  - https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml
  - rabbitmqcluster.yaml

commonLabels:
  app.kubernetes.io/part-of: oms
  platform.homelab/tenant: oms
