apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

resources:
  - storage-rbac.yaml

helmCharts:
  - name: kubescape-operator
    repo: https://kubescape.github.io/helm-charts/
    version: 1.27.7
    releaseName: kubescape
    namespace: security
    includeCRDs: true
    valuesFile: values.yaml
