ksNamespace: security

capabilities:
  configurationScan: enable
  continuousScan: enable
  nodeScan: enable
  vulnerabilityScan: disable
  relevancy: disable
  runtimeObservability: disable
  networkPolicyService: disable
  malwareDetection: disable
  seccompProfileService: disable

clusterName: in-cluster

configurations:
  otelUrl: ""

nodeAgent:
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
    limits:
      cpu: 500m
      memory: 1500Mi

kubescape:
  resources:
    requests:
      cpu: 250m
      memory: 400Mi
    limits:
      cpu: 1500m
      memory: 1Gi
