apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
  labels:
    platform.domain: devops-platform
    team: timour
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: platform
  source:
    repoURL: https://github.com/Tim275/talos-homelab
    targetRevision: HEAD
    path: kubernetes/platform/developer-platform/renovate/base
  destination:
    server: https://kubernetes.default.svc
    namespace: renovate-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        maxDuration: 5m
        factor: 2
