apiVersion: netbird.io/v1alpha1
kind: ClusterProxy
metadata:
  name: homelab
  namespace: netbird
spec:
  clusterName: homelab
  serviceAccountName: clusterproxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterproxy
  namespace: netbird
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterproxy
rules:
  - apiGroups: [""]
    resources: [users, groups]
    verbs: [impersonate]
  - apiGroups: [authentication.k8s.io]
    resources: [userextras/*, uids]
    verbs: [impersonate]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterproxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterproxy
subjects:
  - kind: ServiceAccount
    name: clusterproxy
    namespace: netbird
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netbird-admin
subjects:
  - kind: User
    name: timour.miagol@outlook.de
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
