---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgC+iqn62kSzDtCpoNjH6JP3OQgRcAJuJDkwhhdDMBVy3OR8JpB34W/u420pYzj2ru7mOnbBNu2nLt8bpJNqSTjMZayfNe1q/TN3wTP2zdTEqGMDEE8VUv1OksooaGejkK5pJmiH42LGs/DcVZ7vT7b8QEtQ3cII15yNskpJ7LPDVS46UhMozYJLzp4QfQlW8t7TRLdMqQ1RvJsBsYeKIR9p+Ad7VxAtTWd82lT2kgWvrv9V6dTSeaXbS6hHZ5y0qsIh2CRncjAzsTfWcru7FFUZ4a9fu/6o3Lh0EY/jiT4VWQDuhMudowJ0BZ7EOMAhyPCCZUaNrkwjS3ufORk3449hRWOEwJ4BKrXX/jGCoOH4pLmXYPq6kw2jMpVhDeSfJsGQRFzkSaBBG+N8Kdlmoa/0WVeAxF2gfBFWzw1Fhr1tCX4EmPexEu3lVTxiWQpR3Y0yM9jaROFHQDdYzOKUfiVL83LLjegfwUvmtw8VohfGUG3tvTe/GbJ90sFguvTl9WSBXZY1dWuA9iuTONewAvgXhIAL+ZAb9OS2JAidFHAEgSGkL3ReO50hxRXK50Z7kXZaowY6mShL1gsjT133PofI1o961DVTv+NM6WNZNyoJR2TYmLrwC6CTSRNTWE+ftGoXUVG9m8+qkHhKUKGeS/JfHSnTfew6x+kQO66cfkhcyrE2N1fJTCawet3pFApGu4ZatPBOIbPfPodx6WYaR4D7+pqECZrEhU+Fswwe3chPQGa6Yp4CSjoG
  template:
    metadata:
      name: netbird-mgmt-api-key
      namespace: netbird
