---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgBFHzo+q07F32+ucJu2EsjxdpRXo+NGAf31W31jt70pgBrG33VWHvV+6UfoJsI6LHTb+8HTK1o+lpt88Jo0jVjpYqDkboU7q8F9O7TEe4CDUuLEzMVlw/3JOB1WTW/B7zjrwUyYqR8ysAkfz7wK9xIXz4boAWXT8iGHUGQ+3QYB0eSia+RwBWWFppkZiDCei+3Ap3uxF0ET3UpLxcbBQy07aXbIOvJujPl9qzT8cJu5g+XHTKqFwBxeShyz84ZrMkfjhjX2az0IkndhXzbBuRWtvrHutTxUjT8642mNN6zGjkQ95vrFR2jE/fkaqQZk+u1xmOWbvkS3Zn1AWS+DEcQL9aMoO+DB+CpYRp2jtMCUIEudRnVw3JjeABVtSgOU0JCWzv3VqO2ZKlOydpNlOkPv4IEHYYR9E5baeHSZjg7/lPmFyl9XkgPYtM2LxPSlpqqDhh2iOwsX/Wr1/wj2fa5EiHzSDDX27JzTHNX0MPcosJnLILyDMEdsZ4RW1RDzDeGpNRGGRv4P9IO/YNvSkyfW/6N2DHWgxfUlCIZG2fw4H+HNPyaaICHeOY1lwPhCz8D72fEHlnbaHMumzYh/Gh4OmaK5zBAmYxfjmepFjD0KVAF3g5AYT5YH8OB8rJ9fgaBx5S4eF+gWd1RhlUJeC+0uvXAQGjuQueHEH157clgJRP1CNJ6FqFaJatXqXbWagy1CpkVQzaAhU/zxvAsKEDZ+ktBGAkqQ6OmQqyNWe2f8wROGnt/fvyjy
  template:
    metadata:
      name: netbird-mgmt-api-key
      namespace: netbird
