apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lldap

resources:
  - resourcequota.yaml
  - limitrange.yaml

labels:
- pairs:
    app.kubernetes.io/managed-by: argocd
    platform.homelab/tenant: lldap
