apiVersion: v1
kind: ResourceQuota
metadata:
  name: lldap-quota
  namespace: lldap
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "5"
    services.loadbalancers: "0"
