apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rbd-csi-ctrlplugin
  namespace: rook-ceph
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: csi-rbdplugin-provisioner
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cephfs-csi-ctrlplugin
  namespace: rook-ceph
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: csi-cephfsplugin-provisioner
