operatorConfig:
  namespace: rook-ceph
  driverSpecDefaults:
    imageSet:
      name: rook-csi-operator-image-set-configmap
    clusterName: rook-ceph
    enableMetadata: false
    nodePlugin:
      priorityClassName: system-node-critical
      enableSeLinuxHostMount: false
    controllerPlugin:
      priorityClassName: system-cluster-critical
      replicas: 3

drivers:
  rbd:
    enabled: true
    name: rook-ceph.rbd.csi.ceph.com
    snapshotPolicy: volumeSnapshot
    controllerPlugin:
      replicas: 3
  cephfs:
    enabled: true
    name: rook-ceph.cephfs.csi.ceph.com
    controllerPlugin:
      replicas: 3
  nfs:
    enabled: false
    name: rook-ceph.nfs.csi.ceph.com
  nvmeof:
    enabled: false
    name: rook-ceph.nvmeof.csi.ceph.com
