crds:
  enabled: true

resources:
  limits:
    cpu: "2000m"
    memory: "2Gi"
  requests:
    cpu: "150m"
    memory: "256Mi"

priorityClassName: system-cluster-critical

annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

logLevel: INFO

allowLoopDevices: false

enableDiscoveryDaemon: true

monitoring:
  enabled: false

csi:
  rookUseCsiOperator: true
  enableRbdDriver: true
  enableCephfsDriver: true
  grpcTimeoutInSeconds: 30
  enableLiveness: true
  provisionerReplicas: 3
  csiRBDPluginResource: null
  csiRBDProvisionerResource: null
  csiCephFSPluginResource: null
  csiCephFSProvisionerResource: null
  csiNFSPluginResource: null
  csiNFSProvisionerResource: null
