apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"

resources:
  - ns.yaml

helmCharts:
  - name: rabbitmq-cluster-operator
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 4.5.0
    releaseName: rabbitmq-cluster-operator
    namespace: rabbitmq-system
    includeCRDs: true
    valuesFile: values.yaml
