clusterOperator:
  metrics:
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
      labels:
        release: kube-prometheus-stack

msgTopologyOperator:
  metrics:
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
      labels:
        release: kube-prometheus-stack

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
