---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tempo-s3-credentials
  namespace: monitoring
spec:
  encryptedData:
    access_key_id: AgBkqkoxkUy61NQCqqSM7BA62mfcL++TTE9yc3AgNPFFqd5jdRSv6rdGhK4aPUVkbAA+odgp0KcWo2OaEGln/S7+wFSKKuuBwh/WCO6P2nV6P36hNXpYIUzjr59/F75GGfW/6DD/QOombUhUthoJiQjuroosZIjY0N67XgnyJnUIve+Vg4EMO+f0oU8MsU9z3/36WtCRnRKRey9pCxK/GAXzJQwrcnOVh9r3AjOL10Dp7CgmitKP4U6f9n/EG0jOoUPUQZRDlwnUzrXPbQY9yK9gc6ussvqGh+aMIEv2G3Hj3KzbGhanEEmlcO0h3M+1wdjq3Wv5pPSEJ3FAhp+f1R0J42I+6n7ctytf47ITV+RWdYRW/wfajs7ozx40J5l30z3D6ARInzpp9xP5a6efknudr5GSc9o4aQ8PWR1ePy7id/xy6UTo1HuVzJgFZnpCKgBGZz245sDKLycTTa0WHad9XYBs7q2oP/jMU5bGipVCc3eG7SLex8FpeR5x1LyUY/XMTt5sqVKDaCe/YRdlzHuwDg8gMSdi7LgyMGXrwSilzNONDLMyt2+OcKSrbKOKESl23pcKyPARKwc0vKQMJLgTGU5boQqThXPBdNDJwRFFnoK3E9tbDj5m3459Ns1/iIPecEF3shqzgpPJ23yavsizSJQE8rZq4Rt4lVoH6SOVjuU2cwSsXPy0slVo4S8dwKJEJeIgKo3KTkGGXKzEyg7ExZCmvw==
    secret_access_key: AgDSKh49DICXfsEs151olmRYjvqMAMMh8BgxQRsxmNeKzYJZFULqly78agQ2Ed9Miyer/LEM5bMOxF5o7pw6J6OlNebcmbHfydsCWmDTn2P16BjxHUkGrUcjp6N/IucPRnyrWW/kwT/E712qI5n3/ADrFdsSfWlJEHOST03AvSRycgKVHJXac/C6hhtfkpFCR53aUq7vxnhH/T9RBoJI0YMWgslx/J34WtdlxhEt9A1KCBGqSL6qTZ0faBRP4ia6Il29ynE9Wcij80vDU16NvXIbdhJVd9bKT6iZD750H4En3vn+WAaF99t4tJcvY7C8dcM2/s2DOz1un/elobnwjO8AZpfktEsSsNF8VFuKX00fRbDKGZZxqRn/xzTmJnHZXrg9webjYYFOpyF6MjscvWONWPnnvJohv44RCJWzDXizQ7eLlxsoL/dTmpv7ooKdZn4MNTYW2t0aifhjXxC8sBlrtkh1HKggAi1eiGFGaKCS1CgzoN2mtL/nOtqLLMKrHNQjUJ4lRhPjv/FE2nqk6PTDHpansYK3CXiEnQw0GtjByFxJ9BtrDPrnVDJ0EA5f21I+bLaZkFjZgs0Puydi+93lrZJJrgcqZZ2NGUvlDjPkddpByxW/BjdzumO501VMfKpNb8jYzRi67VpPZGoc2ewNINaAZtl7I4gcOXYfcY4MgtopFYPDp+WN+eiyPgzAyleNtHW02lVAIAJqn+JnCMpHA9H+4gnUWzN9fReTs9DXq1xCE/60Lvtz
  template:
    metadata:
      name: tempo-s3-credentials
      namespace: monitoring
