---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tempo-s3-credentials
  namespace: monitoring
spec:
  encryptedData:
    access_key_id: AgA8LJxXvnoWDi3gQoC+21I78cdclKcDpvt+sZBf/W4iSZ2ASH7ehHLLbWgD/MzHDxl318dMWJ8Y94leGC+TCO4dP6eQKWFsdwMR6B5QNkR5NrH8nhIpIRHVqSjW4naV240h01ufJSF+SnvJLiU+s13liCw9DDqL16COb5N1nXFeVTmfZGM7OVtjobh0mxgiXV/5gbccn6qJE6Ybh+hnfeNSr2JR+uFAXYcfJzNy+wbvKmTlKYxxQg94fZVKaesMRaEV3m/3uaqSR36RhftzlQ6ZdMoWpeZcutoIkZYkC8jWDL+Ok1pOQsm8LJzwNNxslWCRM9ryDqT3zu5lyxILt1VDjEelq5JtfPtBpjK4ajxckN7K0O68AT5c6S/9M2wCX8q8otgrtFqiQ1GrzEQyAzU0gAZ+dmh8GgDNcnJ5C420kf5B2BdSSDeXfQzwPDS4opJ6S4cj3dTj9sGzr19o2/uq2S0GSDuTvvbG7oDkW1q8H6rpSY1+HcP9n+sSMOMEQxy8MwG+QGcDCucCRkM2ym19yuzBpNVnfrkeAGODpY/KaMeK1fk5NdwyFFCFMAIyN52udfvzpz6WzqnORgsoPTc7rln5Qiv3PSRJgKsZywoApT6BnynA2ak2v8UJYpkWYk7J51Wu2/gm2NIuYn3Dwp+UCCl7UTCwAOaXhTE5lIl6SfIolWWTzhiPGJvzWugteAu06FZKr4nReG8QrV6zxHuhRbcQgg==
    secret_access_key: AgARL5vim1F9TSUuGsc+TtoTiO6mcnzzgH5TL5FoMW0ZgBsmhZQ7RE1qsQLmvW9gfsKa4PvFtCwWaRiRrD1Mr7NClqm5it7Be1niMfACoYHyQ8x5wQXZt0ozS+R+0pJ83gxV67Sx5/w1WngGvLiPSaQcZAEEW/Raizq1Msp7gB6LQ/Qyrx+uphgyDGic3oCgnJBRTXAsw1MCCy0j3fTBGgtcJ3d0fZC3rmPxIbSkJBjW2kK79rXrT2VPLLDqQDx6Vj/upZRkBn+VIpE0i+PIRq+ut2AXsaHTtmelrqaDMHC3gdb+oQsS0hPQyHtc8DXQub2WHqXUGpsBSxRGL/DMd+bq7zMw/6AObr/EVo6dfbLIK7HolucKc2N8oq/U6w0dWEfXIhmwIhPek7hCK21EQfdpAqnf0WO3XHb0IMii0Zy4BOs3cHaNf2fPdI2me0kpDJ9QAq8iX29AWuo6Djr4GEHx37E1BAaci5j4TpZWlaIdXSaKd8b7h3chFrG1/X1ei6KjGpQ94xrymbh1XbiIg4uKG+/XA/lojgcUkim4QxxzYCfmAfVQ+g5AVQ4GGFbndRIevhVEHJoOlMTQUVeDktiWg6rHghEeiq1o6EqXrLLcH95fmgE5lizsuQqJcDKgROO0HyGbiC7lZ3/8WM6GvdhePQYSmOA133E+sqTkDqZ+s3g9P41ivslgIbRGbo2xu0vP7vKKOL3xfpOlQ+L27ErZUoWXgvcz/fYs2zAXn6X7Zvqj8uVuQ51k
  template:
    metadata:
      name: tempo-s3-credentials
      namespace: monitoring
