apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-drova
  namespace: drova
  labels:
    app.kubernetes.io/name: redis-drova-servicemonitor
    app.kubernetes.io/part-of: prometheus-operator
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - drova
  selector:
    matchLabels:
      app: redis-drova
  endpoints:
    - port: redis-exporter
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
