apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs-proxmox
  namespace: monitoring
type: Opaque
stringData:
  prometheus-additional.yaml: |
    - job_name: proxmox-host-node
      static_configs:
        - targets:
            - 192.168.0.50:9100
            - 192.168.0.57:9100
          labels:
            role: hypervisor
      metric_relabel_configs:
        - source_labels: [__address__]
          regex: '([^:]+):.*'
          target_label: instance
          replacement: '$1'
