---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: elasticsearch-snapshots
  namespace: elastic-system
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: elasticsearch-cluster
spec:
  generateBucketName: elasticsearch-snapshots

  storageClassName: rook-ceph-bucket

  # - ConfigMap: elasticsearch-snapshots (BUCKET_HOST, BUCKET_NAME)
  # - Secret: elasticsearch-snapshots (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY)
