apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rook-ceph-rgw
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-rgw
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
