apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubescape
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - security
  selector:
    matchLabels:
      app.kubernetes.io/instance: kubescape
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
