apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-cluster-operator
  namespace: monitoring
  labels:
    app.kubernetes.io/name: strimzi-cluster-operator
    app.kubernetes.io/part-of: monitoring-stack
    tier: platform
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kafka
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
