apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#  APPS DEV ENVIRONMENT - COMPONENT CONTROL

resources:
  # CHILD APPLICATIONS - APPEAR IN ARGOCD UI

  # - audiobookshelf/application.yaml  # DISABLED: Resource optimization
  # - kafka-demo/application.yaml  # DISABLED - Only kafka-demo-prod needed
  - n8n/application.yaml

  # - code-server/                    # DISABLED - VS Code in browser
  # - jupyter/                        # DISABLED - Jupyter notebooks

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: timour-homelab
      app.kubernetes.io/domain: environments
      app.kubernetes.io/layer: apps
      app.kubernetes.io/environment: dev
      team: timour

commonAnnotations:
  argocd.argoproj.io/sync-wave: "26"

