---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: renovate-operator
spec:
  encryptedData:
    token: AgANHhS60NfaJbtNiZ+xJEpgsGKXHH2gZoxpMjManabxl9LMClF89lkMIImQBkp8NqV0azBVFhk8thoeskazjsinaPz9l+GJFZwLBqYNlLW4tjpnrx3E6yCp24LawO/04ewMVMUUFqprnDtBKBtSVOPVGHM6lxNKbel0PH+l3lv9jnegvrYAFSs1LIpeMhVE+Oa3diy3aDXxZMKyCLDf2J6m6cec0jl+tLCK1pZVGtkB02BOUIAP9EqMoHgpsfmjsAQQO7sn0rHJZR2zi9XsACPnU/u8s2TGq6+PB/JZ+GU5kEnkaS9Sw4gYwvpVgGHFw6gwc71Wtl3wVpSeFKza3Unxh3uz8kjq6amDJlLdWiS6+MGSw4W33/84EEbScOr+lprFLyOchlKPWrPMbSeTzVQGsO1H6yy0wUK9GsXopjqC8IK0gB7U1FBvac4W3Pmj8XnPdOiZpq5n6pHW7WP/mEMANDCNbhmIGSsxhOkUYb+ijqdmZDxb6QogQkVEXNK09AAIpVh0Q5gv+sbccsBrm5k/PAGbwRcILAmTuiIkwOxJk3FgrY24Qcnqk7coTYuIr08yJwITkxzNj9njq0Pwqx3evpTVt8fgUGFxUzobhBajg8pxLuQTp2BxbJS2hcRdqNKaZ+pqiaQ1rHDxKLxKhvccXTVfBhlrC6/RsUVgiuM+VPyzp70xcfl7GqJasnMafBcp5l43ivWMJMjE+pqzRhkw+du2mdwGom0h88kV9VaPWGd46Hk=
    username: AgBJAHlJlZ8JzItEtr86JXtBClqQ0PfSaAHID7MkwH3JO/udQj5DiqRn+AwQ0QnQXyEQDDQ9AAmd/BtNgZ5klEcsJzMNOJskXTgdNyqtR/OQPoZSF4Vs5c4GQDADtBmfNsKTy0o94HCC6hg59qSbOLsKQMCqI1RQ0fFPyUOfmmOVFwtqNKCphawMqeUqbWSONdN4fPp0gkYI3HJxc39lYOKd5Og0QKr9aJXiPPE1t15idRxg8klF9mJSee/EaKHPWlXcw39187N6RMoFJn1lykWi3KxSmSHS+qEuqiwLbJXCjGKMdg6aSlWRFRG07qCM9xEphsyI7FlV1/6UOI4Da7vYEkYmWiLTqPYoGfZ4rohI5QEKmg7Ri4VnGZCOD8V4tSWvyjQ0KkUdONZUhwEEAA2UjKCkpbyqh5vJKfDv1kAz0CfzqWrvYOi36UeqOB7YBGipfpdTDQjogpLOUgJnidQv2dkPXFXY9uoO2z/liMnZ3M+PKHqsFEbFCDfO+TBAhpMBnyjlzg1fzEvGg7qXxu/F+4xbVwnPviJTkNSd+x0kbb1zhHFm3wwpoHkbIZtkLIXoKVXQ3XT2Q6aFtIBKkWiUJWa0z/T6+UOqcEd1HZ3dchsjT5kM63pDklgjwZWqJv58zMrpd92oHCCaFolCGml5bzRuKyWkMgJmjk53G1OVYleU1c9M9WyjSUaJlP1Gcjfb346x/difW2o=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: renovate-operator
