---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgAoo4IPyvABndpO5OYbbmIJRrwb7slviwDcY5m17DftUVrX4qCoonMfkUPl7I2PO5x0QqYuwNscR0wMBHCfjUOdvh/PmT+B9sIwl/XoKs29Ik+Lx3WG/s7cyxiZSCF2dlyg4EpPFSC8br9RiXAdSJqq6uBTuAqv7hbT6FG0VYD0rPDMYLnboofFYRhLTipVzF+sJEq+WU9+1dXDrwOuM3P7IaFlCHbUIo0z8V2oOjy7ZSW8BpecmZ23Fzy+VebyHFzyg2vKq7TyYOaXgSk2yg/+W8vCK51ng7Win6v9p8XXi/LrnEbZiAJ+/Iy/eS+Yr9D9jO/4NqxYT75TgEoQ89W8igqsXaYglYS6SptBcIntLOnsaHJY00pWZK07AkHRJaz6x7tPqZIiPS8ASDwsYTWbYxtMHThyemj2X8NpSpbY+DBNk8Pw5iWt9t1MmdF0UuzH2L62v1LRqRdNj3TprdUMVbgDxpPr5IhKtE3ESA8nk3qx1QIoEBc6pQ/kUD5SjfqrmgVOAvO6bxYGKHQLROAG+cmTGQ407feM/jjhK1CnnvlRjzRGbbakiVUyN7omsXIeqbmfjzc8ynu6Xizx0ppcEN4uCMQ+NdVx9XzXSDRc0/puX+AczsT7T6GyUbwJuSkxm+h4Q9m9XZyTc0ERrs9v9VFF/EJdUSrrUDvNw++oPkazwrxaipBwq3OVENXK6nnN02kYJMe6r1jNBQxtBYpZmdm0SMactAV8WICTRlfKVxwC+fBqUX2XhmyRyxq8PnRmLeGqvXoB3qvpJ2GYjsZQoZRA0QEQElBLZ7RI8vPK1OdiM2MXT3mByKQer50=
    RENOVATE_TOKEN: AgCQJy8RAZLIgHoMud20Xhb7DQxUSCZlRbYX54ATyCgNjVPGlCTTaRa5D7NAlPFvdRNkn+JCZoWQPdL8T5Jv18rljox/lLkZj7uU7KEKl36qr35MLIz5JvaipozljwHYSZRITNo2og13h5JT0yucqHj16VXOqOHUM8LqBbBM0/drBWgH/3KWeKmbQsTbRK+yiqTVa/4oj1Y5yeBWWBKHIsUAT+A59WBVpq36y79JKEG3ClHXsxzgJMNqad8sdTblbSuSwIXGEMbi308txYe5H6pnw3FUeV9IJIo9bp+JYcc22amXnvKLyJUmBPy7PGdTaEIHn4ElMOAZps/YsRsnkz+NSyHEAETJhfb6qo2YsBxau0FLvC2DRlSa0yxgyj3mw1id1D1+uLe/Cgo5JAO3S0juhHLfODq3DTsGLU++xTEdFqjFqFXD3AZEWj7cz0Q7Ko1DpqUSySRlpR60MtBE80M6J0knfwM4dqsOqPkXNREFq7C7EJaMafBLoOMVMGij2w9+cyT0aKKL/3rcVHZVPvNuGHavWuv8+KN8LrvlY+EP5oMtRl6Bi5X+f1MuThhdjonFa8IUuQv/MBAl5jMXZa8wxra/j7SYKuLTcnxBenjeAhI6jQqCBMpnyJXpl8Pu1HRSlq/ufVXY9e4AbclXzR2Mnd8YhP9tEge7VtPcVNvyGgJspDAgWRkBBkTeklgbtKe/vfbc7N9tvbHrSibrwI1z9Hp3eD/g67ShPh/JSdsLHtMBtFPLOMqnzoBbe+eTRjgnimCnIi4jIfvkNdAscK4GJKGdafCSv0v0is4RJdbImrYSmvSmcR5c0sLesMo=
  template:
    metadata:
      creationTimestamp: null
      name: renovate-secrets
      namespace: renovate
