apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: renovate
  namespace: renovate
spec:
  background: false
  match:
    any:
      - resources:
          kinds: [CronJob, Job, Pod]
          namespaces: [renovate]
  exceptions:
    # Renovate-Bot writes to /tmp (workdir) — needs writeable rootFS
    - policyName: require-non-root-filesystem
      ruleNames:
        - check-root-filesystem
        - autogen-check-root-filesystem
        - autogen-cronjob-check-root-filesystem
    # CronJob-Pod resources via Helm-chart, sometimes missing
    - policyName: require-resource-limits
      ruleNames:
        - check-resource-limits
        - autogen-check-resource-limits
        - autogen-cronjob-check-resource-limits
    - policyName: require-resource-requests
      ruleNames:
        - check-resource-requests
        - autogen-check-resource-requests
        - autogen-cronjob-check-resource-requests
