name: yaml-lint

on:
  push:
    branches: ['**']
    paths:
      - "**.yaml"
      - "**.yml"
      - ".yamllint.yaml"
      - ".github/workflows/yaml-lint.yml"
  pull_request:
    paths:
      - "**.yaml"
      - "**.yml"
      - ".yamllint.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install yamllint
        run: pip install yamllint

      - name: yamllint
        run: yamllint -c .yamllint.yaml .
